### ISSUE TITLE
How about to implement the owner name in the Android app ?

### ISSUE THREAD

**Issue by AntonioGPS** [gopro/labs#10]
I am missing this feature or I did not find it

**Comment by dnewman-gpsw** [comment]
you can simple type the command **!MOWNR="Your Name"**  into the Added Command field in the mobile app.

**Comment by AntonioGPS** [comment]
You need to remember that not so easy command. I believe a dedicate field should be easy to implement 

⁣Dr. Antonio Rodríguez Franco
Universidad de Córdoba
Campus de Rabanales
Dpto. Bioquímica y Biología Molecular
Edificio Severo Ochoa
14014 Córdoba

Obtener BlueMail para Android ​
