### ISSUE TITLE
HERO11BLACK GoProLabs firmware issue - start at gps motion not working

### ISSUE THREAD

**Issue by LADIDO** [gopro/labs#100]
I used this feature with HERO9 so I'm sure I can use it. But The HERO 11 when accept the command oSoB1oC!SK1H5!R, it displays the gps trigger info, but the gps speed remains 0 also when moving. So the recording doesn't start. However, when I start recording manually, the gps information in movie is correct, the gps reciver works. I've tried several settings and combination settings.
Recording on movement trigger works correct.

Have You any info about how to solve this issue?

"info version":"2.0"
,"firmware version":"H22.01.01.10.70"
,"camera type":"HERO11 Black"

**Comment by dnewman-gpsw** [comment]
I have confirmed that there is a bug in GPS Speed capture.

**Comment by dnewman-gpsw** [comment]
Found the issue, will be addressed in a future Labs release for HERO11
