### ISSUE TITLE
HERO11 with GoProLabs debug

### ISSUE THREAD

**Issue by LADIDO** [gopro/labs#101]
Hi, please explain debug info. After recording QR code the log starts with 
debug:APPC_VIDEO_PROTUNE_ISO_MODE_MANUAL

It seems camera react propely on light conditions while I have shutter angle locekt at 180. But the message doesn't give a sense ... ISO MODE MANUAL is not available

**Comment by dnewman-gpsw** [comment]
These should go in discussion, not a bug the github pages.

The message is left over debug, not an issue.  The message just means you set an ISO min and/or ISO max.
