### ISSUE TITLE
AI feature request, please add possiblity to communicate with GoPro Player

### ISSUE THREAD

**Issue by neurosynapse** [gopro/labs#1015]
Hello,

We are using GoPro Max 360 degree camera for defect inspections and using GoPro Player (by far the best player to watch 360 degree videos) to watch them manually. We have trained several AI detection systems for automatic defect detection. The full pipeline involves converting video to frames using ffmpeg and doing AI inference on them. Our output is json file with frame(image) names and detection found. It would be nice if we could find a way how to pass this information to GoPro Player so at specific video frames during the manual watching process this information could be shown. It would be nice if you could really add this feature in this AI era.

Best regards,
Roberts

**Comment by dnewman-gpsw** [comment]
Unfortunately that software is outside of Labs Firmware development, but I pass your idea along to the developers of Player.

**Comment by neurosynapse** [comment]
Hello,

Thank you! It would be nice if we could arrange online meeting with the team. My contacts are roberts.maurins@aerones.com

Best regards,
Roberts
