### ISSUE TITLE
HDMI out AND gopro screens?

### ISSUE THREAD

**Issue by awrebels** [gopro/labs#1017]
I have the media mod for the gopro 12. Is there a setting (or possibility) to enable the front and/or the back screen of the gopro while HDMI is being output via media mod? 

Using the cam for IRL streaming. The front screen would be helpful for reference of people I'm filming. Back screen for me. 

thanks!

**Comment by dnewman-gpsw** [comment]
I believe it is a hardware limitation. Not possible.
