### ISSUE TITLE
Feature Request: automated SolarTime in DailyTimelapse

### ISSUE THREAD

**Issue by The-Paw** [gopro/labs#102]
I would like to have the automated daily sunrise time-update from this https://gopro.github.io/labs/control/solartimelapse/ in this https://gopro.github.io/labs/control/dailytl/. Possible??

**Comment by dnewman-gpsw** [comment]
This is not an "issue" with the web pages, use discussions so more can view the answer.

Yes they can be combined, just add !U before the !R in the solar script.

**Comment by The-Paw** [comment]
Thanks .. but I would like to use the time in the daily sample ;)

**Comment by dnewman-gpsw** [comment]
You can do that.  These are just examples, you can modify as you need.  If you not have the scripting skills, post a question on the discussion forum https://github.com/gopro/labs/discussions
