### ISSUE TITLE
Naked gorpo QR not always beeping  ?

### ISSUE THREAD

**Issue by Yamboss** [gopro/labs#1021]
issue with naked (no screens) GoPros that are recognizing all the QR codes, though some QR's don’t trigger an audible confirmation. There are also certain settings that are missing, like the maximum shutter angle, that can't be adjusted through the app, which is something we need to address. to fix the un-blurred image and action look.

thank you gopro for this labs option really reminds me of magic lantern just safer to use !

**Comment by dnewman-gpsw** [comment]
As a Magic Lantern user from years ago, yes it was an inspiration.

Explain how "maximum shutter angle" in missing?  Technically no GoPro camera has a minimum of maximum shutter angle in default firmware.  Labs doe shave some shutter speed hacks to remedy this.

**Comment by Yamboss** [comment]
Although I use the Exposure Max feature, I find it doesn't always deliver the level of accuracy I'm aiming for. Specifically, I'd prefer to incorporate additional ND filters to avoid pushing the shutter speed above 1/200. This approach would not only enhance stabilization but also prevent the footage from adopting an overly sharp, jittery appearance.

**Comment by dnewman-gpsw** [comment]
No idea on the beep missing.  You can always trying adding !B1 to the QR Code, as that is the beep command.
