### ISSUE TITLE
media mod audio out via hdmi? 

### ISSUE THREAD

**Issue by jamiefletchertv** [gopro/labs#1024]
Is there any config im missing to support outputting the media-mod mic audio via the HDMI=1 clean output? 

Currently running Go Pro Labs Firmware for Hero 11 Black v2.30.70 into an encoder a HDMI encoder and im not registering any audio.

**Comment by dnewman-gpsw** [comment]
Audio should be going over HDMI, it was in my brief test to a TV.

**Comment by jamiefletchertv** [comment]
Thanks. I hadn't yet tested on a different output. And can confirm the audio is passed through (**Facepalm**) so i'll debug where in my encoding chain its getting lost.

**Comment by jamiefletchertv** [comment]
Re-opening this issue as it appears to be related to the Power supply given to the camera. 

Can anyone from GoPro confirm the Amp requirements to power the MediaMod Mic? 

Im currently able to drive the GoPro in a 12v/1A DC-PD to USB-C Supply from an encoder (instead of a typical 5V/2A mains) with a setting like this https://gopro.github.io/labs/control/set/?cmd=mVoMPRES=%220,4k50pWide%22r4p50e4!NfW0thS0dR0aScNd1b1wAi16M1S0x0sLag0v0q0dVoV0B1D0R0C0S1W0L01!MWAKE=1!MTUSB=1!MHDMI=1 

Most ancillary options (GPS, etc all off) and only the main camera functions. 

So it would be really useful to know if any more settings off will same enough headroom to power the mic :-)

**Comment by dnewman-gpsw** [comment]
You are powering everything, the camera and the media mod, you will need at least a 5V 2A USB power source.
