### ISSUE TITLE
Labs broke my camera

### ISSUE THREAD

**Issue by blekivagyok** [gopro/labs#1026]
Installed gopro labs to my hero 9, scanned the QR code made with command "!LRT:Y:1" to remove the 15 min timeout in hindsight mode. Then I could only see the video on the screen, whatever I did nothing of the controls or settings came out. I formatted the SD card, and copied the regular hero 9 firmware onto it, now it does not show the hero labs text when I turn on the camera, but other than that, nothing has changed. Still cant do anything, cant even turn off the device ad it is hot as hell.
Ay help is apperciated.

**Comment by blekivagyok** [comment]
It has been on for like 10 minutes, it was so hot I could not even hold it in my hand. Quickly removed the battery before it explodes.

**Comment by dnewman-gpsw** [comment]
If holding the power button down for 10+ seconds, then releasing for a hard reset doesn't help, you will need to contract GoPro support. It sound like your camera either has developed a hardware failure or had an incomplete firmware update. 

The command you listed is not a valid command, I expect it would not do anything.  Can you show me where that command was suggested?

**Comment by blekivagyok** [comment]
Thank you. Yes, after a while I found out that it was not a valid command. Chatgpt told me to type it in, I dont really know why, since it is not even close to anything like the hindsight timeout commands... I will contract GoPro support tomorrow.
