### ISSUE TITLE
Switching between Log and Standard does not work if preset has different names.

### ISSUE THREAD

**Issue by arosl** [gopro/labs#1031]
Hi I have two video presets, SiteVideo and Cine. SiteVideo we use for quick videos of underwater sites. While Cine is for underwater cinematic videos. 

For Cine we have set 24fps and shutterspeed of 48 etc, and wanted to use "Log" and a more involved postprocessing.

However we can only switch between Log and Standard if the preset is named Cine, if we use a Cine QR code that switch it to log, and then use a SiteVideo that use Video it will not switch over to standard/video. That only happens if the preset keep the same name as the preset that switched it to standard.

Or ( as I just realized making this issue) we need to scan the QRcode two times if it has a different preset name to get it in or out of Log.

SiteVideo:
https://gopro.github.io/labs/control/set/?cmd=mSoMPRES="12,SiteVideo"r4p24e1!NfL0tcNd1w55i4M1x0sMg0v0q0dPoB7D4R1C5SW0oMHIST=10oMHSTP=1,90,42oMLEVL=3oMWIDE=1

Cine:
https://gopro.github.io/labs/control/set/?cmd=mLoMPRES="10,Cine"r4p24e0!NfL0thS0dR0aScFd1b1w55i4M1x0sLoMHIST=10oMHSTP=1,90,42oMLEVL=3oMWIDE=1oMEXPQ=48

**Comment by arosl** [comment]
If the settings start with mV it will not go out of log. But if it starts with mS it will go out the second time you scan the code.

**Comment by dnewman-gpsw** [comment]
The issue is the QR Code set the mL or mS, after the preset is defined. This is an order of operations issue, if you use oMPRES=.. first then mLr4p24 etc, it works. The QR generator has been fixed.  Should work correctly now.
