### ISSUE TITLE
Bug in GoPro QR Code Creator

### ISSUE THREAD

**Issue by JerryDiver** [gopro/labs#1049]
There is a small bug on the creator https://gopro.github.io/labs/control/custom/

The Wind Reduction set to OFF does not work, it registrates as AUTO when QR is scanned
![image](https://github.com/user-attachments/assets/d795b503-53ac-4c69-b015-aa807f204fab)

It works though if the code is put in additional commands

**Comment by dnewman-gpsw** [comment]
Which camera model?

**Comment by JerryDiver** [comment]
Hero 12

**Comment by dnewman-gpsw** [comment]
Seems to work here.

**Comment by JerryDiver** [comment]
Ok tried about a dozen more times with different other settings, for me it's a no, but like mentioned, manual input works

**Comment by dnewman-gpsw** [comment]
there no difference between manual entry and using the Wind Reduction check box.  Use your smartphone to scan the QR Code generated, they are the same.

**Comment by JerryDiver** [comment]
Yes they are the same, can't deny that, just my Gopro 12 just does not read it as so, either from the PC screen or printed on paper.

This one does not work with my gopro
![image](https://github.com/user-attachments/assets/461e6b0d-89e4-432a-b812-06b0646a4733)

When the aS command is manual put in last position, all fine, no problems
![image](https://github.com/user-attachments/assets/224d0339-9849-49a9-bb6c-57c84b3a6147)

But I will close this, as this probably only concerns my 12.
