### ISSUE TITLE
Maximum Shutter Angle Bug

### ISSUE THREAD

**Issue by avanjool** [gopro/labs#105]
I'm using a gopro hero 8 and attempting to set maximum shutter angle but I can't get it to behave any differently than selecting a custom shutter speed in the camera menu. Currently if I set it to 45 degrees it will stay at that shutter speed even if the scene is completely overexposed. Am I misinterpreting the explanation of this feature as described here: https://gopro.github.io/labs/control/maxshut/ ?

**Comment by avanjool** [comment]
Here's an LRV: [https://github.com/avanjool/gopro-test/blob/main/GL010524.LRV](url)

QR code used (iso min and max set to 1600 to show shutter speed is locked and not increasing when scene is overexposed): https://gopro.github.io/labs/control/set/?cmd=mVr4Tp30oX1fXte1aWcFb1wNi16M16S180x-.5sLg0v0q0dVoV9B9D4C5S1W0

Could you share your hero8 QR code?

**Comment by dnewman-gpsw** [comment]
You have a locked shutter, so the camera can't use the EXPTX exposure control to limit shutter speed.

This is will fix you camera setup:
https://gopro.github.io/labs/control/set/?cmd=mVr4Tp30oX1fXte1aWcFb1wNi16M16S0x-.5sLg0v0q0dVoV9B9D4C5S1W0

You had i16M16S180 <- forcing a 180 degree shutter.
Replaced with i16M16S0

**Comment by dnewman-gpsw** [comment]
unless in know for sure it is a camera bug, please you the discussion forum https://github.com/gopro/labs/discussions as it will be easier for other to learn and find answers.

**Comment by avanjool** [comment]
My apologies for posting here, I guess I'm confused then. If I set the shutter speed to auto on the QR code generator page it doesn't allow me to select a maximum shutter angle, how are you able to do this?

**Comment by dnewman-gpsw** [comment]
Via this page: https://gopro.github.io/labs/control/maxshut/

**Comment by avanjool** [comment]
Ahh thank you for the help!
