### ISSUE TITLE
LOGB Offset parameter is not reaching -128 values as expected

### ISSUE THREAD

**Issue by tivikoff** [gopro/labs#1057]
Hello. After series of tests I noticed that  LOGB = [base],-128 does not produce expected result. At least what I can see - is that offset's behaviour continues as expected until value around -96 ~ -98 and then any lower offset value doesn't make any difference. So output gamma curve with offset -128 is identical to -96. Which should not happen if we check [the curve's math](https://www.desmos.com/calculator/sfxqtunzty). 

You can see these real footage graphs where I highlighted luminance levels at 10% and 90% (red) to be reached by blacks and whites respectively at offset = -128, but this never happen. Curve "squeezing" stops after -96 or so, with 7-8% blacks and 92,7% whites (green), like there is some internal limit for this parameter. But I believe that it should reach -128 while help tip offers to use both LogB 400 or 200,-128 as an example.
![image1](https://github.com/user-attachments/assets/a007577e-c135-4c2e-b6da-999f84184468)

I also reproduced this gamma coversion with dctl with LogB curve formula inside and applied it to the footage with offset = 0 to replicate the output image with offset = -128, and got expected result with 10/90% limits in this synthetic digital test:
![image2](https://github.com/user-attachments/assets/11e6f19f-ab33-4a3a-bdef-7839cc078fbf)

I use GP Hero 11 with the latest labs v2.30.70 fw. WIDE =1, NR01 =1, BITR = 160, HIST, 24Hz.
Tested with LogB 113 (Flat), 200, 400, 800 - results are the same.
Thanks!

**Comment by dnewman-gpsw** [comment]
Simple math error, looking at the code the amount of black lift was limited to 0.1f on unity scale, so that maps to 102 on a 10-bit scale.  Do you have an application for -128?

**Comment by tivikoff** [comment]
Thanks for letting me know. Yeah, checked and currently black are at ~8% (82 on 10 bit) and whites at ~92% (941 on 10 bit) which corresponds with offset -102.

At offset -128 they should be at ~102 for blacks and ~921 for whites, right?

I personally don't use offset and prefer to shoot in LogB 400 or classic Flat curve. I just noticed this while testing my custom dctl for GoPro conversions in different scenarios, including LogB [200,-128]. 

However, offset = -128 limits at 10% IRE level are pretty similar or a bit higher than multiple log gammas like s-log3, arri log, f-log, d-log, etc.; so may be convenient as a starting point for some cases.

Sad to hear that H11 is no longer maintained, considering that it still has the same sensor and processor as H12 and H13. I don't know if the internal code was rewritten, making it harder to maintain, even for bugfix. But it seems like a 2-year lifespan is unfortunately too short.
Thanks anyway!

**Comment by dnewman-gpsw** [comment]
It is maintained, just unlikely to see another Labs update anytime soon. This very minor Labs bug, doesn't cause the main firmware to go through a new release.  Labs use mainstream releases to address it own updates, otherwise the QA costs are too high.   HERO11 has had 8 firmware updates so far, pretty stable camera now.  There might be updates in the future, just can promise any.

**Comment by dnewman-gpsw** [comment]
Fixed in HERO13 with 1.12.70, it will be fixed in upcoming HERO12 or 11 builds.
