### ISSUE TITLE
Hero 13 LABS issue

### ISSUE THREAD

**Issue by IvanhoeFPV** [gopro/labs#1060]
hi, my new HERO13 freezes after updating to LABS and keeps flashing. If I remove the card it keeps rebooting and I can't even get to the menu to do a factory reset. pls help

**Comment by IvanhoeFPV** [comment]
LABS broke my camera guys. Please help!

**Comment by dnewman-gpsw** [comment]
Send a video of what the camera is doing.  "After updating", and "keeps flashing" sound like opposites to be.  Is it in an update loop, or is it booting and than crashing?

**Comment by IvanhoeFPV** [comment]
Flashing was looped when the card with the update file was inserted. The reboot cycled after removing the card. Now after the factory reset it looks fine

**Comment by dnewman-gpsw** [comment]
Close then?  All good

**Comment by IvanhoeFPV** [comment]
Probably yes. Maybe this could help someone. Thanks
