### ISSUE TITLE
DLRV=1 not working on H12 & H13

### ISSUE THREAD

**Issue by RikshaDriver** [gopro/labs#1069]
Recent documentation on the readme seems to imply that H13 and H12 now support disabling LRV by using DLRV=1.

Have tried on both cameras and can confirm this is definitely not the case.

Is this a typo on the README and do these still not support disabling LRV?

If so, would request disabling LRV as a Labs feature request for these cameras.

**Comment by dnewman-gpsw** [comment]
Please show me where. HERO12 and 13 do not support DLRV.

**Comment by RikshaDriver** [comment]
This bit in the README.md:

| Feature                                                                                     | H13 | H12 | H11/M11 | H10/Bones | H9 | H8 | H7 | MAX |
|---------------------------------------------------------------------------------------------|--------|--------|----------|-----------|----|----|----|-----|
| [LRV Disable](https://gopro.github.io/labs/control/extensions)                              | ✔️ | ✔️ | ✔️ | some | ❌ | ❌ | ❌ | ❌ |

**Comment by dnewman-gpsw** [comment]
Thanks I will fix.
