### ISSUE TITLE
GoPro 10 Black - Timelapse repeat query

### ISSUE THREAD

**Issue by Yatesc95** [gopro/labs#1070]
Hello, 

I am going to be filming timelapses in the Arctic this coming winter. The Gopro will be set running, but not accessible for 2 days, so I am wanting to run a long video timelapse, where the GoPro runs between the hours of 10:00 - 15:00, then the gopro goes into sleep mode and then repeats the timelapse again between 10:00-15:00 the next day. 

I have some AnglerFish housings, where the GoPro will be powered via an NPF battery to increase the battery length. I currently don't have access to these housings with the batteries, so I am struggling to test the code and whether it will actually repeat again the next day (as the GoPro dies before the next day is reached). 

Can I check this code with someone, who understands it (I'm very much a noob with this!) Will this work?:

 !10:00NmTp.10r4fL0!S!15:00E!R

I may be completely off the track, but it would be great if someone can point me in the direction of what I might be doing wrong.

**Comment by dnewman-gpsw** [comment]
The script looks fine. When is it failing? It is completely the first 5 hours timelapse? What does the MISC/qrlog.txt file show?

**Comment by dnewman-gpsw** [comment]
Closing from inactivity
