### ISSUE TITLE
EXPT wrong shutter speed

### ISSUE THREAD

**Issue by RikshaDriver** [gopro/labs#1079]
Using EXPT=1 would assume 180 degree shutter angle, so a frame rate of 50 should result in 1/100 shutter speed, 25 would result in 1/50 etc.

However, the output is instead along the lines of:

24p -> 1/50
25p -> 1/51
30p -> 1/61
50p -> 1/101
60p -> 1/121
100p -> 1/202
120p -> 1/242
...

This is happening on H11 & H11-Mini to H13. I suspect it may be the case for older cameras too.

Additionally, EXPT is not documented in https://gopro.github.io/labs/control/extensions/

**Comment by dnewman-gpsw** [comment]
It has it own page here https://gopro.github.io/labs/control/maxshut/

Also your experiment shows it is working as expected.  The $EXPS=1 feature does tend to round up the value for ISO and shutter.  There is nothing magically that happens at exactly 180°, the camera selects the closest readout time.  So 1/61, if you look in the GPMF metadata, the accurate way to do this, it shows the SHUT value is 0.0165164s (~1/60.5459).  The true 180 degree shutter is 1/59.9405994 and it don't expect even the most expensive cameras do that.  At exactly 1/60 you have 180.18°.

**Comment by RikshaDriver** [comment]
Will have a look at the GPMF metadata thanks.

I don't normally use drop frame fps as you know we use the 50Hz standard in Oz, but isn't the math something like:

angle / [ceil(fps) * 360] for the equivalent shutter speed?

So the inverse to solve for angle would mean 1/61 for 29.97 = 177 degrees

And 1/202 for 100p = 178 degrees

For full integer fps, shouldn't 100p @ 180 degrees = 1/200?

**Comment by dnewman-gpsw** [comment]
Correct, I had my math inverted.  

1/60.5459 vs 1/59.9405994 is 177.16°  Still good approximations of for 180° motion blur.

**Comment by RikshaDriver** [comment]
Maybe I'm missing something, but rounding up for drop frame would mean 180d for 29.97fps should be 1/60 and not 1/61
Equally, 119.88fps should be 1/240 and not 1/242

Even for "PAL" framerates, 180d 25p should result in 1/50 and not 1/51 etc

**Comment by dnewman-gpsw** [comment]
That is how it works. Nothing is going to change.
