### ISSUE TITLE
timelapse firmware update

### ISSUE THREAD

**Issue by amrossin** [gopro/labs#1080]
I have been trying to deploy GoPro 11s with this firmware update to record underwater for 24 hours, but they have been really inconsistent with actually taking photos for 24 hours. The longest I've gotten is ~8 hours but it's really sporadic. I factory-reset the cameras this week and re-tried with the firmware but only got 18 photos. Hoping for advice!

**Comment by dnewman-gpsw** [comment]
Use a HERO12 or 13, if you need high reliability for long duration timelapse.  But 18 photo sound ,more like you might have made an error.  HERO11 is typically good for 24 hours or 400 images or less.

**Comment by dnewman-gpsw** [comment]
If you want help on scripting, please share your qrlog.txt and script with the discussion area.
