### ISSUE TITLE
Hero13 external power not work without battery.

### ISSUE THREAD

**Issue by IvanhoeFPV** [gopro/labs#1082]
So another issue Hero 13. Not only that it still can't be flashed properly even if I did a factory then it keeps restarting but if I do a factory reset with LABS it seems to work but the external USB C power supply from my battery on the drone doesn't work. What worked better than the original FW in past LABS does not work now. When I connect external power and remove the battery from the camera, it stops working and reports low power. Guys this version of LABS is really not working…

**Comment by dnewman-gpsw** [comment]
You have scanned *TUSB=1?  This is required for bypassing power warnings.  There is a Labs release planned for next Tuesday that should much it more stable for initial setup. But you can try it now: https://www.dropbox.com/scl/fi/0qr5b3cxv92u8hcbkujhz/LABS_HERO13_01_12_70.zip?rlkey=xq4j34pblroafn2py7rcdwii6&dl=1

**Comment by IvanhoeFPV** [comment]
Thanks a lot. I downloaded the new LABS and external power without battery didn't work there either. But the flash has already gone through properly and the camera is also working properly after the flash. After the command *TUSB=1, external power supply without battery already works. Thanks a lot sir

**Comment by dnewman-gpsw** [comment]
That has always been the solution, so we are good. closing
