### ISSUE TITLE
GPS Bouncing Around and not accurate - Hero 8 - v2.51.75, July 2022

### ISSUE THREAD

**Issue by Walmer9** [gopro/labs#1084]
I updated the Firmware on my Hero 8 to v2.51.75, July 2022.  After doing so the gps coordinates are bouncing around and way off.  I downgraded the Firmware to LABS_HERO8_02_50_71 from I think 2021 and the gps works again.  The problem now is that the current Quick app forces a firmware update before I can access the camera.  I really like having the preview and remote functions on the phone app but I need the GPS to work. as an overlay.  Can anyone think of any options or is there a newer firmware update coming that will fix this GPS error?

**Comment by Walmer9** [comment]
Found a work around, use the old 2021 labs firmware.  With the new app you can click on a very faint grey bar under the blue "Install Update" button.  That lets you into the camera as usual without having to update.  Still wish we could get a firmware update to fix this.

**Comment by dnewman-gpsw** [comment]
It's been many years. I've never heard a report of this.  Labs should not modify GPS precision.  It's good that you found a workaround
