### ISSUE TITLE
Time/Timecode not updating via SYNC

### ISSUE THREAD

**Issue by RikshaDriver** [gopro/labs#1089]
I've deliberately changed the current time (by a few minutes) on H11 & H13, have tried the *SYNC=1 feature but neither seem to be updating the camera time nor the timecode on the video track after recording.

Is there a way to check GPS signal?

**Comment by dnewman-gpsw** [comment]
It does require a good GPS lock before SYNC has any effect.

You can check GPS with ```!D``` which will wait for an okay lock (waiting for a DOP less than 20.)

**Comment by dnewman-gpsw** [comment]
I just verified that SYNC is working. I set my clock wrong, and used this feature to watch the system time easily: https://www.youtube.com/shorts/6k6FDkDYpgs  Within a minute or so, the clock corrected itself.
