### ISSUE TITLE
H13 artefact on top with EXPS=1

### ISSUE THREAD

**Issue by RikshaDriver** [gopro/labs#1090]
When enabling EXPS on H13, a horizontal line artefact is appearing on the top of the screen.

![GRAB-20240924-124103b](https://github.com/user-attachments/assets/132cb00b-c8e8-4444-bc34-dec5dfb72568)

Using the latest 1.12.70 Labs firmware.

**Comment by dnewman-gpsw** [comment]
agreed, likely fixable.

**Comment by dnewman-gpsw** [comment]
This is fixed in the upcoming 1.20.70 release.
