### ISSUE TITLE
GoPro 13 black reinstall factory settings failed 

### ISSUE THREAD

**Issue by DanielRechinu** [gopro/labs#1092]
I installed latest gopro labs firmware released on 12 September 2024 and it didn’t work properly. Rec didn’t work from Quick app. I created an QR code settings that GoPro camera read but settings from QR doesn’t translate into camera video settings ( i try to set log with 1080 resolution and  camera sets on 4k log). And most important, camera don’t reinstall factory settings. I followed all the steps, via Quick app and manual , several times. GoPro camera still have GoPro labs firmware. What should I do more ?

**Comment by dnewman-gpsw** [comment]
There is a new release for Labs today.

GP-Log doesn't have a 1080p mode, 4K is the minimum resolution for Log modes.  You can check on the camera menus.

The stock firmware for downgrade should be up in a day or so.  It will be here in a bit: https://gopro.com/en/us/support/hero13-black-product-update/windows

**Comment by DanielRechinu** [comment]
Thank you.

**Comment by dnewman-gpsw** [comment]
Both new Labs and stock firmware are now available.  Closing
