### ISSUE TITLE
MUTE doesn't work on HERO12

### ISSUE THREAD

**Issue by pavlosharhan2** [gopro/labs#1093]
Firmware: LABS H23.01.02.20.70

This feature is very useful, and works great on HERO10, but on HERO12 I have to additionally run an ffmpeg pipeline to remove the audio. !MMUTE=15!SM3-1H5!R doesn't remove sound from videos on 12, but does remove on 10

**Comment by dnewman-gpsw** [comment]
This was just fixed for HERO13, and that should be rolled back to HERO12 in a month of so.

**Comment by sT0v** [comment]
How does MUTE=15 differ from DAUD=1?
