### ISSUE TITLE
Photo-Modes

### ISSUE THREAD

**Issue by jamesrdf** [gopro/labs#111]
In https://gopro.github.io/labs/control/custom/

Selecting the Night/Timelapse/Nightlapse Photo-Modes doesn't generate any GoProQR codes. I'd expect to see mPN/ mTP/mNP, but they are omitted.

I'd also expect to see a delay timer options (def 3s) for Photo Night mode.

**Comment by dnewman-gpsw** [comment]
Thank you. Now fixed.  The delay timer control has been on the wish list for a long time.
