### ISSUE TITLE
Hero 11 + Labs Firmware = Multiple Errors

### ISSUE THREAD

**Issue by ZedKah2** [gopro/labs#1110]
Hello everyone,

 
I bought a Hero 11 and The Remote (+ 1-year subscription) because I read in the GoPro community forums that with the Labs Firmware, one can extend the time out for Hindsight to whatever they want, instead of the default 15 minutes, which is **exactly** what I need, **and** is actually the SOLE reason why I bought this kit.

I love biking, I love photographing, but I HATE to stop biking to take a picture; so I bought a GoPro to fix it on my helmet, and I bought "The Remote" so I can control my camera without having to remove my helmet—that makes sense, right?

At first, things seemed to work OK, so I was a happy camper; I unfortunately soon became quite disillusioned… Indeed, after a few success stories (bike rides), troubles invited themselves to the party and never left since.

 
Here are the issues I’m facing.

First off, I think it’s worth noting that the ONLY command I input is the extended time out for hindsight, which is ’!MHSTO=480’.

Basically, this will extend the Time Out of Hindsight (**M**aximum **H**ind **S**ight **T**ime **O**ut) from 15 minutes to 8 hours (480 minutes/60=8 hours).

Like I said, things worked great at first, which means it should be fine, but then, here’s what happens.
 

I need at least 6 hours of hindsight, thus setting it for 8 hours. Usually, (aka: most of the time), things work OK at first, but, say after 2 hours or so, this will inevitably happen:

1. First, Hindsight goes off by itself, so if I start a recording, it begins at 1 second instead of 30, and I missed because The Remote will NOT tell me Hindsight went off by itself;
2. Second issue is that the camera will just turn off on its own, while it’s set to _never_ in the settings, and then, the remote will show "Connecting" (or something equivalent);
3. Third, the camera will stop recording and displays the message that _I need to upgrade to a faster Micro-SD card_, but I’m using a **Samsung Pro Ultimate 512 GB**, which **IS** indeed in GoPro’s compatibility list, and there, The Remote tells me nothing about it, and since I wear the camera on my helmet, I have absolutely no clue…

 
Kindly remember that in the beginning, I’ve been able to fill up this Samsung Pro Ultimate 512GB many times (that’s at least 6.5 hours of non-stop recording), maximum card can record is 8 hours at the rate I’m filming.

So, I need Hindsight to work all the time and if I cross a landscape which is worth photographing, then I just press the shutter on The Remote and boom: it starts recording—from the previous 30 seconds—so I can pull out some pictures out of the videos, without having to stop my ride, get out of the bike, and take a picture.

This is, again, the SOLE reason why I bought my GoPro and The Remote, but it’s just not working for more than two hours, which literally scraps my joy and makes my purchase completely useless, and for the price it sells, that’s obviously not good at all.

I’ve gotten in touch with GoPro’s support, many times, with no candy; this morning, I received an email from a GoPro’s customer service representative who wrote:

>  I am sending this email to follow up on your case with us. I would like to inform you that **our internal team responded to follow ticket that we have created. They informed us that the issue is only arising when you are using the GoPro Labs Firmware.** 
> 
> **They said that you need to contact the GoPro Labs Team through the discussion page to resolve the issue with the with the camera**. You may contact them through this link-https://github.com/gopro/labs.
> 

 
So here I am.

 
Again, the camera works fine at the beginning, and after two hours or so—maybe sooner or later, but that’s an average:

- Hindsight just goes off by itself, then later on: 😠
- The camera will shut off by itself, then later on:  😠😠
- Camera stops recording asking for a faster card.  😠😠😠

 
I do record 5.3K at 60fps, GPS is on, so is 10 bit, and high bitrate, but I tried to put all of them off, to no avail.

No other significant setting is changed from the default ones.
 

After the first time the issue happened, I took the precaution to always bring two more SD cards, so when the camera plays the fool with me, I can switch the cards. But again, after a while, the same 3 issues described above show up with the camera, no matter which card inside.

The two extra SD cards I use are Lexar 1000x, 256GB, C10, U3, **V60**, **SDXC II**—with two rows of contacts for faster transfer rates—and, while those are not on GoPro’s compatibility’s list, they are **V60**, which means **they won’t record slower than 60MB/s sustained**, so there’s NO WAY they’re not fast enough, GoPro stating that the minimum is 30MB/s aka: V30.

 
Troubleshooting steps I went through so far:

1. On a PC, **formatting all cards—NOT quick format, complete sector-by-sector formatting**, took over an hour for the Samsung 512GB, and about half an hour with the two Lexar ones;
2. Updating the regular camera's firmware to the latest;
3. Reset camera settings to default (Preferences ➙ Reset ➙ **Factory Reset** —> this I believe removes the Labs Firmware and, while I did not try in this mode, because this would be useless as Hindsight Time Out would be back to 15 minutes, customer support seems to claim I would not have those issues without the Labs Firmware installed (see their response quoted above);
4. Lowering recording settings—4K instead of 5.3K, no GPS, no high bitrate, etc.;
5. Replacing the camera—yes, that’s right, camera got replaced, yet, same issues.

FYI, heat is NOT the problem as this happened, among others, on a cloudy day when temp was ±20°C, which is FAR from being too hot for the camera; moreover, I did get the message that the camera shut down by itself because it was too hot, that was on a sunny day when the temp was about 32°C, so it’s definitely a different issue.
 
 
From my humble understanding of the Universe, and the laws that govern it, problems could be related to:

- The **SD cards**, but it seems it’s not since the issue arises with 3 different cards, and it works fine for ± 2 hours then, it starts acting;
- The **camera**, but it seems not to be the case since it happens with two different **new** cameras;
- The **Labs Firmware**, but as I said, I did not check that because even if it works, that’s not gonna work for me because I need Hindsight for at least 6.5 hours; 15 minutes will never cut it;
- A **Bluetooth hacking** that I am the victim of—The Remote and the camera communicates via BT.
 

I am here to find out which it is:

Am I the victim of a bug in the Labs Firmware, or am I a victim of a BT hack (you’d be surprised how BT is highly "hackable")?

Either way, I cannot work like that, and for the price I paid, I need this issue to be resolved.

 
BTW, worth mentioning as well that **those issues also arise while I’m simply recording, NO HINDSIGHT!!!**

Most likely worth noting as well that a fresh formatted card—even only by the camera—will make things work for a while, but not for long, and when issues start, they won't stop until formatting the cards again, yet, won't work for long.

 
I don’t even know if this post will be read by GoPro’s users community, or by the programmers who wrote the Labs Firmware, because I’ve been directed here by GoPro’s customer support representative, but I’m afraid, at this point, community will not be very helpful as GoPro’s customer service representatives couldn’t help themselves, but I am sincerely hoping that an engineer or programmer will be able to assist.

 
Looking forward to get a resolution on the matter at hand.

Sorry for the very long post, just tried to be as thorough as possible, so I don’t get questions for which I did not provide enough details upfront.

Thanks to everyone for your time and dedication.

Best,

Z

**Comment by ZedKah2** [comment]
Hey, forgot to add that I am obviously using an external battery pack, 20 000mAh...

**Comment by dnewman-gpsw** [comment]
Labs is experimental, no feature is promised or guaranteed to work. If you purchased a camera based on Labs features, that was likely an error. Hindsight for example, as limited in stock firmware to a length that could be guaranteed to work, they QA and test every published feature thoroughly to their specs. Labs firmware hacks Hindsight, turning off the guardrails, so the results are not guaranteed, as Hindsight is not tested beyond 15 minutes.  Hindsight is recording to your SD Card continuously, so it is going to be hard on the cards, it is likely the most demanding feature on the camera.  At 6 hours you're 24 times beyond what the camera is tested to do. 

Can hindsight work beyond 15 minutes? For sure, but the longer you need to run this feature, you might optimize your settings to reduce the wear and tear on the camera and the SD Card. Use 4K30 or 2.7K60, something the camera can do continuously even under hot conditions. You should also use 8-bit, and standard bitrate.  This could help extend the reliability for the Hindsight hack.  The bitrate Labs extensions do not work with HindSight, otherwise I would have recommended a lower bit-rate (BITR is ignored for Hindsight.)

"Preferences ➙ Reset ➙ Factory Reset —> this I believe removes the Labs Firmware"  It does not, as Labs can only be removed with a standard firmware install.  Factory Reset, will restore the camera defaults, although it doesn't reset any Labs extensions. For that, scan !RESET (and following the on-screen instructions.)
