### ISSUE TITLE
Why only QRcodes and no menu / app  items for settings?

### ISSUE THREAD

**Issue by jonas18z** [gopro/labs#1117]
In some situations, I like using QR codes (e.g., for multiple cameras or rental setups), but in other cases, I would prefer a more straightforward menu system. You still need an app or computer to generate settings, but it would be more convenient to connect directly to the camera and adjust everything right from the app. In those cases, a QR code becomes unnecessary. Also, it's not always easy to verify whether you have the specific settings you want. I know you can make presets etc but some time you just want to fiddle with the settings... 

Another issue is the use of unnecessary label for certain settings, like BITR and SPED. Why not write out what they mean and manage the variables internally? This would make the interface clearer and more user-friendly.

**Comment by dnewman-gpsw** [comment]
If Labs features a popular, they often migrate to main firmware, with more useability polish and multiple language support.  

What do main "use of unnecessary label for certain settings, like BITR and SPED". Are they too obvious? SPED should be permanently saved, not sure why you would see that.
