### ISSUE TITLE
GoPro 10 - sounds of "start video" and "stop video" is now the same

### ISSUE THREAD

**Issue by temp-64GTX** [gopro/labs#1119]
Good morning. Does it possible to fix this small but important issue?
On the previous firmwares (from 2022) gopro 10 had a different beeps of start video recording and stop video recording. Very handy, very useful. You can use camera without looking at it - you always know, when it starts recording, and when it stops. You can differentiate them by sound. 
But not now. 2024 firmwares - now both beeps are the same. It can produce bad experience. I lost a few footages, because it turned out that i recorded not the action, but mess in between actions. Very sad. Very unsatisfying.

**Comment by dnewman-gpsw** [comment]
This doesn't seem to be a Labs question. Labs doesn't change the camera beeps (or shouldn't.) I just tried HERO10, I one beep on record start, and three on record stop.

**Comment by temp-64GTX** [comment]
https://www.youtube.com/watch?v=agGNgNnE1oo
Here is a video demonstration.

**Comment by dnewman-gpsw** [comment]
Not happening here, so it is not the current firmware, assuming you have updated to v1.62.70. Try factory resetting the camera

**Comment by temp-64GTX** [comment]
today i did that factory reset. And beeps behavior does not changed. I think it's not a magic. It happens when i update my camera from Labs 1.46.70 to Labs 1.60.70. And it not changed when i update from Labs 1.60.70 to Labs 1.62.70.

**Comment by dnewman-gpsw** [comment]
I only have one HERO10, it works.  There is one not public release, you can try, as my camera was running that https://www.dropbox.com/scl/fi/ofxqq75xmouxoid37cdsm/LABS_HERO10_01_62_71.zip?rlkey=9ovsvnxr0cdl6ppv4f9anc6qi&dl=1

The change log doesn't mention anything on beeps.

**Comment by temp-64GTX** [comment]
ok, i found out the reason. It's DLRV.
if DLRV=1 then beeps fail.
if DLRV=0 then beeps are ok.

**Comment by dnewman-gpsw** [comment]
interesting, the three beeps must be upon the close of the LRV.  Also DLRV is not considered fully compatible with HERO10.  From the DLRV documentation - "Note: There is currently a bug in this feature (HERO10 as requires a restart after two captures.)"

Do use DLRV.

**Comment by temp-64GTX** [comment]
Am i right that now there is only two options left?
1) Do not use DLRV.
2) use DLRV and live with broken beeps.

**Comment by dnewman-gpsw** [comment]
Yes, an as DLRV is broken anyway, and not supported at all on later models, I would not use it.

**Comment by temp-64GTX** [comment]
That's kind of sad.

**Comment by dnewman-gpsw** [comment]
But logical and documented.
![image](https://github.com/user-attachments/assets/3e13a3be-bfe6-4f35-8937-fd31b5af2802)

If you really want DLRV, it works on HERO11 & Mini.  On H12 & 13, the LRVs are hidden by default. The only other reason to disable LRVs was for a slightly higher BITR support.  Yet on HERO13 BITR=300 is stable with LRVs.  So this feature is not coming back.  Labs dev is focused on feature that gain a user benefit, this one no longer does.

**Comment by temp-64GTX** [comment]
Glad to hear that the the LRVs hidden by default on H12 & 13. But i am walking past them, because there is no differences compare to a gopro 10. 
It is not clear, what will happens first - 1 inch sensor in gopro, or bankruptcy of gopro. Very interesting.

Anyway, this bug has been investigated. No further action required. Is there any else that i can help?

**Comment by dnewman-gpsw** [comment]
You are wrong about current cameras not being different, many users (youtubers) just incorrectly assume all feature could be be backported to old hardware. Two simple examples of big jumps form 10, a larger sensor, twice the memory (that made so many of the new feature possible.) Each generation get enhancements in power and thermal design, for example: HERO10 can be overclocked to around 170Mb/s reliably, a HERO13 over 300Mb/s, due to hardware improvements. HERO13 is a very nice camera.

**Comment by temp-64GTX** [comment]
I am never wrong. This "new" gopro 13 have exact same sensor that was in gopro **9**. The only difference is that they added a little bit of pixels on a vertical axis. This poor Sony IMX 677(L), they milking it already 4 years a row, that's insane. 
300Mb/s will have sense at 8k resolution. And 8k will be possible with a larger sensor. But not with this outdated guy from 2019.

**Comment by dnewman-gpsw** [comment]
Moving the goal posts I see.
