### ISSUE TITLE
QuickCapture Labs activation delay

### ISSUE THREAD

**Issue by RikshaDriver** [gopro/labs#1127]
When using QuickCapture with Labs parameters enabled (i.e. FLAT with LOGB=400 and other params), the capture initially starts off with the base parameters then seems to activate Labs features a second or 2 into the recording.

Using LOGB as an example, initial QuickCapture may start with LOGB=113 then adjust to LOGB=400

**Comment by dnewman-gpsw** [comment]
Yes, you can't use Quickcapture reliably with will Labs features.  Labs waits for the camera to start, QuickCapture starts before Labs.  This is by design.
