### ISSUE TITLE
Gopro Labs Nightlapse Photo Mode not working - Hero 11 Black

### ISSUE THREAD

**Issue by gerro25** [gopro/labs#1131]
Hi,

I am new to trying gopro labs and is looking to try the nightlapse photo mode for an extra long time lapse. I am using a GP Hero 11 black with the latest GP labs firmware installed.

I've tried re-installing the original GP hero 11 firmware, factory reset, the !RESET!1OR command, and resintalling the latest GP labs firmware but nothing seems to be working.

I am using the code mNPp.120eAfL0r0tdR0cGd1w55i16M1x0sM.

I've tested other functions of the GP labs and everything seems to be working as intended. Is there something wrong with the code I am using?

**Comment by dnewman-gpsw** [comment]
Do you have the Nightlapse Photo preset?  

Notes from https://gopro.github.io/labs/control/custom/
**Time/Night-Lapse modes:** The camera defaults to having presets for only one time-lapse mode and one night-lapse mode, yet both modes have two configurations (video or photo.) For all QR Code mode commands to work, a preset is needed for every mode you wish to use. e.g. If you only have a preset for night-lapse video (NLV), the QR command for NLV will work, but will not for night-lapse photo (NLP). To solve this, create a new preset for NLP, and both video and photo night-lapse commands will work.

**Comment by gerro25** [comment]
Do you mean a preset in the camera itself? Yes, I do. It would trigger the time lapse photo but it seems the camera is not shutting down as it's supposed to.

**Comment by dnewman-gpsw** [comment]
There is nothing in the command you shows to ask it to shutdown.  All just settings.
