### ISSUE TITLE
Bring back support for oX1 - MLM original

### ISSUE THREAD

**Issue by catch-point** [gopro/labs#1139]
Hero9+10+11+12 all support oX1, but not the current hero13 labs firmware. Please bring back support in the latest labs firmware.

### Discussed in https://github.com/gopro/labs/discussions/1123

**Comment by dnewman-gpsw** [comment]
The camera doesn't have those modes any more, so there is no longer a video mode for Labs to connect to.

**Comment by dnewman-gpsw** [comment]
Closing as not a bug.
