### ISSUE TITLE
Spot metering and Lock exposure in video gopro12

### ISSUE THREAD

**Issue by euromarco** [gopro/labs#1165]
Gopro 12....The code !2NoSL50,70 It only works in photo mode but not in video mode
Even by prefixing SM0
![Screenshot_20241109_000724_Chrome](https://github.com/user-attachments/assets/b1e94e4c-5952-478f-8ed9-9d380a035897)
Grazie, Marco

**Comment by euromarco** [comment]
![Screenshot_20241109_000949_Chrome](https://github.com/user-attachments/assets/a7b8b45d-18f4-49bc-8828-893bd1611366)

**Comment by dnewman-gpsw** [comment]
In my testing it works fine, however the on-screen lock guide will not show. So oSM10,10 will expose to the top left corner, it just will not show the UI graphics for spot metering.

**Comment by dnewman-gpsw** [comment]
Closing as not a bug.

**Comment by euromarco** [comment]
In the photo program the lock works and stays correctly

**Comment by dnewman-gpsw** [comment]
It works perfectly video modes here. I just reconfirmed using the latest HERO12 firmware. Maybe try factory resetting your camera.

**Comment by euromarco** [comment]
Yesssss! I succeeded, resetting gopro and changing the order of the codes. Thanks again dnewman-gpsw.
