### ISSUE TITLE
Add an Overlay to Video QR Code invalid on Gopro Hero 12

### ISSUE THREAD

**Issue by Grey-Sheep** [gopro/labs#1184]
### Discussed in https://github.com/gopro/labs/discussions/1183

<div type='discussions-op-text'>

<sup>Originally posted by **Grey-Sheep** November 25, 2024</sup>
Hi,
I'm trying to add a date and time stamp to my recordings (aka dashcam mode) and when I use the Overlay in the labs it always says "Invalid QR Code" regardless of the settings I use.  Other QR code work fine.

Has anyone else experienced this or know of a fix?</div>

**Comment by dnewman-gpsw** [comment]
duplicate
