### ISSUE TITLE
change owner gopro labs

### ISSUE THREAD

**Issue by jamondemono** [gopro/labs#12]
hello

I bought a gopro hero 8 to another person who had instaled the gopro labs firmware. I want to change the owner but it didn't change it. I create the qrcode with the command << !MOWNT="MYNAME\nMYPHONENUMBER">> in the screen apear my name and phone number but when I reboot the camera it's still apearing the old owner information. I try to change to the official firmware and change another time to de labs firmware but apperar the old owner information.

**Comment by dnewman-gpsw** [comment]
The QR Command:  !RESET
