### ISSUE TITLE
Hero 7 Black does not take lens FOV `linear` command

### ISSUE THREAD

**Issue by bartt** [gopro/labs#120]
The Hero 7 Black running GoPro labs v1.90.71 does not take the `fL` command or the `fN` command to change the FOV. The camera will always switch to the wide video mode when activating the video mode.

**Comment by dnewman-gpsw** [comment]
Labs doesn't add new lens modes to the camera.  **fL** does work on HERO7, but only if you are in a resolution that supports Linear.  **r4fL** will not work, as the HERO7 doesn't have 4K Linear.  **r27fL** will work as Linear is offer in 2.7k.  HERO7 doesn't have narrow lens mode (not that I could find.)

**Comment by bartt** [comment]
Thanks for the input dnewman-gpsw. Some follow up experimentation shows that POV doesn't take when combined with a zoom level. 

I *can* set the POV to linear in 1080p video resolution using `mVr1080pfL`. However, `mVr1080pfL70`--which also sets the zoom level to 70%, *does not*. Then the POV is set to *wide* with a 70% zoom level. 

In camera, it is possible to zoom to 70% with a linear POV.

**Comment by dnewman-gpsw** [comment]
Ahh.  HERO7 Labs predates the zoom commands.  So fL okay in some modes but fL70 will not work.

**Comment by bartt** [comment]
Dang. Would it be possible to prioritize POV over zoom? So that `fL70` would put the Hero 7 in linear mode without any zoom? Then one would only have to manually adjust the zoom level. 

Currently, switching from wide to linear (the current result of `fL70`) resets the zoom level and thus requires 2 actions: switch to linear and set zoom level in linear. Prioritizing POV over zoom level would require only one manual adjustment.
