### ISSUE TITLE
GoPro 10/11 motion detection using mask

### ISSUE THREAD

**Issue by suyunas** [gopro/labs#126]
I have GoPro 10/11 and using motion detection feature in which i am using a mask to capture movements.
GoPro will start the recording when seeing movements in the masked area. However, it wouldnot stop when there are no movements in the mask area.

Basically, I want the GoPro to stop recording when the subject leaves the masked area and enters the non-masked area. Kindly assist.

**Comment by aalse** [comment]
The best way to go about it would be to set the trigger so it only records for a fixed duration once movement in detected (1 minute, 5 minute, 15 minute etc). I don't think it's possible to set a second trigger for 'no movement'.

**Comment by dnewman-gpsw** [comment]
The mask bug has been fixed in build 1.20.70, released today for HERO11.  This will be rolled in HERO10 if there is a future build (likely) for that camera.

**Comment by henryatworkr** [comment]
Is this bug fixed for HERO9?
