### ISSUE TITLE
Construction Time Lapse Quits

### ISSUE THREAD

**Issue by Fisherman888** [gopro/labs#130]
Hi
I've had this issue with both a Hero9 and Hero10. The construction time lapse looks good at setup, shoots correctly for a couple days, then quits despite still having plenty of battery. This seems worse in cold weather, but that might have nothing to do with it. I'm typically shooting from 0800 to 1600 and taking 16 shots in that time.

I'm wondering if anyone else has encountered this and what the remedy might be. It can be pretty frustrating to lose weeks of shots.

Many thanks,
LK

**Comment by dnewman-gpsw** [comment]
Move this conversion to discussions https://github.com/gopro/labs/discussions), as that we where other users are that might have idea.  This is the page of bug fixes to be done.  

Labs features hacks and reliably for extreme timelapses is known issue.  On discussions, share the failing point from MISC/qrlog.txt - this is debug log that might show what failed.  Generally for more reliability, you want fewer shutdown and wake per day events.  https://gopro.github.io/labs/control/dailytl/ is better as it wakes only once per day, but uses more power.
