### ISSUE TITLE
Timelapse with overlay does not record

### ISSUE THREAD

**Issue by kyeotic** [gopro/labs#132]
When using the timelapse delayed start config (example below) everything works as expected.

![image](https://user-images.githubusercontent.com/1187432/199347599-4afe8027-7d22-4411-85d1-3acf2ab132b4.png)

However if I enable a timestamp overlay with "permanent" enabled recording never begins. Are these two options incompatible?

I've also tried combining the timestamp "burn in" command with the timelapse command using the **add command** input. I produced this QR code (https://gopro.github.io/labs/control/set/?cmd=!20NmTr1080!S!60EoMBRNO=15oMBURN="(0,35)[BRHH:MM:SSAA\nyyyy-mm-dd]"), which does record a timelapse but without the timestamp burn in.

Edit: After more testing it seems like the permanent overlay stops any scheduled recording from starting, even "Video". Is there any way to get a timestamp onto a delayed action?

**Comment by dnewman-gpsw** [comment]
Move to discussions https://github.com/gopro/labs/discussions  This is the wrong forum section, as this is for actions to developers to fix proven issues. Issues that are fixed or will not be fixed are closed, limiting user discovering. This is way discussions are better, that will stay active.

You need to include the camera model and firmware version.  On GP2 HERO10/11 support for overlays is really limited. Normal video modes like 4K30 or lower work.  I just tried timelapse video, and the overlays do not work.  This is not a bug, but architectural changes preventing the old hack designed for GP1/HERO8 from working in all video/tlv modes.
