### ISSUE TITLE
GoPro keeps turning on when connected to external power source.

### ISSUE THREAD

**Issue by LeoLopesLage** [gopro/labs#140]
I'm running the construction scrip with the U! command to sync with my cloud subscription.

I found that it only upload when connected to an external power source. So I did it. Worked and everything is in sync.

But, the GoPro keeps turning on every 5 seconds because it is connected to that external source... Than no buttons is pressed and the script put it to sleep. And it turns on again... loop.

Does anyone know how to fix it?

Thanks

**Comment by dnewman-gpsw** [comment]
Post question in discussions https://github.com/gopro/labs/discussions
