### ISSUE TITLE
stealth mode for cinematography

### ISSUE THREAD

**Issue by Czukuru** [gopro/labs#143]
Hi. I need 2 qr codes for stealth using in the frame of big production camera. With one qr i want to turn off all led's and both screens with permanent command to turn off the camera before the motion and than hit remote rec button with no light from the camera. And after that, another qr to turn everything on

**Comment by dnewman-gpsw** [comment]
This is should be asked in the discussion section.  Please move it here https://github.com/gopro/labs/discussions

It is a good idea.  Some might be already supported.
