### ISSUE TITLE
HSTO=x - minutes NEW

### ISSUE THREAD

**Issue by dhcrump** [gopro/labs#147]
The text states "changing from the default for 15 minutes".
On my 11Black the defaults are 15 and 30 Seconds - NOT minutes.

I want to be able to change the setting of HindSight in seconds.
Does x = minutes or was this a typo and it should be seconds?

**Comment by dnewman-gpsw** [comment]
This is the control for the timeout, not the duration of the hindsight.  So it is correct as written.  This is no Labs control to change the duration of the hindsight window, 15s or 30s are the only options.  If you want more than 30s you might try using loop record mode.

**Comment by dhcrump** [comment]
I actually want less than 15 seconds, more like 1 or 2 seconds.

**Comment by Fougl** [comment]
Hi, I would like to know what is the maximum timeout value?

**Comment by dnewman-gpsw** [comment]
No idea, but there is no upper limit.
