### ISSUE TITLE
Inconsistency in the documentation: DSPL or DISP?

### ISSUE THREAD

**Issue by pklaus** [gopro/labs#15]
At the moment, [docs/control/extensions/README.md](https://github.com/gopro/labs/blob/master/docs/control/extensions/README.md) reads:

> **DSPL**=time, this will control the amount of time messages are displayed. For users who want there own information displayed longer. The default is 1 second. **DISP**=1 thru 9 is in seconds. **DISP** = 10 thru 9999 is in milliseconds. So for much faster messages set DISP to 100. Set this before setting the owner information, as metadata commands are processed in the order they are stored.

So which is it? DSPL or DISP? From my attempts to change the settings, I'd say `DSPL` is the right one.

**Comment by dnewman-gpsw** [comment]
Thank you for pointing this out.  DSPL is correct.  I will get this fixed in the documentation.

**Comment by dnewman-gpsw** [comment]
Fixed
