### ISSUE TITLE
Question: How to check the owner info in mp4 generated?

### ISSUE THREAD

**Issue by lzl124631x** [gopro/labs#151]
In https://gopro.github.io/labs/control/owner/, it says "In addition to being displayed, it is written within each MP4 or JPG created.". How can I check this info in the mp4 generated?

I do see `MISC/GoPro-owner.txt` generated and qrlog.txt has the logs related to reading the owner info. 

I'm using Mac and I don't see the owner info when checking the info by pressing `ctrl + I` on the video file or in GoPro Player.

**Comment by dnewman-gpsw** [comment]
As this is not bug, so should be posted to https://github.com/gopro/labs/discussions

All GoPro custom metadata is stored in a GPMF format.  Sadly Apple will never read that.  Developer use https://gopro.github.io/gpmf-parser/     You can also use https://gopro.github.io/labs/control/metadata/

**Comment by fxstein** [comment]
There is a way to trick Apple into reading it by using tags. This is why I created `goprox` to process GoPro media files before they get imported into the Apple ecosystem. Have not looked at the labs owner info but am planning to do so.
https://github.com/fxstein/GoProX
