### ISSUE TITLE
Cannot see videos on Hero 10 Labs firmware 1.46.70, works on regular one

### ISSUE THREAD

**Issue by HanSooloo** [gopro/labs#161]
I noticed that I CANNOT see the videos I recorded on my Hero 10 with Labs 1.46.70 firmware version.  I can record without any issue.  I can, then, plugin the SD card in a reader connected to my computer where I can see all the files without any problems.  

I called Hero support and they recommended going back to the standard firmware, which is 1.46.00 as of this post.  When I go back to the standard firmware, I am able to view the videos on the Hero 10 again.

_Additional data points:_

1. I was able to view them before.  The only thing that is different is that I activated the "Base Name" feature, where the files are prefixed with "MAIN".  Before then, everything was fine.

1. I also noticed that I couldn't reset the base name as described in its page.  When I scan the QR code with "nothing" in the basename field, the camera continued to use the original basename.

What has changed?  Why can I not view the files on the camera when on the Labs firmware?

**Comment by KonradIT** [comment]
> The only thing that is different is that I activated the "Base Name" feature, where the files are prefixed with "MAIN". Before then, everything was fine.

That's why you can't see them in camera.

**Comment by HanSooloo** [comment]
> > The only thing that is different is that I activated the "Base Name" feature, where the files are prefixed with "MAIN". Before then, everything was fine.
> 
> 
> 
> That's why you can't see them in camera. 

Is that the expected behavior of base name feature?  Didn't think that it would make the files invisible to the camera :-)

**Comment by HanSooloo** [comment]
Checking the labs page, it states the following:

WARNING: The GoPro App and GoPro cloud services will not support these renamed files. 

So, maybe suggest modifying it to say:

WARNING: The **GoPro camera**, GoPro App and GoPro cloud services will not support these renamed files.

**Comment by dnewman-gpsw** [comment]
Keep to https://github.com/gopro/labs/discussions as we try use the issues section as a backlog of bugs to fix.  

I've updated the warning message.  Labs was working correctly.
