### ISSUE TITLE
Baffling results from Construction Time-lapses

### ISSUE THREAD

**Issue by enbytv** [gopro/labs#17]
So, I set up a test construction timelapse using the "Construction Time-lapses" function. These were the settings used on a GoPro Hero 7 Black.

![image](https://user-images.githubusercontent.com/42849093/108087772-a95c2080-706f-11eb-99cc-9731ffb37d62.png)

I made sure to set the clock correctly to UTC time. However, the camera did not take this time and date, instead reverting to 01/01/2016 00:00, and hence has taken completely random pictures at random times. See below screenshot detailing the times it took the picture.

![image](https://user-images.githubusercontent.com/42849093/108087650-8f224280-706f-11eb-931f-46b68390bb1f.png)

For example, some days it started taking pictures at "08:00" but then stopped at "08:31". On other days it started at "14:30" and took pictures until "17:07". On some days it only took one picture at all.

**Comment by dnewman-gpsw** [comment]
Please confirm your camera's clock is working correctly, as the wake timer depends on it.  Reset you date/time and run the experiment again.   Next time send the MISC/qrlog.txt file if there is a failure.

**Comment by enbytv** [comment]
> Please confirm your camera's clock is working correctly, as the wake timer depends on it. Reset you date/time and run the experiment again. Next time send the MISC/qrlog.txt file if there is a failure.

Yeah, I did reset it both before and after this. Had another failure but there was no MISC/qrlog.txt file. Have got it working properly but had to reinstall both the GoPro and GoPro Labs firmware before it ran successfully.

**Comment by enbytv** [comment]
Another failure on my HERO7 Black. It is not working properly, and the MISC/qrlog.txt file only contains the last few days of results. However, the qrlog.txt which I have attached does capture the fact that it took zero pictures on 2021-04-20 despite being on a daily trigger.

[qrlog.txt](https://github.com/gopro/labs/files/6352181/qrlog.txt)

![image](https://user-images.githubusercontent.com/42849093/115582225-a4f6f280-a2c0-11eb-96f2-0d4e74e49f18.png)

**Comment by dnewman-gpsw** [comment]
It seems that the wake alarm is less accurate than I have see.  

This was a successful day start, where the camera wakes just before the required time:
[2021-04-21 07:49:20 0% 15c] Woke with Command:[08:00:00]!S!1R
[2021-04-21 07:49:26 0% 17c] Shutdown and Sleep:580 seconds
[2021-04-21 07:59:33 100% 16c] QRShouldIWake:02
[2021-04-21 07:59:33 100% 16c] Woke with Alarm:[08:00:00]!S!1R
[2021-04-21 **07:59:34** 0% 16c] Woke with Command:[08:00:00]!S!1R
[2021-04-21 07:59:34 0% 16c] Start in:**26 seconds**
[2021-04-21 08:00:01 0% 20c] Timer wake command:!S!1R
[2021-04-21 08:00:08 0% 20c] true 08:00 > 07:59:>07:59<17:00!525SQ~!08:00S!1R
[2021-04-21 08:00:08 0% 20c] true 08:00 < 17:00:<17:00!525SQ~!08:00S!1R
[2021-04-21 08:00:12 0% 20c] Shutdown and Sleep:525 seconds

This was a bad day start, woke after the required start:
[2021-04-20 07:06:13 100% 11c] Woke with Alarm:[08:00:00]!S!1R
[2021-04-20 07:06:14 0% 11c] Woke with Command:[08:00:00]!S!1R
[2021-04-20 07:06:20 0% 13c] Shutdown and Sleep:3106 seconds
[2021-04-20 **08:00:35** 100% 15c] QRShouldIWake:02
[2021-04-20 08:00:35 100% 15c] Woke with Alarm:[08:00:00]!S!1R
[2021-04-20 08:00:36 0% 15c] Woke with Command:[08:00:00]!S!1R
[2021-04-20 08:00:42 0% 17c] Shutdown and Sleep:24000 seconds

7:06:20 + 3106 seconds,  which set the wake for 7:58:06, yet the camera woke at 08:00:35, so it fails the before 8am test.

The wake timer is never precise, but this a larger variation then I've seen.

Something to try:  >07:59<17:00!525SQ~!08:00SQ!1R

Add the Q to !08:00SQ reduced the timing requires to be so exact.

**Comment by enbytv** [comment]
Interesting. Thanks, I'll tweak this and see if it improves!

**Comment by mforss920** [comment]
My hero 7 went for 2 days then locked up with all red lights on...

**Comment by RonaldoQ79** [comment]
My Hero10 is giving me similar problems, It seems to successfully take photos for around 4 days and then just stops. Plenty of battery power left too.

**Comment by solipsia** [comment]
I have the same issue on my Hero 9 Black. The timelapse works perfectly for around 5-10 days and then just stops with the camera staying on. I then need to rescan the QR code to get it to resume.

**Comment by RonaldoQ79** [comment]
I have set the internal clock to 24hr and it seems to be running fine now. Maybe being set to AM/PM was causing a conflict as the timeslapse I had set was from 0800 - 1700.

**Comment by jo196605** [comment]
> 

Hello Ronaldo, I think you've found the solution. I had 4 hero's 09 running construction timelapses and only one who was set to 24h stayed working. They are all now on 24h, I hope my problem is fixed. Thanks a lot!
