### ISSUE TITLE
qr code Start/stop delay

### ISSUE THREAD

**Issue by MelliCain** [gopro/labs#18]
Hello,

I'm trying to do a usb power trigger with qr code. But when power is on, video recording starts after 10 seconds. How can we reduce this delay?

**Comment by dnewman-gpsw** [comment]
What command are you using? The exact QR text please.

**Comment by dnewman-gpsw** [comment]
If you are using the default: !uN!S!u10E!R  It is about as fast is it will go.

This might be slightly faster: !uS!u10E!R

It is not fast.

**Comment by MelliCain** [comment]
I m using defult qr code (!uN!S!uE) 

I'll write the results after trying

**Comment by MelliCain** [comment]
Nothing has changed. Video recording starts 10 seconds after connecting USB.

**Comment by MelliCain** [comment]
> If you are using the default: !uN!S!u10E!R It is about as fast is it will go.
> 
> This might be slightly faster: !uS!u10E!R
> 
> It is not fast.

Nothing has changed. Video recording starts 10 seconds after connecting USB.
