### ISSUE TITLE
Feature Request: QR Code readout protection? 

### ISSUE THREAD

**Issue by damirissimo** [gopro/labs#181]
Hey there,

First of all, Labs is amazing! Thank you, everyone, for your hard work.

I have a suggestion in regards to camera and the security of it's settings. Labs QR Code readout is instant and works as intended. In the same time, this brings up a potential malicious attack which may shut down your GoPro by showing specific QR Code to it or scramble up its settings. Though not many know about Labs capabilities and even if one's GoPro has Labs firmware installed, still, it's an option. 

Would it be possible to protect GoPro from reading non-authorized QR Codes? For example, owner could set up "secret phrase/code" in GoPro settings, and specify this phrase in QR Code command. Or one could use it's own GoPro Serial Number or some other ID which is written inside gopro memory already.

**Comment by KonradIT** [comment]
Use `HNDL`. 

Eg: `HNDL=2`

Then QR codes need to begin with `h2`. (Eg: `h2fN` to set Lens to narrow)

**Comment by damirissimo** [comment]
Hey @KonradIT,

This sound like solution! Sorry, seems like i missed it when reading the docs. I guess 1-31 numbers should be enough for basic readout protection :)
