### ISSUE TITLE
Invalid, QRControl app, Android: Mixed up in places "LOGB" and "LOGO"

### ISSUE THREAD

**Issue by EIIIE** [gopro/labs#189]
The functions "LOGB" and "LOGO", their parameters and descriptions are mixed up in places. Attention to the screenshots: 
![LOGO](https://user-images.githubusercontent.com/13149979/211941372-ebd1541d-e38e-4ae4-832f-3cb618032f28.png)
![LOGB](https://user-images.githubusercontent.com/13149979/211941377-f889e818-6e1d-44d0-813f-3820fc5a5911.jpg)

P.S. I apologize if no one here is associated with the QRControl application and I made a mistake with the place of publication.

**Comment by dnewman-gpsw** [comment]
Fix in the next QRControl release
