### ISSUE TITLE
e2 and e3 codes won't change the current setting for EIS / Hypersmooth 

### ISSUE THREAD

**Issue by corentin-larose** [gopro/labs#19]
- on a GOPRO HERO 8 BLACK with GOPRO LABS firmware 02.50.71:
- generating a QR code from generator:

Off: mVr1080p25fWe0 => works
On: mVr1080p25fWe1=> works
High: mVr1080p25fWe2 => doesn't change the current setting
Boost: mVr1080p25fWe3 => doesn't change the current setting

Despite the fact it has been said that the software was "clever" enough to make the distinction, this is most likely because EIS/Hypesmooth and Night Photo exposure time settings share the same code "e2" and "e3".

**Comment by dnewman-gpsw** [comment]
I can confirm that e2 and e3 aren't working on HERO8, but they are working on HERO9.  It is just a simple bug, not a confusion over Night Photo.

**Comment by corentin-larose** [comment]
> I can confirm that e2 and e3 aren't working on HERO8, but they are working on HERO9. It is just a simple bug, not a confusion over Night Photo.

So this is a bug, then, I don't understand why you just closed the issue, did you already fixed it?

**Comment by dnewman-gpsw** [comment]
The camera bug was addressed, but as camera firmware is not open source, it can only be shared if or when there is QA bandwidth. Releasing new firmware will be a rare event, so far H8 has had two Labs releases 7 months apart, there can be no guarantee the HERO8 will get another Labs update. However, all bugs reported are addressed, where possible, fingers-crossed for future Labs releases on older camera models.
