### ISSUE TITLE
Bug: GoPro 11 Mini 2.00.70, There is no sound notification when the camera starts and turns off

### ISSUE THREAD

**Issue by EIIIE** [gopro/labs#190]
When the camera turns on with the mode change button (black on the front panel), there is no sound alert. Also, there is no sound notification when the camera is turned off when idle (10 seconds from turning on). If you turn on the camera with the record button (the button on top with a red circle), then an audio alert is played, when recording stops, an alert is also played and the camera turns off. The rest of the alerts work correctly (changing modes, turning off the camera by holding the button on the front panel, using QR codes).

Resetting to factory settings did not help.

**Comment by dnewman-gpsw** [comment]
This is how the normal production 2.00 firmware behaves, Labs doesn't not modify this.
