### ISSUE TITLE
Feature Request: LOGB feature on GP10

### ISSUE THREAD

**Issue by p-masek** [gopro/labs#194]
LOGB=logbase,offset  -  this is great feature as regular Flat profile can be too washed out and standard is too contrasty for lot of users. 
Could this be feature added to GoPro 10? 

Basically - feature which would add possibility to edit Flat profile (adjust contrast, saturation) as it is quite common on other cameras, that would be great.

**Comment by dnewman-gpsw** [comment]
It is not coming to HERO10, basically because of the lack of 10-bit. The flat profile is does for 8-bit, and moving too much would potentially reduce image quality.  On HERO11 the 10-bit grants more flexibility.

**Comment by p-masek** [comment]
@dnewman-gpsw I do not want to increase dynamic range beyond what current flat profile can do. My interest is opposite - adding more contrast to flat profile and move it closer to standard profile. That would help reduce amount of grading of 8bit video during postprocessing. 

And again - it would be nice if GP profiles could be tuned as per test of the user. Just take a look on DJI drones or Canon, Sony,... cameras  - even the cheapest ones let you edit contrast and saturation. Why same cannot be in GPs? Why we can edit only posharpness?

**Comment by dnewman-gpsw** [comment]
I understand, but LOGB is not good for adding contrast or saturation, it is very different control that really need 10-bit. LOGB is not for tailoring an in-camera look, rather for pushing dynamic range for enhanced post and color correction.  Now a contrast and saturation control might be a good idea, I will think about if that can be done.

**Comment by p-masek** [comment]
@dnewman-gpsw thank you for clarification regarding LOGB.
Adjusting flat profile would be great, I hope you will find the way how it could be done (to GP10 as well 😉)...
