### ISSUE TITLE
Problem with Construction timelapse

### ISSUE THREAD

**Issue by iainballantyne-pixel** [gopro/labs#214]
### Discussed in https://github.com/gopro/labs/discussions/212

<div type='discussions-op-text'>

<sup>Originally posted by **iainballantyne-pixel** January 28, 2023</sup>
Hi, I bought a GoPro 11 to use as a time lapse for our new house extension. I'm new to all this, so please bear with me. I've downloaded the QR firmware which allows the GoPro to scan the QR codes on here. I've then used the construction time lapse ready made QR code on here (after using the QR code to set the time). The QR code scans and I get a message stating the time the images will start and the camera powers off. If I leave the camera, at the correct time, it seems to power up and appears to take an image, it then powers down again and repeatedly does this for the set duration.

However, at the end of the duration, if I look on the media section (swipe up on the screen) there are no images/videos. If I take the SD card out and look at it, there are no files at all on the memory card.

Construction starts on Monday, any help would be appreciated, I've been struggling with this for 2 weeks now! 

Thanks in advance.

Iain</div>

**Comment by dnewman-gpsw** [comment]
Addressed in the discussion threads
