### ISSUE TITLE
Session 5 Issues

### ISSUE THREAD

**Issue by HiStephenT** [gopro/labs#22]
Hi, there appears to be several issues with the current session 5 implementations, cannon select 90fps, whilst attempting to setup a time lapse (Photo) it freezes the camera. When looking at the Quik app, the resolution is unknown. After a reset of the camera and switching modes it’s restored. Video timelase is also a bit problematic due to missing camera specific settings.

**Comment by dnewman-gpsw** [comment]
Session 5 support via QR Codes is very limited.  The latest Quik app should be a better option.
