### ISSUE TITLE
Question relating to motion trigger.

### ISSUE THREAD

**Issue by henri** [gopro/labs#24]
Is it possibly to have a timed start (eg 10 seconds) and have a gyro/accelerometer to to end the recoding. It seems the stop recording when there is no motion is only possibly at the moment when the recording is also started by the gyro/accelerometer.

If I have missed something simple please let me know. Being able to start on a time and then stop on no motion after specific number of seconds would be great if possible.

**Comment by dnewman-gpsw** [comment]
The two features can't be combined.  Good idea though.

**Comment by henri** [comment]
Thanks for the update. Maybe in a future version? I am glad it is not a bug!

**Comment by dnewman-gpsw** [comment]
Maybe future, it is not a simple change.  And explaining this to users will be tricky. :)
