### ISSUE TITLE
Feature Request: Fine grained min/max ISO control

### ISSUE THREAD

**Issue by andrerav** [gopro/labs#241]
Pun intended, of course :) If it's possible, then more control over the minimum and maximum ISO would be very nice. Currently the ISO settings are limited to the values 100, 200, 400, 800, 1600, 3200 and 6400. Especially in the mid-high ISO range, being able to set an arbitrary maximum ISO value could be beneficial. Sometimes 800 is too little and 1600 is too much, and I find myself pining for something in between :)

**Comment by andrerav** [comment]
Ah I see, that makes sense. I suppose the quality difference between the camera adding digital gain before encoding compared to me doing it in post would be negligible/placebo?

**Comment by dnewman-gpsw** [comment]
Correct, with the higher bitrate, reduced denoise, it is the same doing it in post.

**Comment by andrerav** [comment]
Great, thanks for the excellent info! :)
