### ISSUE TITLE
[bug] USB power trigger does not persist

### ISSUE THREAD

**Issue by salarmehr** [gopro/labs#269]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/2582036/226152534-3a7a7268-2253-4b22-8752-0bf27ca9f2eb.png">

Using the above code, I activated the USB power trigger to use the camera like a dashcam. It works until I turn on the camera with the power button or if I switch it off with the power button or capture anything manually. The trigger does not work anymore until I scan the code again. 

This means that I cannot use the camera to capture something and put it back on the car to be used like a dashcam and I have to scan the QR code again and again. 

I hope in the future you can simply add a new mode next to slow motion mode, to use the camera like a dash cam with a cute car icon!

**Comment by dnewman-gpsw** [comment]
That example works as designed, 3 years ago. So not a bug.  If you want a more modern way you need to use the WAKE and BOOT commands. see https://gopro.github.io/labs/control/extensions/ This way you can either manually or automatically boot the camera, and have it perform any action you want.  In the latest HERO11 Labs firmware, you can do even more to customize a dashcam mode, using Timewarp when the car is not in motion, or really any combination of camera features you can imagine.
