### ISSUE TITLE
website bug?

### ISSUE THREAD

**Issue by mllorenteisidro** [gopro/labs#27]
On the website [Full List the Settings Commands](https://gopro.github.io/labs/control/settings) under "Some further option ('o') commands", you can read: 

> Screen Auto Off - oS - Never, oC1 - 1min … oC3 - 3min

NOTE the "C"

I am assuming it should be:
> Screen Auto Off - oS - Never, oS1 - 1min … oS3 - 3min

NOTE the "S"

**Comment by dnewman-gpsw** [comment]
Thanks, now fixed.
