### ISSUE TITLE
dyld: Library not loaded...

### ISSUE THREAD

**Issue by Verohomie** [gopro/labs#28]
So close to getting this to work... anyone seen this?

> `b-rad@Brads-MacBook-Pro Desktop % udtacopy merge-GX0x0483.MP4 final.mp4
> dyld: Library not loaded: @rpath/libclang_rt.asan_osx_dynamic.dylib
>   Referenced from: /usr/local/bin/udtacopy
>   Reason: image not found
> zsh: abort      udtacopy merge-GX0x0483.MP4 final.mp4`

I suspect my issues are permission or path based? Got it to work on windows! But my MBP is my edit platform.

**Comment by rubegartor** [comment]
I could solve it in the following way:
`otool -L udtacopy`
This returns a list of libraries, one of them begins with: @rpath/...
Now, search for thath library in your system:
`mdfind libclang_rt.asan_osx_dynamic.dylib`
This returns a list of routes where matches were found for that specific library, copies the full path with the most current version of the library, and now replace it here:
`install_name_tool -change @rpath/libclang_rt.asan_osx_dynamic.dylib [your lib path] udtacopy`

All this executed from the directory containing udtacopy.

Example: 

![Example img](https://i.imgur.com/1m6a6qX.png)

Hope this helps, this worked for me in Macbook Air 2020 M1.

**Comment by Verohomie** [comment]
WOW... not sure what/how this works BUT... THANKS!!! Running RSG on merged footy :)
