### ISSUE TITLE
GoPro 11 Labs firmware link

### ISSUE THREAD

**Issue by CyberoniOntoni** [gopro/labs#280]
It’s wrong. Gives 404

**Comment by CyberoniOntoni** [comment]
Link in README leads to https://gopro.github.io/labs/firmware/bin/LABS_HERO11_02_10_70.zip

**Comment by CyberoniOntoni** [comment]
> Which link does?
> 
> The one I shared here doesn't #265

Thanks!

**Comment by dnewman-gpsw** [comment]
Where are you getting that older link from?  Might be a page I missed.
