### ISSUE TITLE
Feature Request: Clean HDMI out with Media Mod

### ISSUE THREAD

**Issue by vwvierhundertzwoelf** [gopro/labs#30]
We have a few HERO 9s with Media mod and want to use them in an live streaming environment.
I wish it could be possible to go directly to clean hdmi when plugging the hdmi into the Media Mod.
It is really annoying to go leave the menu and disable the overlay every time you replug the cable.

Thank You

**Comment by rmoriz** [comment]
For GoPro 9 and 10 with labs firmware, there is a QR code that enables clean HDMI via Media Mod  - look for "HDMI" on https://gopro.github.io/labs/control/extensions/ 
Maybe you can combine it with the ["USB Power" trigger](https://gopro.github.io/labs/control/usb/) and ["Scripting" ](https://gopro.github.io/labs/control/actions/#scripting)

Sadly, my GoPro 8 is not supported anymore. I'd love to have a clean HDMI command, too :'(

**Comment by marksteven** [comment]
This does not seem to work so hoping someone can point me in right direction
Eg getting clean HDMI out on Gopro9
have used this page 
https://gopro.github.io/labs/control/extensions/
to add HDMI=1
to first line Metadata Four CC
I get a brief error saying "Must be in four characters long"
yet documentation says HDMI=1 which is 6

As far as I can tell reading a bunch of pages this is the correct format to get a clean HDMI out using Mod without having to go through 2 button click to "eye" etc
I also tried HDMI1 , hdmi=1, hdmi1 !
Nowhere can I find and example of what the code if it is 4 characters long should look like.
Hoping some one can help.
Thanks
Also QR does not work at all if HDMI cable is attached
