### ISSUE TITLE
how to control the gopro hero10 live streaming by the ble command?

### ISSUE THREAD

**Issue by zsinba** [gopro/labs#31]
Hi，dear,
Live streaming by the QR code is so cool. but what should I do if I want to live steaming by the BLE control with my app?
I got the OpenGopro SDK,It could control some commands by the BLE, but it can't control the connection to the SSID and start the live action. 
Could you tell me how to control it by the ble command?

**Comment by dnewman-gpsw** [comment]
That is question for Open GoPro team, as it is not in the Labs scope.
