### ISSUE TITLE
GoPro as dashcam : Issue on Motion detection trigger in a scheduled interval

### ISSUE THREAD

**Issue by esiremalaysia** [gopro/labs#323]
related to discussion #322 

### Use case :
Trying to use my gopro as a dashcam while a motion detection occurs in a specific scheduled interval using 'boot' command. Note that the gopro is continuously powered by a powerbank and cooled with a fan (in case of hot weather).

### Labs documentation :
I find the actual documentation for 'boot' command here (https://gopro.github.io/labs/control/extensions/), is says  : e.g. !10:00NoMBOOT=”!SM3D4H5!R” <- Wake at 10am, then motion capture continuously. But the instructions does not work on the hero10 (also tried on the hero8 and do not work neither). 

### Troubleshooting :
Here, the command I was troubleshooting with : 

**CASE 1** - Start Motion Detection continuously: !SM4H2!R (✅ working)
**CASE 2** - Start Motion Detection + Hindsight (15s window) continuously: mVhS1!SM4H2hS0!R (✅ working and already solved #187)
**CASE 3** - Start Motion Detection continuously on a scheduled time at 8:00 AM : !08:00NoMBOOT="!SM4H2!R" or !08:00NoMBOOT=!SM4H2!R (❌ failed) -> boot at scheduled time OK, but the motion detection FAILED with message error*
**CASE 4** - Start Motion Detection continuously on a scheduled time at 8:00 AM + Hindsight: !08:00NoMBOOT="mVhS1!SM4H2hS0!R" (❌ failed) -> boot at scheduled time OK, Hindsight OK, but the motion detection FAILED with message error*
**CASE 5** - Boot + Motion detection + Adding an SD card based boot file (base on this example : https://gopro.github.io/labs/control/imutrigger/)  : !MQRDR=1!08:00N!MBOOT="!Lmotion"!SAVEmotion=!SM4H2!R (❌ failed) -> same error from case 3 + but when restarting manually the gopro the motion detection begin without taking into account the time scheduled condition
**CASE 6** - Start Motion Detection continuously on a scheduled time at 8:00 AM and stop it at 20:00 AM : help❓
**CASE 7 (final)** - All the above (motion + hindsight + start/stop schedule ) + upload on the cloud : help❓

### Issue (MAIN) :
*Message error each time using 'boot' command:  "CANCEL MOTION TRIGGER"
![gopro_motion_issue](https://user-images.githubusercontent.com/42617463/234718052-2ebd90cb-b473-494c-9c67-a64e805f9ab1.jpeg)

It is kinda frustrating to see that every single step can work separately on the hero10 and hero8 but when we combine with boot commands everything failed.

### Issue (SECONDARY) : 
I want the rear LCD screen to be turned OFF on hero10 while processing the script above because it :
- drains too much battery for nothing
- waste of resources
- heats the gopro 
- that's not unobtrusive (especially if used in a car at night/bad weather)

I saw the issue here #77, but unfortunately technical support @dnewman-gpsw says that's not possible due to the architectural difference. I feel really sad that it works on previous models hero8, hero9 and newer model hero11 but not on hero10. Feel a little scammed on that issue because as a gopro customer and a developer every working feature from previous model must be included on newer model, especially with cameras industry. It might be a solution, if you can reopen that issue I will highly appreciate. 

### Logs (for case 4) :
```
[2023-04-26 18:41:08] Labs:Main Start 
[2023-04-26 18:41:08] Labs:Initialize 
[2023-04-26 18:42:48] Read QR:!18:44NQv1oMBOOT="mVhS1!SM4H2hS0!R" 
[2023-04-26 18:42:52] Shutdown and Sleep:66 seconds 
[2023-04-26 18:42:53] shutdown:rtc wake scheduled 
[2023-04-26 18:44:01] Woke with Alarm:[18:44m01]!NQv1oMBOOT="mVhS1!SM4H2hS0!R" 
[2023-04-26 18:44:01] Labs:Main Start 
[2023-04-26 18:44:01] Labs:Initialize 
[2023-04-26 18:44:04] Woke with Command:[18:44m01]!NQv1oMBOOT="mVhS1!SM4H2hS0!R" 
[2023-04-26 18:44:04] Start Now:Past by 4 seconds 
[2023-04-26 18:44:04] Countdown:complete 
[2023-04-26 18:44:04] Timer wake command:!NQv1oMBOOT="mVhS1!SM4H2hS0!R" 
[2023-04-26 18:44:04] Labs:QR Detection Waking 
[2023-04-26 18:44:04] Labs:QR Detection Ready 
[2023-04-26 18:44:07] Boot command:mVhS1!SM4H2hS0!R 
[2023-04-26 18:44:07] Command order:mVhS0hS1!SM4H2hS0!R 

```
_Running on GoPro Hero 10, Firmware 01.50.70_

### Goal :
My goal is at least to find a solution to make **CASE 3** functional as written in the documentation which is my biggest concern.

I take time to meticulously point the issue and improve gopro labs features, and expect a solution from it. Thanks in advance for the support.

**Comment by dnewman-gpsw** [comment]
duplicate
