### ISSUE TITLE
Bluetooth Timecode sync

### ISSUE THREAD

**Issue by DigitalMetal** [gopro/labs#33]
Please would you consider allowing Timecode sync from a bluetooth TC generator such as the ATOMOS Ultrasync blue, this could be another useful way of timecode syncing multiple GoPro's in a professional video scenario.
Thanks
https://www.raycom.co.uk/product/timecode-systems-ultrasync-blue/

**Comment by dnewman-gpsw** [comment]
Other are using QR Code from Timecode sources to solve this issue.  Adding BLE timecode device support is currently beyond what Labs can offer.
