### ISSUE TITLE
Extra Long time-lapse (or any photo mode) not working on 11 Mini

### ISSUE THREAD

**Issue by lucaoppy** [gopro/labs#338]
Hello, by looking at the README file it seemed to me that I could have extra long time lapse on my Mini 11 using Labs firmware.

https://github.com/gopro/labs/blob/0f12ca0fcc198814ed5c3ca3ae6a96e6b26232bb/README.md?plain=1#L63

I tried v2.20.70 but it didn't switch to the mode, I also tried simple photo mode and it also did not work.

Is the readme to be corrected like this? 

| Feature                                                                                                               | HERO11/Mini | 
|-------------------------------------------------------------------------------------|----------------|
| [Extra Long time-lapse](https://gopro.github.io/labs/control/longtimelapse)  | Yes/No           |

Or is it supposed to work and maybe I'm doing something wrong?

Thank you in advance.

**Comment by dnewman-gpsw** [comment]
Thanks, fixed in the feature lists.  Of course, Mini does not have photos, so no extra long time-lapse feature.
