### ISSUE TITLE
Hero 5 Session photo timelapse mode

### ISSUE THREAD

**Issue by macvenez** [gopro/labs#362]
Hi, as you may have seen in another older post I'm having issues with Hero 5 Session when set to timelapse photo mode.
I tried using **Labs and Original firmware** but I have the same issue with both.

When I set timelapse photo mode (10MP, 60s interval, wide lens) and press the shutter button to start recording the camera just shuts off and goes in a kind of locked state where it is freezed with shut off screen and the only way to recover is to keep the mode button pressed for a while (at least 10s).
The same things happen when I start a timelapse by quickcapture (keeping the shutter button pressed for 3s when the camera is off).
The only difference now is that the top part of the screen which shows mode icon and battery status icon remain there and the other half (where you should see if it's shooting) remains black. Also there the camera freezes (this time with the top half light on) and you can only recover by keeping the mode button pressed.
I tried using at least 4 different SD cards (all of them on the list) and the issue persists.
If needed I can attach a video to explain the situation completely.
Is it possible to have an update?
Thanks!

**Comment by macvenez** [comment]
I did factory reset twice, it's working now, thanks.
Are there any info about future firmware releases for the hero 5 session? Thanks

**Comment by dnewman-gpsw** [comment]
Very unlikely, as the camera is now two system architectures old.  It was very difficult to do the Labs version 2 years ago, so harder today.

**Comment by dnewman-gpsw** [comment]
That won't happen, likely or many more reasons than I can guess at.
