### ISSUE TITLE
udtacopy usage

### ISSUE THREAD

**Issue by ramonsmits** [gopro/labs#38]
The usage of udtacopy is unclear, it states:

> ffmpeg -y -f concat -i your_path_to/filelist.txt -c copy -map 0:0 -map 0:1 -map 0:3 your_output_path/final.mp4
>
> udtacopy your_path_to/the_first_GoPro_file.MP4 your_output_path/final.mp4

Source: https://github.com/gopro/labs/tree/master/docs/control/chapters#optional-joining-chapters-after-capture

This seems to only copy the [GPMF data](https://gopro.github.io/gpmf-parser/) from the 1st file and not the others.

What exactly is done with `udtacopy` if the *gpmd* is in a separate track? How do these 2 vary? Explaining that the guidance would be helpful.

**Comment by dnewman-gpsw** [comment]
There is a small chunk of global GPMF data in the udta (user data atom in the header) of the MP4, and ffmpeg does copy that. GoPro tools require this header metadata.
