### ISSUE TITLE
!MBITR option not applied in GoPro Hero11

### ISSUE THREAD

**Issue by KangRyeon** [gopro/labs#386]
I am using 'mVr1080p24fL0e0hS0dR1800v0q0dVoV0B7D4C5S2W5L7!MBASE="[yyyy-mm-dd_HH.MM.SS]-"!MBITR=3' option.
For permanent bitrate application, the option '!MBITR=3' was used, but after rebooting, bitrate 3Mbps is maintained only until the first video, and from the second video, it is changed back to 40Mbps.

For example, like below
1) 2023-05-24_07.11.13-GX010001.MP4 : 3Mbps
2) 2023-05-24_07.41.13-GX010002.MP4 : 40Mbps
3) 2023-05-24_08.11.13-GX010003.MP4 : 40Mbps

Is this a bug? or am I missing something?
Is there a way to keep bitrate 3Mbps in all videos?

**Comment by dnewman-gpsw** [comment]
I have confirmed this is a bug.  It is only happening with lowered BITR values, which is likely why it hasn't been reported.  Looking into why now.

**Comment by KangRyeon** [comment]
What is the lowest number that I can reliably set bitrate?

**Comment by dnewman-gpsw** [comment]
It is not the number, anything lower than the standard rate is just not being reset for the next capture.  The firmware fix is straight forward, and will be included the next Labs release, which is currently still a few months off.  I haven't found a good workaround, other than restarting the camera between captures.

**Comment by KangRyeon** [comment]
Thank you for your answer!

Will this issue happen with GoPro Hero10 as well?

Also, I know the usb trigger, can I have a setup with this option to start recording after rebooting when connecting to usb?

**Comment by dnewman-gpsw** [comment]
HERO10 does not seem to have this bug, in my quick tests on two cameras.

As for the trigger question, yes? But I'm not hundred percent on what you want to do. On H11 you can do a lot with triggers and scripted.  You can combine WAKE=2 with BOOT command and USB triggers, to do a lot.

**Comment by KangRyeon** [comment]
Thank you. I will try to set the bitrate of all videos to 3Mbps using Hero10 :)
Have a great day!

Should I close this issue?

**Comment by dnewman-gpsw** [comment]
No, it is a bug still on H11

**Comment by kdev-sys** [comment]
any update?

**Comment by dnewman-gpsw** [comment]
It is fixed internally awaiting a next release opportunity. Likely weeks not months.

**Comment by dnewman-gpsw** [comment]
Firmware is in testing, but your feedback is helpful. Please try this firmware from this expiring link (July 15, 23) https://www.dropbox.com/t/NMB0UDYK5DWiFUBr  The official release might be a few weeks away.

**Comment by kdev-sys** [comment]
> Firmware is in testing, but your feedback is helpful. Please try this firmware from this expiring link (July 15, 23) https://www.dropbox.com/t/NMB0UDYK5DWiFUBr The official release might be a few weeks away.

It works flawlessly!!! Thank you!!

**Comment by VProdAustria** [comment]
Quick hint: The link to the firmware on the main project page is broken.
Leads to the old "LABS_HERO11_02_10_72.zip" which is gone / therefor a 404 is showing up.
Works if you change it manually to "https://github.com/gopro/labs/raw/master/docs/firmware/lfs/LABS_HERO11_02_12_70.zip"

**Comment by dnewman-gpsw** [comment]
Okay, now fixed. It was okay on https://gopro.github.io/labs/ which was I was seeing downloads.

**Comment by VProdAustria** [comment]
Thats great. Thx for the quick fix of the link (and the removal of the MBITR issue at lower bitrates). Its also fixing hopefully the streaming + REC at lower H265 bitrates issues I had. Identical behaviour sometimes (as described in the 1st post): Started at targeted bitrate (BITR=5 MBits in my case) and the second file + continuing were sometimes at 25 MBits again. Tests are running actually. HUGE THX for the fix!
