### ISSUE TITLE
Session 5 QR codes for protune not working

### ISSUE THREAD

**Issue by wackfpv** [gopro/labs#39]
Scanning a QR code with the Session 5 doesn't change protune settings. Trying to change sharpness from low to high, and isn't changing... Also would be nice disable spot meter with QR codes on the Session 5 too.

https://gopro.github.io/labs/control/session5/

GoPro Session 5 Firmware: V02:51:72

**Comment by dnewman-gpsw** [comment]
Try with the latest Quik App.
