### ISSUE TITLE
Front Display Errors GP11 

### ISSUE THREAD

**Issue by stpfl123** [gopro/labs#395]
when i activate !MFRNT=1!MEXPS=1 to display ISO and Shutter i get randomly front display errors on two differnet GP11 Camera.
When i not activate no errors

**Comment by dnewman-gpsw** [comment]
Pictures please.

**Comment by dnewman-gpsw** [comment]
Nothing to go on,  closing

**Comment by stpfl123** [comment]
Sorry i can send i picture now

**Comment by stpfl123** [comment]
[https://drive.google.com/file/d/13XDruqKnLxpep4uf5iQfW2uSJ0-tpOFn/view?usp=sharing, https://drive.google.com/file/d/1S7WjAhCP3gE6lL9OJrwjQPnuxeOkh9FS/view?usp=sharing, https://drive.google.com/file/d/1TLpYJ_loTnpuBGnE0FBbeL2OHnelQ049/view?usp=sharing](url)
