### ISSUE TITLE
Hero 9 Construction Timelapse

### ISSUE THREAD

**Issue by Fisherman888** [gopro/labs#40]
I am running the Construction Time-lapse on my Here 9 Black. It ran awesome throughout 2021, but with the changeover to 2022 (maybe a coincidence?), it started behaving oddly, taking 10 photos then no more; lost many weeks of progress on the site. Anyone else having issues like this?

**Comment by CarrinoAnthony** [comment]
Hey, total newbie here. just started playing with construction TL a few days ago doing some testing. it ran for 2 days and then cut out. A few hours ago I changed the internal clock on the GoPro to 24hr format thinking it might be getting confused with a 12 hr internal clock and the settings on the QR code page on 24hr time. its still running. fingers crossed this is the fix.

**Comment by mforss920** [comment]
Same 2 day prob for me  trying 24h today

**Comment by CarrinoAnthony** [comment]
varying degrees of success while I was testing. had a project start so I installed it and crossed my fingers. heading there end of this week to see if its still running. happy to report back here.

**Comment by RonaldoQ79** [comment]
Ok great thanks! I have a timelapse on going for the last few weeks and it usually cuts out after around 3/4 days. I will try the 24hr format this weekend, not sure what my clock format is set to at the moment.

**Comment by jo196605** [comment]
Same issue here with 3 hero 09's. Construction timelapse stops after  1,5 days with a full battery...

**Comment by billborsari** [comment]
Seeing a similar problem with a Hero8 and the latest labs firmware.  Did going to 24H work?  Any else find a fix?

**Comment by CarrinoAnthony** [comment]
Nope. I gave up on this idea a few months ago. It’s simply NOT a solution until it’s stable / reliable. 

Best,

Anthony
_______________________
agc
