### ISSUE TITLE
QR code not scanning

### ISSUE THREAD

**Issue by snowphoto** [gopro/labs#41]
I wrote an Apple Shortcut to generate a QR code that removes the GoPro Labs Logo overlay. On my computer the generated QR code scans fine with the GoPro and works as expected. On my iOS device the same shortcut generates a different QR code and does not scan with the GoPro. Both QR codes scan identically with the iPhone----->    !MLOGO=""
![IMG_7834](https://user-images.githubusercontent.com/59865319/157487594-d1dc4398-4d69-47ca-ab02-48667ee6f000.jpg)
Non working iOS generated QR code 

<img width="167" alt="Screen Shot 2022-03-09 at 11 07 23 AM" src="https://user-images.githubusercontent.com/59865319/157487816-3f67b105-1d5a-4498-8124-4ea681571853.png">
Working MacOS generated QR code

Any ideas?

**Comment by dnewman-gpsw** [comment]
The top image in vertically mirror flipped.  The camera will support rotated QR Codes, but not flipped ones.
