### ISSUE TITLE
Remote Does Not Work

### ISSUE THREAD

**Issue by tetrahydra** [gopro/labs#430]
Hi, the firmware works fine and I changed the file naming system, everything works fine EXCEPT for the remote.

It is connected and it can start the camera, but it says "No SD".

**Comment by dnewman-gpsw** [comment]
This not a known issue.  Remote works fine with all camera models and firmware versions that it is designed to work with.  Which camera, which firmware (camera and remote) are you trying.  Start with a factory reset to make sure.

**Comment by tetrahydra** [comment]
Hey David, it was solved by using `!RESET`

Actually Quik app on Android can't also connect when that "problem" persisted. Now both remote and Quik app can connect and control GP11.
