### ISSUE TITLE
Change local recording from 1080p60 copy to 1080p25 copy

### ISSUE THREAD

**Issue by DavidBill7** [gopro/labs#44]
I would like to stream at 720 but store a local copy at 1080p25 instead of 1080p60. Is this possible?

**Comment by dnewman-gpsw** [comment]
The local recording is at a fixed frame of either 50 or 60.   There was a bug in the live streaming page that forced 60, that has been corrected.  Recording at 1080p50, can be easily converted to 25p without any frame timing issues.

**Comment by Manouchehri** [comment]
> Recording at 1080p50, can be easily converted to 25p without any frame timing issues.

@dnewman-gpsw In situations where low light performance matters, native 30fps recordings can be preferable. Also, 1080p 30fps @ 60Mbps looks better than 1080p 60fps (with half the frames thrown away) @ 60Mbps.

**Comment by dnewman-gpsw** [comment]
Agreed, but that is not a current option.  50p has been restored.  50p or 60p are the two choices.
