### ISSUE TITLE
GPS Speed Triggers start right but never Stop

### ISSUE THREAD

**Issue by mserigo** [gopro/labs#446]
Black Hero 11,
start with 8 mph, stop with 5 mph,
Hold time on 5 seconds
Checked:
Disable auto power off
Leave LCD on (Required on HERO10)
Repeat speed triggered capture

Video recording on Full Frame, 5.3 k 60 W
with maximum zoom and 2x Slo-Mo

Recording start right, but never stops, it keep recording even if stopped for a long period

**Comment by dnewman-gpsw** [comment]
This is a bug and a simple work around.  Scan !MQRDR=1  And it will work correctly.

**Comment by dnewman-gpsw** [comment]
Now fixed in in v2.12.70 release August 10, 2023
