### ISSUE TITLE
WBLK fix for GoPro Hero 11

### ISSUE THREAD

**Issue by CyberoniOntoni** [gopro/labs#454]
### Discussed in https://github.com/gopro/labs/discussions/369

<div type='discussions-op-text'>

<sup>Originally posted by **CyberoniOntoni** May 16, 2023</sup>
I know its not a priority and probably beyond the scope of the program, but I would love to see it working as I do dive and record almost every day. It would make my life so much easier in post. Thank you!</div>

**Comment by dnewman-gpsw** [comment]
There is already and open issue on this https://github.com/gopro/labs/issues/281
