### ISSUE TITLE
Bug: Media mod line in incompatible with usb connection to desktop on GoPro Hero 11 Black

### ISSUE THREAD

**Issue by erbensley** [gopro/labs#455]
Describe the bug
When using a media mod or 3.5mm mic adapter to connect the GoPro Hero 11 to an external audio source, plugging it in to my computer via USB disables the external audio source. This prevents use of OpenGoPro to control cameras using line-in audio with the mentioned peripherals.

To Reproduce

Set up GoPro with external audio source via 3.5mm mic adapter or media mod
Capture and notice that the external audio source works
Connect gopro via USB (through the 3.5mm mic adapter or media mod USB connection) to your desktop PC
Capture via OpenGoPro and notice that the captured video has no audio.
Expected behavior
I should be able to use the OpenGoPro library to capture on a USB connected GoPro with line-in audio.

Hardware

GoProHero 11 with GoPro labs 2.10.70 firmware (latest as of this writing)
GoPro Media Mod or GoPro 3.5mm mic adapter (either)
Desktop (tested on Ubuntu 22.04)

**Comment by dnewman-gpsw** [comment]
Are there Labs features failing, this might be 100% Open GoPro and/or MediaMod bug.   Does if fail with stock firmware?

**Comment by erbensley** [comment]
It fails with stock firmware as well, but as far as I couldn't find where to submit a bug for that specifically.

**Comment by dnewman-gpsw** [comment]
I filed the internal bug report.  As this is not Labs related, I'm closing this ticket here, but it should remain open on the Open GoPro issues list.
