### ISSUE TITLE
File Corrupted when using 5.3K 50fps

### ISSUE THREAD

**Issue by tetrahydra** [gopro/labs#459]
Hello,

These are my settings

```
BITR=190
DLRV=1
NR01=1
EXPX=200
EXPS=1
WIDE=1
LOGB=400
BASE=GoPro11_[yyyy-mm-dd_HH.MM.SS]_
LEVL=1
```

Additional settings
ISO 100-400
Linear + HL

When using _QuikCapture_, some of the recorded videos were corrupted. But when turned the camera on, and then press the record button, all the videos are ok, so far.

I repeated this several times, and it happens:
1. When the camera has not been used for longer than 6 hours.
2. Subsequent QuikCapture in a quick successive press. Less than 30 seconds in between the end and start.

**Comment by dnewman-gpsw** [comment]
Likely not a bug, you are running the bitrate 90 mbs higher than the camera is tested.  Try at 170

**Comment by tetrahydra** [comment]
Will post an update once i have it tested again on Monday (July 24).

**Comment by dnewman-gpsw** [comment]
NR01=1 also increases processing demands for compression. So there no guarantee for bitrates above stock.  Low fps is easier to overclock than higher fps.

**Comment by tetrahydra** [comment]
Here comes the update. You are right, after I lowered the bitrate to 170mbps, there were no more corrupted video files.
