### ISSUE TITLE
QR Code Precision Date and Time is not precise

### ISSUE THREAD

**Issue by fpczk** [gopro/labs#46]
I have two GoPro Hero 8 Black and a GoPro Hero 10 black, all with the latest firmware. I need to synchronize their recordings, so I synchronize the cameras with my laptop's local clock using the [Precision Date and Time (Local) QR Code](https://gopro.github.io/labs/control/precisiontime/). 

To test whether the clocks are synchronous, all GoPros record a digital clock running on my laptop, (1080p, 60Hz) and the resulting mp4 files are synchronized by me by offsetting them according to their starting timecode, which is documented [here](https://github.com/gopro/gpmf-parser#gopros-mp4-structure)

> trak’ subtype ‘tmcd’, name “GoPro TCD”, starting timecode (time of day as frame since midnight)

I assumed that the cameras would be synchronized in an order of magnitude of 1/60s. But in fact, the synchronization error between the different cameras / between the cameras and the laptop is up to 1or 2 seconds. Is this to be expected? I hoped for a higher precision.

**Comment by dnewman-gpsw** [comment]
Between camera mode that can be some latency differences between reading the time and setting the RTC hardware time.  With the same camera model that will be in sync with each other.  There have been significant improvements on HERO10 so the timecode is very close, within 20ms now (1 frame at 50/60p.)  You can even calibrate the HERO10 with the new TCAL control (see https://gopro.github.io/labs/control/extensions/ ) for fairly reliable frame accuracy (at least at 24/30p in my testing.)  To calibrate between a HERO8 and HERO10, you will need a new Precision Time page for HERO8, just add the offset you are experiencing.

**Comment by fpczk** [comment]
Thank you.

> With the same camera model that will be in sync with each other.

So the offset is more or less constant for a given camera model? If so, then theoretically it could be taken into account right away by the firmware when setting the hardware time, the developers would just need to add/subtract a constant number and the problem would be solved?

>  You can even calibrate the HERO10 with the new TCAL control (see https://gopro.github.io/labs/control/extensions/ ) 

I'll definitely have a look at the TCAL control. It's not clear from the page, but I assume the value that it takes is the offset I experience?

**Comment by dnewman-gpsw** [comment]
Yes, there is a slight difference between camera models, maybe video modes (unconfirmed.)  In older firmware, they was a bug in which the RTC time setting happened after the QR Code scan acknowledgement, adding a half second error. Fixed in HERO10.  If HERO9 or 8 get future updates that will likely get this fix.
