### ISSUE TITLE
Android Beta 1.7.4 not working

### ISSUE THREAD

**Issue by xiphiasphotography** [gopro/labs#48]
Been using the app successfully now and then. I just wanted to make some QR codes ahead of time for this weekend but when I open the App I see the startup logo and then just a white screen and nothing happens.

One UI 2.5
Android 10
Kernel 4.9.118-22750344
QRControl 1.7.4 (4-20-2022)

Please advise

**Comment by dnewman-gpsw** [comment]
Erase the apps storage and caches (both), and it will start fresh and work correctly. If that doesn’t help, contact the developer at qrcontrol@miscdata.com.
