### ISSUE TITLE
Hero 10 Timecode Video Overlay support?

### ISSUE THREAD

**Issue by chrisgervang** [gopro/labs#49]
In the [docs](https://gopro.github.io/labs/control/overlays/) I see compatibility for Hero 8,9,Max. Is Hero 10 supported as well?

Would love to use the time precision improvements discussed in #46

**Comment by dnewman-gpsw** [comment]
HERO10 is way more complicated for supporting overlays, there is limited support coming soon (likely next week,) but not in the premium video resolution and frame rate modes (4K at 30fps is maximum.)

**Comment by hefushuai** [comment]
Have you solved your problem
