### ISSUE TITLE
Duration capture not working on 11 Mini

### ISSUE THREAD

**Issue by mackyfranklin** [gopro/labs#493]
Duration Capture (dR15, dR60, dR300, etc) doesn't work on the Hero 11 Mini. 
I wrote a custom script that allows me to do this (see below for anyone else looking for a temporary solution) but would love if I could simply load it using the dR codes along with my other settings instead of having to do it as a separate code.
`Temporary solution: !MQRDR=1!MBOOT="!LfiveMin"!SAVEfiveMin==A0=X0<r0=At:B>r0=Xt:B+=X-A>X300!E!R`

**Comment by dnewman-gpsw** [comment]
Duration Capture is not a feature on Mini, so those dR commands have nothing to control in that camera.  Happy to see you have found a workaround.
