### ISSUE TITLE
Hero 5 session Construction Timelapse issue

### ISSUE THREAD

**Issue by dukevideo** [gopro/labs#50]
Hello,  
I recently updated my go pro hero session 5 with the Go Pro labs software and created a QR code to my required settings (9am-9pm and 50 photos/day) using this page: 

https://gopro.github.io/labs/control/construction/

The scan of the QR code worked ok the first time and the camera the turned off and a short while later turned itself back on to start taking the first set of photos for my timelapse.  However, instead of taking just a few photos it starts taking hundreds of photos and beeping several times and the only way to stop it is to turn the camera off.  Has anyone else had this problem? I looked on the SD card and there were over 400 photos on there which is obviously wrong when my QR setting is for 50 a day! I did set the date and time using the go pro app before scanning the QR code so I am not sure what I'm doing wrong?

**Comment by dnewman-gpsw** [comment]
H5S support for Labs is very limited, but this is one function it can somewhat do.  The camera should have made a MISC/qrlog.txt file, from that you may be able to determine what went wrong.
