### ISSUE TITLE
QR codes from Lab for Hero 7 change Language to chinese

### ISSUE THREAD

**Issue by ulph0** [gopro/labs#51]
Hi, today i installed LABS_HERO7_01.90.71. every time i use a qr code generated by https://gopro.github.io/labs/control/custom/ the language of my gopro is set to chinese, what i of course can't read, please help.

**Comment by ulph0** [comment]
hi, is this an active repository? i checked it out again; the qr generator on https://gopro.github.io/labs/control/custom/ doesn't work correctly when setting the language. changing the "voice language" changes the display language, but the display/font language setting is missing. when i switch to german there, i'll get chinese a chinese font on my display. if i switch to french, i get german. it would be nice if you could correct that.

**Comment by ulph0** [comment]
ps: could you also please express the shutter speed in 1/s instead of grade?

**Comment by ulph0** [comment]
also, setting of shutter speed seems to not work.

**Comment by dnewman-gpsw** [comment]
The voice and display language error was fixed on later cameras/firmware.  Shutter speed control does work, but not it is you set ISO Min (just leave that at 100.)
