### ISSUE TITLE
No HyperSmooth stabilization settings with the QRcode 

### ISSUE THREAD

**Issue by TimotheeGEOSAT** [gopro/labs#52]
Hi,
When i set some EIS settings like HS High on the appli and then scan the QRCore with the GoPro Hero 9, all the settings are well set except the EIS settings.
Did anyone have trouble like this ? Some idea?

Thank you.

**Comment by dnewman-gpsw** [comment]
Can you share the QR Code command you are using and which version of Labs firmware?
