### ISSUE TITLE
USB POWER TRIGGER not working on Hero 11

### ISSUE THREAD

**Issue by dnewman-gpsw** [gopro/labs#523]
### Discussed in https://github.com/gopro/labs/discussions/521

<div type='discussions-op-text'>

<sup>Originally posted by **ryantrax** September 10, 2023</sup>
I'm trying to get USB POWER TRIGGER to work on the Hero 11 Black. It works fine on my Hero 9 and 10, I just can't get it to work on the 11. I scan the QR it says it's accepted and powers down, I add USB power and it doesn't power on and start recording. I'm using command !uN!S!u10E!R just like on my Hero 9 and 10. 
Is this a known issue with the last update? </div>

**Comment by dnewman-gpsw** [comment]
This is new bug/regression.  The USB trigger is very old Labs hack, and may need some updates.  There is a workaround

Use:
!MWAKE=2 <- the camera will boot on power.  Set once.

This will then work with your list script.

**Comment by Lin-Admin** [comment]
Same problem with my Gopro 12 black.

Additional questions:
a) How can I create a QR Code for _"!MWAKE=2"_ 
b) How can I manually enter such commands?
Thx!

**Comment by dnewman-gpsw** [comment]
These are no longer bugs. 

Lin-Admin, Use any QR Code generator.  Or use QRControl mobile app or use https://gopro.github.io/labs/control/custom/

**Comment by Lin-Admin** [comment]
I have now found out that I can edit the file /MISC/bt.
However when entering _MWAKE=2!mV!R_
it starts when USB power is connected, but unfortunately no recording found in /DCIM folder?

How is the correct command to start and force video recording into /DCIM/ ??

**Comment by Lin-Admin** [comment]
I have now found out that I can edit the files _qr.bin_ and _bt_ and put the commands like _MWAKE=2!mV!R_ in both files.
This makes the cam start when USB power is connected.

**However I still could not find a command which switches the cam off when USB power is disconnected and battery is still inserted.**

Any hints are highly appreciated!

**Comment by dnewman-gpsw** [comment]
Do not manually edit qr.bin, this is not work reliably.  Also !MWAKE=2 should never be in a boot command, that is a set once event.  

I don't understand why you feel the need to do use a QR Code generator. 

I worry if give you details on the more different stuff, without the learn the easy tools, you will brick your camera.

All this can be done with: https://gopro.github.io/labs/build/ but you will need to understand coding principles.
