### ISSUE TITLE
Gopro gives "Not enough power" warning if started with MWAKE

### ISSUE THREAD

**Issue by AlexanderHackl** [gopro/labs#528]
Hi,

everytime I start the GoPro Hero 10 on power on using the MWAKE command. I get the not enough power warning and the GoPro shuts down.

However if I the manually start the GoPro by pressing the Power Button it will work. The GoPro is connected to a 5V / 3A power supply using a USB 3 / quickcharge cable.

**Comment by dnewman-gpsw** [comment]
Use !MTUSB=1 to fix power supplies that are not reporting their capacities.
