### ISSUE TITLE
Hero 5 Session / Cannot use Timelapse mode using cam only

### ISSUE THREAD

**Issue by xbug42** [gopro/labs#53]
I'm running the 2.51.72 Lab firmware on my Hero 5 Session.

-  Using the camera buttons, I choose the Timelapse mode in the menu
-  The Timelapse icon is displayed after 1 second
-  I press the shutter button which have the effect of switching off the camera
-  I press the shutter button then the camera record in Video mode !

If I enter the menu again

- the video icon is displayed (strange, maybe related to this issue ?)
- then the "GoPro Labs beta firmware" banner text is displayed
- then the timelapse icon is displayed

After having reset the camera to factory settings, the issue is still here. 

When the camera is controlled by my phone, the Timelapse mode is working...

The camera seems to be locked in Video mode when I'm only using the camera buttons...

**Comment by dnewman-gpsw** [comment]
Labs is not well supported on H5S.  You might want to restore stock firmware for full timelapse support.

**Comment by xbug42** [comment]
Ok... Maybe this should be a good idea to clearly state on the main lab page that the H5S is not well supported... Or even better to improve the H5S support !

I reverted to the stock firmware and then I had another problem : the camera is only doing timelapse when pressing the record button, whatever the previously selected mode is !!! 

It looks like the lab firmware screwed something in the persistent memory... 
Reset to factory settings did not help...

Any idea ?

**Comment by xbug42** [comment]
Ok... Maybe this should be a good idea to clearly state on the main lab page that the H5S is not well supported... Or even better to improve the H5S support !

I reverted to the stock firmware and then I had another problem : the camera is only doing timelapse when pressing the record button, whatever the previously selected mode is !!! 

It looks like the lab firmware screwed something in the persistent memory... 
Reset to factory settings did not help...

Any idea ?

**Comment by macvenez** [comment]
Hi, I experienced the same thing today, I discovered the Hero 5 Session is way more buggy than I already know...
I hope (quite impossible) they can sort out those problems for the 5 session and kinda the latest update with patches for it...
One other option is to release the firmware as an open source project and let the community figure out bugs by themselves (it's an old camera and it doesn't implement any newer features)
I hope someone reads this and finds a way to solve those issues

**Comment by xbug42** [comment]
This issue was closed as "completed" although nothing was done, not even mentioning in the readme that this lab firmware will screw your Hero 5 Session...  
Now I cannot do timelapse anymore using the camera buttons with the stock firmware... Thank you very much Gopro... :(

**Comment by macvenez** [comment]
> This issue was closed as "completed" although nothing was done, not even mentioning in the readme that this lab firmware will screw your Hero 5 Session...  
> Now I cannot do timelapse anymore using the camera buttons with the stock firmware... Thank you very much Gopro... :(
> 
> 

I opened a new issue on the topic, that's quite embarassing considering that Hero 5 Session is still widely used (and that's why they included it in the GoPro Labs update I assume).
Another main issue is the battery drain which as long as I've read it's affecting lots of users

**Comment by xbug42** [comment]
@dnewman-gpsw here is a summary to reproduce the issue in my side : 

In lab firmware :
- Open "Camera settings"
- Select TL-VD 
- Exit menu
- Short press on REC button
- Video record is started (instead of timeline) 

In stock firmware (after downgrading from lab firmware) :
- Reset to factory settings 
- Open "Camera settings"
- Select VIDEO
- Exit menu
- Short press on REC button
- Timeline record is started (instead of video)

Please tell me if you can reproduce in your side...

**Comment by dnewman-gpsw** [comment]
Labs code doesn't change these behaviors, however if Labs was build against new (older) code, that might explain.  However, long press get me time-lapses of both versions.  Seems to work fine.

**Comment by xbug42** [comment]
I'm sorry but it's not working fine !

Long press is not an option because it's bundled with Photos (and I suspect I would have the same issues with Photos if I link Long Press with Timelapse).

To be clear : for me the main problem is not that lab is broken, I understand it's experimental and not tested as a stock firmware. No for me the real issue is that after having installed lab firmware (and factory reset) , the stock firmware is not working as it was before...

I currently have lab firmware installed because I cannot take videos with the stock firmware ! Shooting videos is the main point of getting a gopro right ? But now it's not working anymore with stock firmware...

**Comment by xbug42** [comment]
@dnewman-gpsw were you able to reproduce the problem with the procedure described [here](#issuecomment-1551934190) ?
