### ISSUE TITLE
Gopro hero 11 not reading QR Code

### ISSUE THREAD

**Issue by Cenzo848** [gopro/labs#530]
Since updating my hero 11 black to v 2.12_70 in August my gopro will not read any QR code whether it is done through Quik or on https://gopro.github.io/labs/control/motion/

This means I can no longer set up motion detection.

**Comment by dnewman-gpsw** [comment]
On the camera in the menu check way version you have install on your About screen.  Swipe down -> swipe right -> Preferences -> About -> Camera Info

I don't think you have Labs installed.

**Comment by Cenzo848** [comment]
Thank you for the response, it was working before the update to version 2.12

**Comment by dnewman-gpsw** [comment]
2.12 is not Labs.  Only 2.12.70.  You can install Labs from https://gopro.github.io/labs/   Labs will not update through Quik, any update through Quik will uninstall Labs.

**Comment by Cenzo848** [comment]
Thank you for your help, I really appreciate it.
I assumed that after the first download the QR reading facility would then be embedded in the GoPro forever.
I have done the update provided in the link. And yes it now works.
So for future reference I am best to ignore the gopro update and look on here for the new update as that will still allow me to read QR codes.

**Comment by dnewman-gpsw** [comment]
Yes, ignore those update notices, just use them as a reminder to look for new firmware on  https://gopro.github.io/labs/, it is normally there within a few days.

**Comment by Cenzo848** [comment]
Thank you

**Comment by xgqfrms** [comment]
> 2.12 is not Labs. Only 2.12.70. You can install Labs from https://gopro.github.io/labs/ Labs will not update through Quik, any update through Quik will uninstall Labs.


## update through Quik App === uninstall Labs firmware ❓

https://github.com/gopro/labs/issues/1150

**Comment by dnewman-gpsw** [comment]
If that any reason you need to do that, please explain, as if there are any bugs in Labs we will want to know about that to address them.  Quik only installs stock firmware.  Stock firmware is also available on the GoPro website, search for firmware.
