### ISSUE TITLE
Security issues - add some tokens to codes

### ISSUE THREAD

**Issue by zbyrek** [gopro/labs#55]
Hello,

I know this whole firmwre is experimental and shouldn't be used in normal oepration, but you should consider adding unqie tokens to these qr codes, because right now anyone can change your camera settings with printed codes and maybe even use some invalid codes to broke gopro.

**Comment by Manouchehri** [comment]
Fundamentally this wouldn't help, as there's nothing stopping attackers from printing out those tokens like a normal user would. 

Tying features and setting to the serial number would be a very unwanted DRM..

QR code scanning does not occur once you're recording (unless you manually enable that). So if you're worried, just point the camera at the ground when you turn it on, start recording, and then you're good.

**Comment by zbyrek** [comment]
It would help a lot, because then attack must be targeted against some specific person/camera and right now I could just print some stickers and put them in public places to get random people annoyed.

I'm not talking about tying it to serial number (I know it is great to set severals gopro cameras at once) just otpion to enter some key with other qr code which would be needed for every next qr code to take action.

**Comment by dnewman-gpsw** [comment]
It has not been an issue so far.  The serious command like BLE and WiFi pairing require user responses on camera.  I also feel convenience of QR codes for configuration would be do greatly reduced with any DRM-like controls.
