### ISSUE TITLE
GoPro Hero 12 GoPro Labs Hindsight not working

### ISSUE THREAD

**Issue by dnewman-gpsw** [gopro/labs#558]
### Discussed in https://github.com/gopro/labs/discussions/557

<div type='discussions-op-text'>

<sup>Originally posted by **FlyTieGuy** September 21, 2023</sup>
GoPro Labs on the hero 12.
The code for hindsight !MHSTO=60 worked on my GoPro 11 Black
But on the 12 it stops working again after 15 minutes, when I set to 60 minutes. It’s as if the code hasn’t registered at all. On the 11 when the camera is activated there is a message which states Features enabled and the code for Hindsight appears but that isn’t happening on the 12. This is an important feature for me so I’d appreciate a resolution.</div>

**Comment by dnewman-gpsw** [comment]
Planned for the next release in about a month or so.

**Comment by ImmortlF350** [comment]
Not sure if this helps, but the behavior on my Hero 12 is a tick different than described above. I DO see the HSTO=1440 when booting. However after a period of time (believe about 15 min which would make sense), the actual recording of the loop seems to stop but the hindsight button is active. If I wake up the screen by touching it after no camera interaction for 16 min or so, the hindsight icon remains active and the counter starts indicating recording (+1s, +2s, +3s, etc...) now that I woke it up,. It seems to suddenly start recording the 30s loop when I wake up the screen.

**Comment by dnewman-gpsw** [comment]
Try the Labs build released yesterday. It will support HSTO for extended Hindsight captures.
