### ISSUE TITLE
GoPro 12 issues

### ISSUE THREAD

**Issue by GAMJoker** [gopro/labs#560]
- DAUD and DLRV have no effect, saw it on patchnotes already. Would be great if it could be fixed for the GoPro 12.

- HIST (Histogram) & EXPS (Exposure settings) work properly while not recording. As soon as I hit record, they start to blink (disappear and appear again). The histogram disappears more frequently. Would be great if after hitting the record button, it either turns off completely, or shows constantly. This blinking/glitching is very distracting.

**Comment by dnewman-gpsw** [comment]
DAUD and DLRV are not enabled in the camera core FW, it was on older models, so there currently nothing for Labs to hook on to. 

HIST has flickered on older models, so this is not new.  If you move it to the front screen with HSTP, the flicker is much less, although front screen histogram is much less convenient for many uses. oMEXPS=0oMHIST=1oMHSTP=-1,20,90

Issue will remain open, as this are valid annoyances.

**Comment by GAMJoker** [comment]
> DAUD and DLRV are not enabled in the camera core FW, it was on older models, so there currently nothing for Labs to hook on to.
> 
> HIST has flickered on older models, so this is not new. If you move it to the front screen with HSTP, the flicker is much less, although front screen histogram is much less convenient for many uses. oMEXPS=0oMHIST=1oMHSTP=-1,20,90
> 
> Issue will remain open, as this are valid annoyances.


Alright, thanks for your answer :)
It's a bummer that the audio can't be disabled completely. 
I do a lot of recording in public. Sadly, in my country it's illegal to record audio of people in public in many cases. So if there's no way to not record the audio at all, I would make myself punishable recording with the Hero 12.
Will probably have to go back to my Hero 11 then in the meantime.

**Comment by dnewman-gpsw** [comment]
There is a solution, use the command oMMUTE=15 (!M for permanent), this will mute all audio inputs, no "audio" will be recorded, other than a blank track. 

Which country has this law?  I want to provide this information to product management to this can be made a main feature, or it least get DAUD fixed for Labs.
