### ISSUE TITLE
!MWAKE=2 no work in Hero 11 without battery

### ISSUE THREAD

**Issue by joakyhsf69** [gopro/labs#568]
Hello, on the Hero11 with version 2.12.70 the !MWAKE=2 command does not work for me, neither with battery nor with USB. Only on some occasions, with the battery inserted, when connecting the USB it starts. In the previous version and in other Hero8s that I have, it works fine. What could be the problem?
And another question, is there a way to not ask the time when the battery has been removed for a long time? on both Hero8 and Herro11.
Thanks

Edit: Correction, with the battery on it always works, but without the battery it doesn't. Before it worked, even without the battery in

**Comment by dnewman-gpsw** [comment]
This is known, and will be addressed in an official release in a month or so.  However there was a patch for this one bug made available as 2.12.71: https://www.dropbox.com/t/mHuJUQ6O60b9q4N2

**Comment by joakyhsf69** [comment]
Yeah! Thank you! This patch solves my problem, very grateful.
Regarding the date, is there any solution? especially on the Hero 8, that window is visible through the HDMI, on the Hero 11 it seems that it is not visible, but it is annoying anyway.
Thank you

**Comment by dnewman-gpsw** [comment]
To stop the date/time update nagging try !MBYPS=1  This control was add on HERO11 and 12.

**Comment by dnewman-gpsw** [comment]
Closed as this is fixed within Labs release 1.12.70 https://gopro.github.io/labs/
