### ISSUE TITLE
Construction Time-lapses Shooting RAW option

### ISSUE THREAD

**Issue by Psicosour** [gopro/labs#57]
The Construction Time-lapses code ( https://gopro.github.io/labs/control/construction/ ) is very useful, but it would be great to have de option to choose to shoot in RAW instead of just JPG.

Really new to this. Any help will be appreciated.

**Comment by dnewman-gpsw** [comment]
If you enable raw in camera, very the app, or via QR Code, the above linked scripted will shoot raw.  This is an independent control, and doesn't need to be part of the construction timelapse script.
