### ISSUE TITLE
Altered Filename doesn't survice power cycle on Hero10

### ISSUE THREAD

**Issue by marklith** [gopro/labs#59]
The title pretty much says it all, I set the Altered Filename with this format:

GOPRO10-[ddmmyy(HH.MM)]-

And it works fine until I turn the GoPro 10 off and on again.  

Is this a feature, a bug or user error?

**Comment by dnewman-gpsw** [comment]
Partly user error, partly the control "Make this name change permanent" was as prominent as it could have been.  Click that.
