### ISSUE TITLE
Livestreaming

### ISSUE THREAD

**Issue by rmoriz** [gopro/labs#6]
Setting up live-streaming to RTMP is a PITA in the app. It would be awesome if one can create a QR code with the configuration and the just scan it to start a recording.

**Comment by dnewman-gpsw** [comment]
This was planned, but the was a bug in the release version of the first Labs firmware that prevented this feature from working. Hopefully addressed in a future firmware release.

**Comment by rmoriz** [comment]
Can you keep this issue open until a fix is available?

**Comment by dnewman-gpsw** [comment]
Sure can.

**Comment by dnewman-gpsw** [comment]
Now supported in the Labs 2021 firmware. More info here: https://gopro.github.io/labs/control/rtmp/
