### ISSUE TITLE
Ideas on how to remotely monitor a Construction Time Lapse?

### ISSUE THREAD

**Issue by Psicosour** [gopro/labs#60]
My cameras are not easely accesible, and I used to check them weekly via de GoPro app, but when using the code is not possible to use the app. I don't want to check the camera a month from now to find out it only has one day of photos.

I have my cameras charged constantly via USB by an external battery, since I'm only taking 24 photos per day, perhaps the cameras could run "unsupervised" for a couple of months. But how to be sure they are still running?

**Comment by dnewman-gpsw** [comment]
Mostly GoPro will not work will using wake commands, with in the internal battery and external power (chose one power source.) If you can be in WiFi range, the best solution is to upload once a day with !U command.  Here is an example: https://gopro.github.io/labs/control/dailytl/

24 photos a day is good for about 10 days, even on the internal battery. With external power (not internal battery) you will get 500-1000 for something random goes wrong during the boot up or shutdown.  If you can use the daily script (linked above) it is much more reliable, as the camera doesn't wake and shutdown nearly as often.

**Comment by filipeg165** [comment]
The script mentioned above is giving me a lot of issues, the camera shuts off completely 10 seconds before starting the Timelapse, and it also turns off wireless comms, it is not reliable at all at the moment.
