### ISSUE TITLE
EXPX/EXPN: confusing documentation

### ISSUE THREAD

**Issue by kouyoumin** [gopro/labs#602]
[https://github.com/gopro/labs/blob/665b4f7fa83eff37cb672a7b41d87a4099dde0f1/docs/control/extensions/README.md?plain=1#L56](https://github.com/gopro/labs/blob/665b4f7fa83eff37cb672a7b41d87a4099dde0f1/docs/control/extensions/README.md?plain=1#L56)
I'm confused about the documentation.
1/500s is definitely "more speedy" than 1/48s.
Why the example set 1/500s as min speed and 1/48s as max speed?

**Comment by dnewman-gpsw** [comment]
These controls are exposure times, not speed.  I fixed the wording in the docs.  So 1/500 is the exposure time minimum (EXPN.)
