### ISSUE TITLE
HERO12 Livestream Start Issue

### ISSUE THREAD

**Issue by Carafichon** [gopro/labs#603]
Hi,
I work at a tv broadcast company and we are used to use Labs for our Gopros 10. For our new (and VERY important) live, we wanted to get Gopro 12. Issue : the Labs command are not executed well. We use this page to create QR https://gopro.github.io/labs/control/rtmp/

It SHOULD go as followed : 
- Search network
- Find network and connect to it
- launch broadcast

Here it goes : 
- search network
- find network and connect to it
- attempt to launch broadcast and 
- REBOOT
- start over
- ....etc

With SAME camera, SAME wifi router, the broadcast launches perfectly through the GoProQuik App.
Is there a fix ? are we alone ? 
thanks a lot friends

**Comment by dnewman-gpsw** [comment]
Good news, is will work on HERO12, it just that the instruction needed to change.  Livestreaming is a little easier to start on HERO12, as the old command was oW1mVr1080!W!GLC, but now !GL or !GLC is sufficient.

The RTMP page has been updated for HERO12 support (there is a new HERO12 checkbox.)

**Comment by Carafichon** [comment]
Hi, thanks a lot !!! Will try this ASAP and come back to you if it's actually fixed ! 
Good day and thanks again

**Comment by Carafichon** [comment]
Ok, it works really good, strange that we have to unable/disable auto transfer but it works ! maybe gopro wants us to subscribe to Gopro+ ? ;) 
I have another question for you since you know your topic ! Is it possible to change gopro camera's streaming bitrate ? As of today it seems locked at 5mb/s (1080p) and 3mb/s(720p). 

Thanks a lot

**Comment by dnewman-gpsw** [comment]
Yes using oMBITL=x can set the max bitrate. BITL to supports Kb/s (oMBITL=5500) and Mb/s (oMBITL=6).  While I have run as high as 8Mb/s, stream stability is not guarantied (network dependent.)

**Comment by Carafichon** [comment]
thanks ! it's really good help for us !!
