### ISSUE TITLE
GoPro Hero 9 not labs not letting me change resolution or FPS

### ISSUE THREAD

**Issue by andrewlongron** [gopro/labs#612]
I have a GoPro 9 and a GoPro 11. The 11 worked perfect with the labs code and I changed it to 5k at 60fps. 
The 9 on the other hand continues to make all the changes except the FPS and resolution. Both have Hindsight enabled upon startup and I was attempting to get the 9 to do 4K at 120fps. This is going to be the camera mounted to the front of the boat so I can capture everything and be able to slow it down. 

Anyone know what the issue may be?

**Comment by dnewman-gpsw** [comment]
H9 doesn't do the same fps as H11 at the same resolutions.  I expect that is the issue.  Choose a video mode H9 has.

**Comment by andrewlongron** [comment]
hey dickhead, GP 11 doesn't come with 5k at 60fps so you going to tell me to choose something the 11 has and dont force a labs code for 5K at 60 Fps? 
If youre not going to be any help then keep your comments to your self. 

IM TELLING YOU THAT IT WONT LET ME CHANGE ANY OF THE VIDEO SETTINGS AT ALL. better? 
smartass.

**Comment by dnewman-gpsw** [comment]
Well this turn quickly.  GP11 does have 5.3k at 60fps (16x9), only the H9 doesn't, like is doesn't have 4K120.

**Comment by andrewlongron** [comment]
its bad enough that these cameras are crap and need constant attention or updates to function correctly but as outdoor content creators we really dont have any other choice when it comes to outdoor cameras. 

We also don't need people who have no maturity at all when it comes to helping others.

**Comment by andrewlongron** [comment]
So labs is basically useless is what you're saying since I can't change any of the functions passed what I bought it with.
