### ISSUE TITLE
David Newman 

### ISSUE THREAD

**Issue by andrewlongron** [gopro/labs#614]
I wasn't done getting my answer so how can you force close my issue. 

This right here just solidify's my final straw in throwing these things in the garbage where they belong. 
I have lost countless amounts of footage due to the severe reliability issues and to see this is how the people at GOPRO treat people and talk to them is why im going to make sure everyone I know doesnt buy another product from GOPRO ever. 

Everyone is goign to know about this is how GoPro handles their issues. I'll make sure of it. 
And your LinkedIn profile says pretty much all I need to know about you. Not much of a people person uh? 
<img width="927" alt="Screenshot 2023-10-22 at 18 22 09" src="https://github.com/gopro/labs/assets/131631548/05fcde20-39a5-4048-b2d6-1fc5a3d34a50">

**Comment by dnewman-gpsw** [comment]
So you welcome to do that else where. You are the only one behaving disrespectfully
