### ISSUE TITLE
Linear View Not being set

### ISSUE THREAD

**Issue by jamalionline333** [gopro/labs#623]
I have Gopro 7 black and QR code is a blessing for me as my screen not working perhaps only I can record directly. But when I select for Linear view  for video and Picture, its not being set as always Wide angle being selected in place of Linear. Kindly fix the bug as Linear view is the most important view for filming for natural look.

**Comment by dnewman-gpsw** [comment]
Repeated on discussions

**Comment by jamalionline333** [comment]
I  really appreciate as you informed solution code regarding my issue through email. I am really happy
