### ISSUE TITLE
[HERO 9] 2 frames are missing in LRV timecode

### ISSUE THREAD

**Issue by Audrik** [gopro/labs#630]
Hello, I try to use my gopro Hero 9 LRV files with DaVinci Resolve proxy option, but there's an import error. After search in file, I can see the HD file timecode is 2 frames longuer than the LRV file.

Is it possible to resolve this issue please?

**Comment by dnewman-gpsw** [comment]
Is this always the case, or only some files?  The PRXY option was only offered for HERO10 onward, I'm guessing LRV length was more reliable on those camera models.  There are no planned updates for HERO9 or any GP1 camera. Also this is not a Labs bug to fix, as it sounds like the error is within the core camera firmware.
