### ISSUE TITLE
EXPS=number not working on HERO11 Mini

### ISSUE THREAD

**Issue by RikshaDriver** [gopro/labs#635]
When settings EXPS=30 or some other numerical value outside 1, the ISO & Shutter display are not displayed at all on the LCD.

The only value that seems to work is EXPS=1

Is the numerical value in seconds or minutes and does it set how long the values are displayed or a set interval at which they are displayed?

**Comment by dnewman-gpsw** [comment]
Sorry that feature is poorly documented.  The values for EXPS is 1 thru 6.  1 - shows expose most of the time, capture length sometimes, 6 - shows capture length most of the time, and exposure sometime.  3,4 are ~50-50.  It is a dumb control to share the display.

**Comment by dnewman-gpsw** [comment]
I will update the docs.

**Comment by dnewman-gpsw** [comment]
microphone level?  *EXPS=1*AUDS=1 displays both, microphone and exposure data.

**Comment by euromarco** [comment]
> microphone level? _EXPS=1_AUDS=1 displays both, microphone and exposure data.

Sorry again but AUDS=1 doesn't help me...
I would like to avoid the overlap of the Sound meter with the very useful line EXPS
![Screenshot_20240905_160837_Studio](https://github.com/user-attachments/assets/fc537ecf-b018-4628-b630-6234b9f47571)
Tank you, Marco

**Comment by dnewman-gpsw** [comment]
This ticket is about HERO11 Mini (read the title), so I answered for a Mini. This is a different issue, no solution currently.
