### ISSUE TITLE
Hero 10 Black motion detection issues

### ISSUE THREAD

**Issue by z0mb0funk** [gopro/labs#64]
When I attempt to use the motion detection feature on my hero 10 black, the countdown stops immediately and my gopro needs to be restarted before it will scan another QR code.

**Comment by z0mb0funk** [comment]
When the motion detection QR code works as intended, it won't repeat on photo mode.

**Comment by dnewman-gpsw** [comment]
Correct, not design for photo.  However it will work in timelapse photo mode.  There is a bug in 1.42.70, that is fixed with scanning !MQRDR=1 once.

**Comment by z0mb0funk** [comment]
Thanks for the response. Motion activation works on photo mode for my Hero 8 Blacks so I assumed it would work on them all. Good to know.

I’m not sure what to do with the !MQRDR=1 . Am I supposed to be able to convert that to a QR code?

**Comment by dnewman-gpsw** [comment]
QR codes are just text.  Just put !MQRDR=1 into a QR code, use the added command field. 

 P.S.  Even HERO8 had issues with photo motion detection.
