### ISSUE TITLE
Max Overlay not working

### ISSUE THREAD

**Issue by KaiKorzonek** [gopro/labs#641]
Hi,

Im trying to add an overlay for my max 360 footage and I'm wondering if this is possible. It says on the QR page it is compatible with the max however on the github read me it shows its not. I've tryed it in many different configurations doesn't seem to work had anyone managed to get this to work.

Thanks

**Comment by dnewman-gpsw** [comment]
It works, but is limited.  You have to render the text with the fisheye image circle.  

oMBURN="(0,20)[MCHH:MM:SSaa mm-dd-yyyy ]"  <- this will render in the middle of the front lens.

oMBURN="(0,20)[BCHH:MM:SSaa mm-dd-yyyy ]"  <- this will render at the bottom nadir.
