### ISSUE TITLE
Exact frame synchronisation with Jam sync 

### ISSUE THREAD

**Issue by muddywellyboots** [gopro/labs#65]
Hi,
I am trying to extract sync'ed frames from footage from two hero 9's, with the sync'ing as accurately as possible.
I've been using the qr code method to jam sync the time code of the two gopros.

Can anyone advice on the most accurate way to extract synced frames? Offsetting one of the files by the start times with ffmpeg, then using ffpeg to extract frames at intervals? Or should I look at trying to actually read the timecode track?

Thansk

**Comment by dnewman-gpsw** [comment]
QR Codes for time sync is only going to impact the timecode precision, so reading the timecode track is the path you should take.

**Comment by dnewman-gpsw** [comment]
I don't know what ffmpeg switches allow reading the time (if it supports it). All good video edit tools will read the timecode.  Programmatically is it straight forward. Read the timecode track's stco atom, this has the file offset to timecode, a 32-bit number for frames since midnight.
