### ISSUE TITLE
Two Gopro 11 mini bricked after update  v2.30.70

### ISSUE THREAD

**Issue by ivrj** [gopro/labs#651]
I've updated two gopro 11 mini to last version  v2.30.70 and they has bricked and wont power on anymore.

The reset  procedure maked it blinks the power led twice.
After this they wont power on and warms a bit  until battery goes off. 

One gets stuck on update logo animation for a long time. The second one update fine, read some qr codes ok, but after power off , wont power on.

The second camera wont detect usb power /charger battery.

**Comment by dnewman-gpsw** [comment]
Can you provide metadata from the last files captured.  This is likely a conflict with the commands you have set, so knowing what you set can help in recovery.  Use this tool to read the metadata https://gopro.github.io/labs/control/metadata/ and share the results here.

**Comment by ivrj** [comment]
The newest goprop  is fresh out of the box, didnt record nothing on it. Just flash the update. The only QR readed is the  precisiontime: https://gopro.github.io/labs/control/precisiontime/

The oldest, this is the last metadata: 


DEVC 
  DVID 1
  DVNM Global Settings
  VERS 8, 2, 2
  FMWR H22.03.02.20.70
  LINF LSU2081402401675
  CINF 25, -68, 104, -69, -126, 13, 60, 76, -111, 32, 119, 65, -110, 86, 120, -82
  CASN C3494224631794
  MINF HERO11 Black Mini
  MUID -1150764007, 1279004034, 1098326161, -1367845230, 0, 0, 0, 0
  CMOD 12
  MTYP 0
  OREN U
  DZOM Y
  DZST 0
  SMTR N
  PRTN Y
  PTWB 5500K
  PTSH HIGH
  PTCL FLAT
  EXPT AUTO
  PIMX 400
  PIMN 100
  PTEV 0.0
  RATE .empty.
  SROT 15.0000
  EISE N
  EISA N/A
  HCTL Off
  AUPT N
  APTO OFF
  AUDO AUTO
  BROD .empty.
  BRID 0
  PVUL F
  PRJT GPRO
  SOFF 0
  CLKS 2
  CDAT 0x0000000064D806D0
  SCTM 0
  PRNA 10
  PRNU 0
  SCAP N
  CDTM 0
  DUST NO_LIMIT
  VRES 5312, 2988
  VFPS 30000, 1001
  HSGT OFF
  BITR HIGH
  MMOD STEREO
  RAMP .empty.
  TZON -180
  CLKC 0
  DZMX 1.4000
  CTRL Pro
  PWPR PERFORMANCE
  ORDP Y
  CLDP Y
  PIMD MANUAL
DEVC 
  DVID FOVL
  DVNM Large FOV
  ABSC 0.0000
  ZFOV 100.6058
  VFOV L
  MXCF x1
  MAPX 1.0000
  MYCF y1
  MAPY 1.0000
  PYCF r0r1r2r3r4r5r6
  POLY 0.0000, 1.8151, 0.1035, -2.9413, 3.5951, -1.8582, 0.3529
  ZMPL 0.6627
  ARUW 1.7778
  ARWA 1.7778
DEVC 
  DVID USRM
  DVNM User Metadata
  STRM 
    BITR 120
    SYID 0
    SYTM 230616135211.604
    SPED 2
    USRD 1
DEVC 
  DVID HLMT
  DVNM Highlights

**Comment by dnewman-gpsw** [comment]
Oh..., user error, you permanently enabled SD card speed testing (you did !MSPED=2.) So that all these cameras will do now, speed test upon boot, then reboot forever.  With 2.30.70 the timing is different so that SPED will crash as a permanent command.

Warning: for others, don't use the permanent flag with features you don't need on boot up.

Yes this is a Labs bug.  You are the first to do on Mini, but it was on HERO11/12 too.  

I'm trying to see if there a recovery procedure (this is for full size cameras), so far it hasn't worked on my Mini (now bricked too.)  If can't find a solution in 24hours, contact support for replacements.

**Comment by dnewman-gpsw** [comment]
I have determined it is recoverable, I just need to get you custom recovery firmware to do it.  This will take about an hour.  You will need a 32GB sd card, as this will not work on larger cards.

**Comment by dnewman-gpsw** [comment]
Try this recovery firmware 

The recovery procedure is detailed, so follow the steps precisely.

Use a 32 GB SD Card or less. If you see a failure in the commands below try to reformat the SD card or try a different card.
1. Download and unzip this archive  https://www.dropbox.com/t/MKxyimisoyKyyQrk
2. Copy the contents of the zip (10 files) to the root of the SD card. 
3. Insert the SD card.
4. Press and hold the Mode and Shutter buttons for 10 sec, then while buttons are held insert Type-C USB cable to the camera 
   Type-C USB cable should be connected to a good charger.
   Once USB is inserted, release the just mode button, LED should turn on solid after some delay. At this moment, you can release the Shutter button.
   4.1. Front LED will start blinking after about 10 sec for 5-10 times.
   4.2. After the blinks, the LED will either stay ON solid or turn OFF.
6. Wait for a few sec after the blinking stops
7. Press Mode button for 10 seconds and release to reboot and to turn ON the camera. Camera will hopefully be ready to use.

This procedure may not work on Mini 11 if the battery is too greatly depleted.  Let me know how it goes.

**Comment by ivrj** [comment]
I let it charging for a while.
Then try the steps, but led didn't turn solid. Dont blink.
Led just blink twice after press only mode  for 10 sec.
When press mode + shutter for 10sec , plug usb, release mode , nothing happen.

**Comment by dnewman-gpsw** [comment]
This is very hard to do, so I not 100% sure you have it correct (it took me a few goes.) You should have about 10 files in the root directory, in addition to the UPDATE folder?  The release of mode button after 10s seconds should cause a reboot, the shutter depressed with those files + USB power, is supposed to force an update. This is not a customer face update procedure, so it is tricky.

**Comment by ivrj** [comment]
IT WORKS!! 🤩🤩🤩🤩
I changed the sdcard to another 16bits and format as Fat16 with 4096bytes alocation. Works on first try. Thank you!!!

How can I reset this permanents settings  from QrControl?

**Comment by dnewman-gpsw** [comment]
You will not be able to do a regular update until that setting is removed.  So after the recovery it doesn't boot fully?  Can you scan !MSPED=0 ?

**Comment by ivrj** [comment]
yes, boot up fully ! 

Cam scanned !MSPEED=0.  

This is now metadata:
```

DEVC 
  DVID 1
  DVNM Global Settings
  VERS 8, 2, 0
  FMWR H22.03.02.39.77
  LINF LSU2102001402259
  CINF 49, -85, 31, -20, 7, 16, -93, -124, -128, 125, -80, 20, 60, -106, -118, 75
  CASN C3491124748659
  MINF HERO11 Black Mini
  MUID -333468879, -2069688313, 347110784, 1267373628, 0, 0, 0, 0
  CMOD 12
  MTYP 0
  OREN U
  DZOM Y
  DZST 0
  SMTR N
  PRTN Y
  PTWB AUTO
  PTSH MED
  PTCL FLAT
  EXPT AUTO
  PIMX 200
  PIMN 100
  PTEV -1.0
  RATE .empty.
  SROT 13.0000
  EISE N
  EISA N/A
  HCTL Off
  AUPT N
  APTO OFF
  AUDO AUTO
  BROD .empty.
  BRID 0
  PVUL F
  PRJT GPRO
  SOFF 0
  CLKS 1
  CDAT 0x0000000065688F67
  SCTM 0
  PRNA 10
  PRNU 0
  SCAP N
  CDTM 0
  DUST NO_LIMIT
  VRES 3840, 2160
  VFPS 30000, 1001
  HSGT OFF
  BITR HIGH
  MMOD STEREO
  RAMP .empty.
  TZON -180
  CLKC 0
  DZMX 1.4000
  CTRL Pro
  PWPR PERFORMANCE
  ORDP Y
  CLDP Y
  PIMD MANUAL
DEVC 
  DVID FOVL
  DVNM Large FOV
  ABSC 0.0000
  ZFOV 133.3860
  VFOV W
  MXCF x1
  MAPX 1.0000
  MYCF y1
  MAPY 1.0000
  PYCF r0r1r2r3r4r5r6
  POLY 0.0000, 1.8151, 0.1059, -0.6547, 0.3502, -0.0000, 0.0000
  ZMPL 0.6881
  ARUW 1.7778
  ARWA 1.7778
DEVC 
  DVID USRM
  DVNM User Metadata
  STRM 
    SYID 16541
    SYTM 231130110815.264
    SPED 0
    DLTM 
    USRD 1
DEVC 
  DVID HLMT
  DVNM Highlights

```

**Comment by ivrj** [comment]
everything ok now! reset command applied!
TY!!!
 
```

DEVC 
  DVID 1
  DVNM Global Settings
  VERS 8, 2, 0
  FMWR H22.03.02.39.77
  LINF LSU2102001402259
  CINF 49, -85, 31, -20, 7, 16, -93, -124, -128, 125, -80, 20, 60, -106, -118, 75
  CASN C3491124748659
  MINF HERO11 Black Mini
  MUID -333468879, -2069688313, 347110784, 1267373628, 0, 0, 0, 0
  CMOD 12
  MTYP 0
  OREN U
  DZOM Y
  DZST 0
  SMTR N
  PRTN Y
  PTWB AUTO
  PTSH MED
  PTCL FLAT
  EXPT AUTO
  PIMX 200
  PIMN 100
  PTEV -1.0
  RATE .empty.
  SROT 13.0000
  EISE N
  EISA N/A
  HCTL Off
  AUPT N
  APTO OFF
  AUDO AUTO
  BROD .empty.
  BRID 0
  PVUL F
  PRJT GPRO
  SOFF 0
  CLKS 1
  CDAT 0x0000000065689D39
  SCTM 0
  PRNA 10
  PRNU 0
  SCAP N
  CDTM 0
  DUST NO_LIMIT
  VRES 3840, 2160
  VFPS 30000, 1001
  HSGT OFF
  BITR HIGH
  MMOD STEREO
  RAMP .empty.
  TZON -180
  CLKC 0
  DZMX 1.4000
  CTRL Pro
  PWPR PERFORMANCE
  ORDP Y
  CLDP Y
  PIMD MANUAL
DEVC 
  DVID FOVL
  DVNM Large FOV
  ABSC 0.0000
  ZFOV 133.3860
  VFOV W
  MXCF x1
  MAPX 1.0000
  MYCF y1
  MAPY 1.0000
  PYCF r0r1r2r3r4r5r6
  POLY 0.0000, 1.8151, 0.1059, -0.6547, 0.3502, -0.0000, 0.0000
  ZMPL 0.6881
  ARUW 1.7778
  ARWA 1.7778
DEVC 
  DVID USRM
  DVNM User Metadata
  USRD 1
DEVC 
  DVID HLMT
  DVNM Highlights

```

**Comment by dnewman-gpsw** [comment]
The official 2.40 should be out in a few weeks, you can update to that, stay on 2.39.77 or wish to 2.30.70.  All will work fine now. Not significant differences between them.

**Comment by IsmagilTim** [comment]
Hello! I'm facing the same problem with my Mini 11 camera. It doesn't turn on after pressing the power button for 10 seconds, it doesn't respond to charging, and it also heats up. I've tried installing the update manually, but it didn't work. Could you please check the metadata of the latest file? What can I do in this situation?
DEVC 
  DVID 1
  DVNM Global Settings
  VERS 8, 2, 0
  FMWR H22.03.02.30.00
  LINF LSU2092302401511
  CINF -96, 90, -8, 99, 102, -84, -24, -4, -76, -16, 26, -76, 120, -24, -16, 53
  CASN C3491124708248
  MINF HERO11 Black Mini
  MUID 1677220512, -51860378, -1273302860, 904980600, 0, 0, 0, 0
  CMOD 12
  MTYP 0
  OREN U
  DZOM Y
  DZST 0
  SMTR N
  PRTN Y
  PTWB AUTO
  PTSH MED
  PTCL NATURAL
  EXPT AUTO
  PIMX 1600
  PIMN 100
  PTEV 0.0
  RATE .empty.
  SROT 13.0000
  EISE Y
  EISA HS EIS
  HCTL Off
  AUPT N
  APTO OFF
  AUDO AUTO
  BROD .empty.
  BRID 0
  PVUL F
  PRJT GPRO
  SOFF 0
  CLKS 2
  CDAT 0x0000000065CCCB49
  SCTM 0
  PRNA 10
  PRNU 0
  SCAP N
  CDTM 0
  DUST NO_LIMIT
  VRES 3840, 2160
  VFPS 60000, 1001
  HSGT OFF
  BITR STANDARD
  MMOD STEREO
  RAMP .empty.
  TZON 60
  CLKC 0
  DZMX 1.4000
  CTRL Pro
  PWPR PERFORMANCE
  ORDP Y
  CLDP Y
  PIMD MANUAL
DEVC 
  DVID FOVL
  DVNM Large FOV
  ABSC 0.0000
  ZFOV 95.5393
  VFOV L
  MXCF x1
  MAPX 1.0000
  MYCF y1
  MAPY 1.0000
  PYCF r0r1r2r3r4r5r6
  POLY 0.0000, 1.8151, 0.1035, -2.9413, 3.5951, -1.8582, 0.3529
  ZMPL 0.6061
  ARUW 1.7778
  ARWA 1.7778
DEVC 
  DVID HLMT
  DVNM Highlights

**Comment by dnewman-gpsw** [comment]
Not the same, the other users where running Labs and made a particular Labs related error, whereas you have a stock camera that needs tech support.

**Comment by retlw** [comment]
> Try this recovery firmware
> 
> The recovery procedure is detailed, so follow the steps precisely.
> 
> Use a 32 GB SD Card or less. If you see a failure in the commands below try to reformat the SD card or try a different card.
> 
> 1. Download and unzip this archive  https://www.dropbox.com/t/MKxyimisoyKyyQrk
> 2. Copy the contents of the zip (10 files) to the root of the SD card.
> 3. Insert the SD card.
> 4. Press and hold the Mode and Shutter buttons for 10 sec, then while buttons are held insert Type-C USB cable to the camera
>    Type-C USB cable should be connected to a good charger.
>    Once USB is inserted, release the just mode button, LED should turn on solid after some delay. At this moment, you can release the Shutter button.
>    4.1. Front LED will start blinking after about 10 sec for 5-10 times.
>    4.2. After the blinks, the LED will either stay ON solid or turn OFF.
> 5. Wait for a few sec after the blinking stops
> 6. Press Mode button for 10 seconds and release to reboot and to turn ON the camera. Camera will hopefully be ready to use.
> 
> This procedure may not work on Mini 11 if the battery is too greatly depleted. Let me know how it goes.

Hi, could you please update the dropbox link? And maybe there is something similar on gopro 10 black? Thanks for any help

**Comment by dnewman-gpsw** [comment]
The link was for Mini only. What is going on with your H10?

**Comment by retlw** [comment]
> The link was for Mini only. What is going on with your H10?

My Gopro 10 black shut down during a firmware downgrade from 1.6 to 1.4 and is now locked. I tried the firmware from the next topic https://github.com/gopro/labs/discussions/826. The camera illuminates the front screen and the LED above it lights up for a few seconds, then blinks 19 times. But the camera remained a brick. Could you take a look at the boot.par and pardata.par files, they look a little strange to me? Or provide a link to the documentation for stubby?

**Comment by dnewman-gpsw** [comment]
There is no documentation on this, as this is not a consumer intended experience.  After the ~19 blinks finish, wait a few seconds and remove power. Next attempt a normal update, using an UPDATE folder. Sometime that helps. Also camera downgrades are discouraged, as those permutations are not tested. I would not attempt to continue with 1.4, instead try and get the camera back to v1.62.70.

**Comment by retlw** [comment]
After 19 blinks, a normal update simply turns on the front screen and everything remains as it was. I just wanted to understand the process. Pardata.par, as far as I understand, is responsible for memory mapping? Or does it still depend on key verification at this stage? Are boot.par and pardata.par generated by stubby or written in manually?

**Comment by dnewman-gpsw** [comment]
No idea. I can't help with the process.

**Comment by retlw** [comment]
Ok, thanks for the help, I'll continue experimenting

**Comment by retlw** [comment]
I finally figured out H10. The file pardata.par is incorrect in the Dropbox Archive. Solution in this thread https://github.com/gopro/labs/discussions/826

**Comment by Mort0000** [comment]
> Можете ли вы предоставить метаданные из последних захваченных файлов? Вероятно, это конфликт с заданными вами командами, поэтому знание того, что вы задали, может помочь в восстановлении. Используйте этот инструмент для чтения метаданных https://gopro.github.io/labs/control/metadata/ и поделитесь результатами здесь.

friend, please tell me, I have the same problem, the camera turns on only when you hold the button for 10 seconds and not always, it heats up, records for 1 second and turns on. The camera is new out of the box, I used it for 2 weeks

DEVC 
  DVID 1
  DVNM Global Settings
  VERS 8, 2, 0
  FMWR H22.03.02.50.00
  LINF LSU2081104403541
  CINF 105, 118, 35, -39, 123, 114, -6, -91, 101, 66, 17, -97, -95, -11, -124, 30
  CASN C3491124699021
  MINF HERO11 Black Mini
  MUID -651987351, -1510313349, -1626258843, 512030113, 0, 0, 0, 0
  CMOD 12
  MTYP 0
  OREN U
  DZOM N
  DZST 0
  SMTR N
  PRTN Y
  PTWB AUTO
  PTSH MED
  PTCL NATURAL
  EXPT AUTO
  PIMX 1600
  PIMN 100
  PTEV 0.0
  RATE .empty.
  SROT 15.0000
  EISE Y
  EISA HS EIS
  HCTL Off
  AUPT N
  APTO OFF
  AUDO AUTO
  BROD .empty.
  BRID 0
  PVUL F
  PRJT GPRO
  SOFF 0
  CLKS 2
  CDAT 0x00000000678B12E4
  SCTM 0
  PRNA 10
  PRNU 0
  SCAP N
  CDTM 0
  DUST NO_LIMIT
  VRES 3840, 2160
  VFPS 30000, 1001
  HSGT OFF
  BITR STANDARD
  MMOD STEREO
  RAMP .empty.
  TZON 300
  CLKC 0
  DZMX 0.0000
  CTRL Pro
  PWPR PERFORMANCE
  ORDP Y
  CLDP Y
  PIMD MANUAL
DEVC 
  DVID FOVL
  DVNM Large FOV
  ABSC 0.0000
  ZFOV 138.5928
  VFOV S
  MXCF x1x3x5
  MAPX 1.2100, -1.2758, 1.7752
  MYCF y1y3y5y1x2y3x2y1x4
  MAPY 0.9365, 0.4465, -0.7683, -0.3574, 1.1585, 0.3529
  PYCF r0r1r2r3r4r5r6
  POLY 0.0000, 1.8230, 0.1068, -0.6632, 0.3563, -0.0000, 0.0000
  ZMPL 0.6549
  ARUW 1.3333
  ARWA 1.7778
DEVC 
  DVID HLMT
  DVNM Highlights

**Comment by dnewman-gpsw** [comment]
Contact GoPro support, a new camera can be replaced.  This is not a Labs question.

**Comment by Mort0000** [comment]
@dnewman-gpsw Sorry, I live in Kazakhstan and I have not received an answer for several times, they say they will call back and do not. If possible, can you help.

**Comment by dnewman-gpsw** [comment]
Nothing I can do.

**Comment by Pitos777** [comment]
> Try this recovery firmware
> 
> The recovery procedure is detailed, so follow the steps precisely.
> 
> Use a 32 GB SD Card or less. If you see a failure in the commands below try to reformat the SD card or try a different card.
> 
> 1. Download and unzip this archive  https://www.dropbox.com/t/MKxyimisoyKyyQrk
> 2. Copy the contents of the zip (10 files) to the root of the SD card.
> 3. Insert the SD card.
> 4. Press and hold the Mode and Shutter buttons for 10 sec, then while buttons are held insert Type-C USB cable to the camera
>    Type-C USB cable should be connected to a good charger.
>    Once USB is inserted, release the just mode button, LED should turn on solid after some delay. At this moment, you can release the Shutter button.
>    4.1. Front LED will start blinking after about 10 sec for 5-10 times.
>    4.2. After the blinks, the LED will either stay ON solid or turn OFF.
> 5. Wait for a few sec after the blinking stops
> 6. Press Mode button for 10 seconds and release to reboot and to turn ON the camera. Camera will hopefully be ready to use.
> 
> This procedure may not work on Mini 11 if the battery is too greatly depleted. Let me know how it goes.

Hello, could you update the link to Dropbox with the Gopro 11 Mini firmware recovery files. The link from this post is more inaccessible. Thanks in advance.

**Comment by radosek** [comment]
[dnewman-gpsw](https://github.com/dnewman-gpsw) would it be possible to reupload recovery files for 11 mini, please? Thank you!
