### ISSUE TITLE
Gopro 10 not responding to motion control Q

### ISSUE THREAD

**Issue by vermontgopro** [gopro/labs#66]
Hi, 
I just started using my GP 10 today and uploaded the firmware and then added a Q code for motion detection. When I place the Q in front of the GP I see the Q with a check mark and then the words "detection in 5" but then the camera does not go into motion detection mode. I use the same feature on my GP 8/9 without issues. I set the screen off for the 8/9 and leave it on as directed for the GP 10. Also, when I use the GP 8 or 9 the detection counts down the seconds I have delayed. 

Any solutions?
Screen shot of my Q code. 
<img width="1728" alt="Screen Shot 2022-07-05 at 3 58 16 PM" src="https://user-images.githubusercontent.com/108763294/177408222-ef3ac989-3952-4691-b4e5-e8de3ade2aed.png">

**Comment by dnewman-gpsw** [comment]
This is a known bug in 1.42.70 (next firmware version will fix it.)  Fortunately there is a simple workaround using the command !MQRDR=1 (just once) 
![image](https://user-images.githubusercontent.com/10856084/177598947-2d553397-3d33-4043-8a6a-355cdd3a3b2e.png)
