### ISSUE TITLE
!PA for MAX

### ISSUE THREAD

**Issue by attila0307** [gopro/labs#667]
I have a MAX with a non-working LCD (as many other users have this problem, also it's my second one with the same problem).
I was happy when I saw the !PA Feature FourCC, but then I saw it's only for H8-12.
Can you make it for GoPro MAX?

**Comment by dnewman-gpsw** [comment]
Always experiment, as there is a good chance the docs are wrong.  In this case it works fine, as MAX firmware as updated in April.

Scan !PA and then press shutter 3 times quickly (it would say that if your LCD was working.)
