### ISSUE TITLE
GoPro Hero 10 Daily Timelapse wifi shutoff and error

### ISSUE THREAD

**Issue by logan012534** [gopro/labs#67]
I have four GoPro Hero 10s running version 01.42.70 set to use the daily timelapse and auto upload feature for a construction job. I have found that the camera will change the Wireless Connection setting from ON to OFF some days, and it will have to manually be switched back on. Has anyone else experienced this? If the camera cannot find a signal when it is going to upload to the cloud will it shut the wireless setting off?

Separately, during testing I have seen the camera fault out when it goes to begin the timelapse and very briefly show an error/warning before it turns off, but I have not been able to replicate this issue to actually read the message. Has anyone else experienced this?

Thanks for any feedback

**Comment by dnewman-gpsw** [comment]
Sorry I've haven't seen the second error -- let me know if learn more on that.

The Wireless Connection is automatically turned off to preserve battery in the longer intervals for the Labs style timelapse.  If you using the !U for auto upload in a custom timelapse script, you can add oW1 to turn the WiFi back on.

**Comment by logan012534** [comment]
Thanks for the reply. Im not sure I follow how to make that change, I am using the webpage with the sliders to generate a QR code. How would I modify that to keep wifi on?On Jul 6, 2022 12:26 PM, David Newman ***@***.***> wrote:
Sorry I've haven't seen the second error -- let me know if learn more on that.
The Wireless Connection is automatically turned off to preserve battery in the longer intervals for the Labs style timelapse.  If you using the !U for auto upload in a custom timelapse script, you can add oW1 to turn the WiFi back on.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/gopro/labs/issues/67#issuecomment-1176428264",
"url": "https://github.com/gopro/labs/issues/67#issuecomment-1176428264",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dnewman-gpsw** [comment]
You haven't explains why you want WiFi on, as it should not be if you want an extended runtimes. If you are externally powering, and auto uploading you should be this script: https://gopro.github.io/labs/control/dailytl/  This is more reliable, and the newer recommended solution.

**Comment by logan012534** [comment]
That is the one I am using. The wifi is to upload the daily video to the cloud. The camera is externally powered and set to auto upload, but will switch the wireless connection off.On Jul 6, 2022 1:14 PM, David Newman ***@***.***> wrote:
You haven't explains why you want WiFi on, as it should not be if you want an extended runtimes. If you are externally powering, and auto uploading you should be this script: https://gopro.github.io/labs/control/dailytl/  This is more reliable, and the newer recommended solution.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/gopro/labs/issues/67#issuecomment-1176479005",
"url": "https://github.com/gopro/labs/issues/67#issuecomment-1176479005",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]On Jul 6, 2022 1:14 PM, David Newman ***@***.***> wrote:
You haven't explains why you want WiFi on, as it should not be if you want an extended runtimes. If you are externally powering, and auto uploading you should be this script: https://gopro.github.io/labs/control/dailytl/  This is more reliable, and the newer recommended solution.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/gopro/labs/issues/67#issuecomment-1176479005",
"url": "https://github.com/gopro/labs/issues/67#issuecomment-1176479005",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
} On Jul 6, 2022 1:14 PM, David Newman ***@***.***> wrote:
You haven't explains why you want WiFi on, as it should not be if you want an extended runtimes. If you are externally powering, and auto uploading you should be this script: https://gopro.github.io/labs/control/dailytl/  This is more reliable, and the newer recommended solution.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/gopro/labs/issues/67#issuecomment-1176479005",
"url": "https://github.com/gopro/labs/issues/67#issuecomment-1176479005",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dnewman-gpsw** [comment]
I just confirmed, !U command works even if you the WiFi is disabled in the menu.

**Comment by logan012534** [comment]
Okay interesting. I appreciate the feedback very much. I will look into this further to see if I am doing something else to cause it not to transmit.On Jul 6, 2022 3:22 PM, David Newman ***@***.***> wrote:
I just confirmed, !U command works even if you the WiFi is disabled in the menu.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/gopro/labs/issues/67#issuecomment-1176588316",
"url": "https://github.com/gopro/labs/issues/67#issuecomment-1176588316",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by logan012534** [comment]
I ran into a new gremlin with the script: once I scanned the QR code on two of my four cameras, it would display the upcoming start time on the rear screen then go to sleep like normal, and then immediately wake itself back up, display the message about the firmware, display the message about the upcoming start time, and go to sleep. It was on a repeating cycle of turning itself on and off until I cancelled the timelapse completely. I took a video of this if that would be of any benefit in troubleshooting. One of the cameras stopped doing this, but the other one I could not get it to stop so I just left it.

**Comment by filipeg165** [comment]
Hello, just wanted to contribute to this issue. I just got 2 brand new GoPro 10s and was going to use them for a construction Timelapse as well.

I put the firmware on both, I used the daily upload one (the latest mentioned) and the camera wakes up 20 seconds before the start time, shows on the screen that it will start, but when it says 10 seconds left, it shuts off, the POWERING OFF message appears and it never wakes up again to start the Timelapse. Also, I noticed that the wireless comms is OFF as well when I turn it back on.

**Comment by dnewman-gpsw** [comment]
Please share the complete command you are trying, as that doesn't sound normal at all.

**Comment by filipeg165** [comment]
This is the command the code generator gives me (the time duration is just for testing):

!20:10NmTfWp.10!S!4440E!U!1R

On my second GoPro, it managed to take the Timelapse without shutting down, but still, the upload does not work, because the wireless comms are switched off as soon as the QR code is scanned by the camera.

**Comment by filipeg165** [comment]
Yes. this is the latest firmware, 1.46.70. I will try to mess around with the code and see if I can get different results on both cameras.

**Comment by filipeg165** [comment]
Hello again and thanks for the quick feedback!

I managed to get it to work on my second camera by simplifying the code a little, without setting the lens, the timelapse mode and putting an end time, instead of n seconds. I used the code below and it worked perfectly, it also uploaded to the cloud.

!23:20Np.60!S!23:30E!U!1R

My guess of the abnormal shutting down on the first camera is maybe a faulty firmware update, I will try to revert it back to normal, then apply the labs firmware and try again with this code that works.

**Comment by filipeg165** [comment]
I managed to get it to work once, after trying over 20 times. It took the timelapse and uploaded fine to the cloud.

I tried the same code again, after 10 seconds on the countdown to start, the camera powers off... This is happening on both cameras equally. Tried simplifying the code, !23:37N!S!600E!U!1R with only the start and end times, no luck. Every single time now, when the countdown to start comes up, 10 seconds later it says POWERING OFF and never continues.

**Comment by filipeg165** [comment]
Hello again, happy to report that the cameras have been on for 3 days now, going to the 4th day with everything working perfectly. Maybe the camera was waiting for a GPS signal or something like that in those 10 seconds of the countdown and didn't get it and turned itself off, I don't know, just a thought.
