### ISSUE TITLE
Feature Request: 16:9 ratio photos, or custom photo resolution

### ISSUE THREAD

**Issue by novaslip** [gopro/labs#69]
The hero10 uses by default 4:3 at his max sensor, maybe in the future it is possible to directly shot photos at ratio 16:9, or maybe able to change to a custom resolution? Thanks advance.

**Comment by dnewman-gpsw** [comment]
As images can be cropped later, what is the main advantage for this?

**Comment by novaslip** [comment]
> As images can be cropped later, what is the main advantage for this?

I do only use 16:9 photos for my work, it is exactly what am i doing now, but crop them it's not a solution for me as it requires time and i need the files directly as i shoot it.
Also with the preview at 4:3, even when i crop them i can't get the correct view distance as the ratio is different from 16:9.
It is possible to add this feature by the way? Or it's something that can't be done? I though switching to gopros camera was a good idea but i'm only facing problems.

**Comment by dnewman-gpsw** [comment]
Labs doesn't change capture modes, so this not likely to happen in camera.  However post tools can solve the aspect ratio problem in seconds.  With a tools like the free IrFanView you can batch a folder on GoPro images cropping them all to 16:9, and resizing if you need.  As your framing issue during capture, that can be addressed with a Sharpie ;), marking the 16:9 region, or more practice.
