### ISSUE TITLE
HERO12 clock drifts several seconds per day while running

### ISSUE THREAD

**Issue by DavidXenakis** [gopro/labs#694]
I'm having trouble keeping my two HERO12 clocks synchronized after syncing the timecode with the QR code. As described in [this Reddit post](https://www.reddit.com/r/gopro/comments/18uxnv0/timecode_synchronization_and_drift_on_gopro_hero12/), I have two GoPro HERO12 cameras with the latest firmware (I have tested both the latest Labs firmware and the latest official firmware). I synchronize each one with a QR code, leave each one running for a couple hours, then record a clap to test whether they are still in sync. Analyzing the footage in an editor shows that the sync has drifted >200ms apart. 

Clip alignment right after syncing with QR code
![image](https://github.com/gopro/labs/assets/3076080/c40d7e61-a31d-4af3-ab9d-7d5c3e0457cd)
Clip alignment 78 minutes after sync
![image](https://github.com/gopro/labs/assets/3076080/9b31388d-33eb-4524-8fa4-5945009a8b51)

Are HERO12s expected to keep time more accurately than what I'm experiencing? Could this be a case of faulty hardware?

**Comment by dnewman-gpsw** [comment]
This is not a Labs bug, so closing.  Please contact GoPro support to see if this is out of spec hardware, and if so get that camera replaced.
