### ISSUE TITLE
Mini 11 as a Dash Cam?

### ISSUE THREAD

**Issue by AGuetz** [gopro/labs#700]
Hello. I am new to this platform and have to admit feeling out of place as I am not as knowledgeable when it comes to tech as I can tell you all are. I just purchased the HERO11 Mini with the hopes that I can get it to behave more like a dash cam after watching a YouTube video from someone claiming to have successfully done so and his link sent me to GitHub and why I am reaching out. Is there anyone who has been able to do this on the 11 Mini and willing to help me? Thanking you in advance :)

**Comment by dnewman-gpsw** [comment]
Not an issue

**Comment by AGuetz** [comment]
So I followed the manual firmware steps, copied your QR code but doesn't work on my HERO11 Mini. I have my camera connected to its dedicated usb power source and it boots up but does not begin/stop recording upon car movement. Your video shows it working on your 11 mini so wondering if it could be something wrong with my camera and worth returning?
