### ISSUE TITLE
QR code generation for extra long picture time lapse under water

### ISSUE THREAD

**Issue by Jazz0915** [gopro/labs#71]
Hi GoPro community,

I am a researcher, and I would like to use the GoPro 8 with Labs to perform a Long-Term-Picture-Time-Lapse under water. Hence, I cannot use an external power supply but must rely on the internal battery. My aim is to shoot a picture time lapse between 4:30 am and 10:30 pm with an interval of 20 to 30 mins (shorter is better, but, if necessary, the interval can be longer) over five days with the lens set to normal and the camera powering off in between to save battery life. 
I tried to use the two time lapse QR-code generators on GitHub, but there is a problem with each: Using the “Very Long Time-lapses with Larger Intervals” generator (https://gopro.github.io/labs/control/longtimelapse/) the camera always switches to wide mode, no matter what was set before applying the QR code. However, the battery lasts a couple of days. Using the “Construction Time-lapses” generator (https://gopro.github.io/labs/control/construction/) the camera settings are fine, but the battery dies after about 20 h, even though the calculator gives an estimated runtime per charged battery of 6 days.

I have heard now that Labs is working best when using an external power supply, as it has reliability issues when using the internal battery only. Is that true? Is there a way to modify the “Very Long Time-lapses with Larger Intervals” QR-Code to set the lens to normal? Any other ideas or tips how I could approach my project?

Thanks a lot,
Jasmin

**Comment by dnewman-gpsw** [comment]
Just edit the script.  All of the github labs pages are just examples.  Find a co-worker that does some coding, any language and they will be able to help you out, if you don't follow what is next:

If you set the longtimelapse  page for 6 days you get this command: **!1386NQmPN!S!1R**
This is script
!1386NQ <- sleep approximately 1386 seconds then do nothing (N - nothing, Q - Quickly - the approximate part.)
mPN <- mode Photo Night 
!S <- Start
!1R <- In 1 second repeat.

So you want the camera to wake, set the photo mode, then set the lens, before taking a photo.  Note: you could just edit the preset on the camera for Night Photo to use Linear. 

the command for a Linear lens is fL
So the new script would be !1386NQmPNfL!S!1R

PS Normal is not a lens option.  There is Linear, which is a reprojection from for the wide-native lens curvature (near a stereographic lens projection.)

**Comment by dnewman-gpsw** [comment]
Labs is experimental, there a no guarantees this 6-day shoot will be reliable.  The fewer wakes and shutdowns the better.  Or you addition cameras for more insurance.  As for external power vs internal, there no advantage, other than you can only choose one, they can be issue mixing internal power with external and wake timers in Labs.
