### ISSUE TITLE
Feature Request: Min/Max Shutter Speed

### ISSUE THREAD

**Issue by p-masek** [gopro/labs#72]
It would be great if there would be way how to setup minimum and maximum shutter speed in same way how it is with ISO.

Scenario: moving between dark / bright conditions often cause that camera bright/dark up image too much. Solution could be setup limits how bright/dark image can be (considering ISO MAX would be on ISO 100). 
Yes, it can be achieved by locking-up Shutter speed and setup MAX ISO - but negative consequence is higher noise in dark conditions (as camera will increase ISO to MAX alowed value in dark conditions) but there is little/no difference if shutter speed is eg. 1/480s or 1/960s.

**Comment by dnewman-gpsw** [comment]
There is a crude solution  https://gopro.github.io/labs/control/maxshut/

This way you can set your longest exposure time (Shutter speed).  So you you can set ISO MAX to 100, and max shutter angle to 90 degrees (or 1/fps*4 , stock is 360 or 1/fps), now the camera will auto exposure as need, but will not use shutter speed/angle beyond your limits.  So you effectively set a minimum shutter speed.

**Comment by p-masek** [comment]
Thank you for suggestion @dnewman-gpsw . 
If I understand this corectly it will set limit for exposure only "from one way" - as you have mentioned - only longest possible exposure time... but there is no way how to set shortest exposure time, right?

**Comment by dnewman-gpsw** [comment]
Correct, there as more need for stablization reasons to limit long exposures, but not short ones.
