### ISSUE TITLE
Feature Request: Disable GP Labs splash screen

### ISSUE THREAD

**Issue by p-masek** [gopro/labs#73]
It would be great if there would be option to disable quite annoying overlay/splash screens related to GoPro Labs and activated features during startup. 
I think this firmware is used by experienced users, they usually knows that firmware is installed and also what features are enabled. Moreover - lot of users will continue use it permanently and such a "welcome screen" will become quite annoying after some time. Feature which would allow to disable/enable it on startup would be nice.

**Comment by dnewman-gpsw** [comment]
If you use the owner information, that is replaced with what ever text you like. See https://gopro.github.io/labs/control/owner/  you can even set a single space. The GoPro requirements is something is displayed so you know that the camera is modified.  If you want it to go away faster, use !MDSPL=10 (display for 10ms, it is the fastest supported.)

**Comment by p-masek** [comment]
Thank you for the suggestion. @dnewman-gpsw 
Single space works for second GP labs screen but it does not for first where are active modifications are listed. Maybe 10ms visibility change could help but I am not sure how to generate QR code for !MDSPL=10. I have tried it on GP pages but QR code remains the same (I have not found page where !MDSPL woyld be accepted)...

**Comment by dnewman-gpsw** [comment]
Any of the pages that have "Additional Commands:" will except the text input. Like here https://gopro.github.io/labs/control/custom/ Also any QR generator can be used the supports vanilla text.  e.g. https://www.qr-code-generator.com/

Here it is:
![image](https://user-images.githubusercontent.com/10856084/181050204-ff295562-cbc2-436c-8172-0bdd4375c354.png)

**Comment by p-masek** [comment]
Many thanks @dnewman-gpsw , now it is (almost) perfect.
