### ISSUE TITLE
Blown out highlights Hero 11/12 GoPro labs locked shutter

### ISSUE THREAD

**Issue by Yeefpv** [gopro/labs#732]
Hey guys, I have a question I’d like to ask. 

I’ve been playing around with GoPro labs the last couple months. I feel like I have it dialed in pretty well but the one thing that I seem to struggle with is blown out highlights in my footage when using a ND32 on the brightest of days. Before I installed labs I never had this problem. Seems like adjusting the logb curve and setting a wide gamut = more exposed highlights. I will mention I’m using 30fps, 60fps, locked shutter 1/60, 1/120, but still get blown out highlights when using a nd32. I understand setting the ev comp adjust the brightness of the highlights, but ev comp is only available while using auto shutter. So how do I preserve highlights when using a locked shutter? Let me know!

**Comment by dnewman-gpsw** [comment]
This is nothing to do with Labs. ND32 can be insufficient amount of ND for the brightest of days for a 180degree shutter. On a very sunny day, the camera can require 1/2000 of a second shutter at ISO 100. Snowy conditions even shorter.  With ND32 1/2000/32 is 1/62.5 so okay at 1/120, but struggling for headroom at 1/60. Invest in an ND64 filter.  EV compensation wouldn't help as the camera has no Iris control, so you can only modify ISO and shutter.  ISO is pegged at 100 and you're controlling shutter. Neither the log curve or the wide gamut effects exposure, however, the log curve will bias everything to look as if they're brighter. And if you have set up your NLE wrong to handle full range video data, it can look like clipping, so do check that out.

**Comment by dnewman-gpsw** [comment]
closing as expected behavior.
