### ISSUE TITLE
Featuere request: Exposure bracketing

### ISSUE THREAD

**Issue by p-masek** [gopro/labs#74]
Exposure bracketing is quite common feature on most (even non-professional) cameras but it is still missing on GoPro.
It would be nice if such a simple feature would be added at least via GP labs (ideally also for RAW format).

**Comment by dnewman-gpsw** [comment]
You can achieve this with scripting the current Labs firmware, also it is a little slow.  The idea of a bracketing is good, I would like to it implemented in the mainline firmware one day too.  But here is an example of a bracketing script you can use now:

mPNrcFx-6i1M1!1Sx-3i1M1!1Sx0i1M1!1S!x3i1M1!1Sx0e2i1M1!1SeA

mPNr - mode photo night raw
cF - color Flat, doesn't alter Raw, but makes the JPEG more useful by disabling tone mapping.
x-6 - EV comp -6
i1M1 - set ISO Min/Max to 100 (there is a bug in Labs Photos that the ISO is set after every EV change.)
!1S - shuttter press, after 1 second

Then it repeats for EV -3, 0, +3,  As we can't do higher EVs, the last exposure is a 2s shutter, the shortest long exposure supported. 
 
![image](https://user-images.githubusercontent.com/10856084/181059355-922ed047-71c4-4be8-94f4-4da3b8defeef.png)

**Comment by p-masek** [comment]
I have tried it and it works pretty nice... and also for RAW in case output is setup like that.
As you have mentioned - downside is that it is quite slow (handheld is impossible). I understand that with scripting it cannot be much faster but it is pitty that GP10 can do 3-25 frames in second in Burst mode and this power cannot be used in bracketting.
BTW I would say this photostacking is way to future - even basic phones use it to achieve better DR,lower noise and some (like iPhone) can produce also HDR RAWs (ProRaw format). Something like that would be great on GPs as well.
