### ISSUE TITLE
Gopro stuck in live mode

### ISSUE THREAD

**Issue by BearWithProject** [gopro/labs#745]
Hi, I was testing the gopro webcam feature on mac. I have the last November Update (Labs). The feature works but now i can't switch modes, nothing. I tried to remove battery, restart, manual update firmware, nothing works. The gorpo start in live mode and I can't access menu or other settings.

**Comment by BearWithProject** [comment]
I solved with a manual factory reset with txt file. Maybe there is something wrong with GoPro Labs firmware and Webcam mod app.

**Comment by dnewman-gpsw** [comment]
Labs doesn't modify Webcam, so it is unlikely connected. Happy to hear you found a solution.
