### ISSUE TITLE
Feature Request: Hero11 Photo Series with variable interval and duration

### ISSUE THREAD

**Issue by Archer4CA** [gopro/labs#758]
I would like to have an intervalometer for photos within the GoPro camera.  Similar to timewarp or timelapse, but I do not need the movie, only the series of photos at a discrete time.  I would like to take high resolution photos.  Purpose is to do aerial photography over a piece of property and then to download the photos.  The photos would then be photo stitched in a panorama using an external program.

Typically 0.5-5 sec between photos, for a duration of up to 30 minutes. Photos to have numbering in series.

**Comment by Archer4CA** [comment]
In TimeLapse I am able to set Linear, Format=Photo, Interval 0.5 sec, output as standard (.jpg only).  Changing to RAW (GPR) and JPG defaults lens to wide and interval of 5 sec min.  So it looks like I can do what I want, but only with .JPG images.

**Comment by dnewman-gpsw** [comment]
These feature all exist already in the standard camera.  However Linear Photo Raw doesn't exist as the lens is not Linear, so processing the image is not Raw.
