### ISSUE TITLE
Histogram in quik app too?

### ISSUE THREAD

**Issue by sanj3k** [gopro/labs#765]
Hi, i will also open a ticket on quik app folks but since without the labs fw the regular histogram is not available at all it somehow belongs here too. 

Please just tell me would it be possible at all? :D I mean in the quik app one has the preview like from back LCD. Are the position parameters really like on top and not communicated through/ to the app?

**Comment by dnewman-gpsw** [comment]
Nothing to do with Labs, the histogram would be computed from the preview stream, it would work on non-Labs cameras.
