### ISSUE TITLE
Spirit level (LEVL) does not appear to be working on Labs 2.10.70 (Hero12)

### ISSUE THREAD

**Issue by SgtTacooo** [gopro/labs#768]
Had LEVL working fine on Labs 2.00.70 on my Hero12 but since upgrading to Labs 2.10.70 it appears the spirit level isn't showing. Have restarted the GoPro, rescanned the QR code with both size 1 and size 9 (!MLEVL=1 and !MLEVL=9) but neither seem to show anything. Shame as it's one of my favourite features too.

**Comment by dnewman-gpsw** [comment]
Confirmed, and I have determined why.  2.20.70 is more efficient and faster.  It partly does this by disabling code not used.  Unfortunately the gyro filter was off, and LEVL used it. 

Workaround. >g1=A+1!1N!R    This will keep the gyro filter on, so LEVL works.

There is a new version for HERO12 coming soon-ish.  It will be fixed.

**Comment by dnewman-gpsw** [comment]
This was fixed in the 2.30.70 firmware.
