### ISSUE TITLE
Gopro

### ISSUE THREAD

**Issue by IsmagilTim** [gopro/labs#793]
Hello! I'm facing the same problem with my Mini 11 camera. It doesn't turn on after pressing the power button for 10 seconds, it doesn't respond to charging, and it also heats up. I've tried installing the update manually, but it didn't work. Could you please check the metadata of the latest file? What can I do in this situation?
DEVC 
  DVID 1
  DVNM Global Settings
  VERS 8, 2, 0
  FMWR H22.03.02.30.00
  LINF LSU2092302401511
  CINF -96, 90, -8, 99, 102, -84, -24, -4, -76, -16, 26, -76, 120, -24, -16, 53
  CASN C3491124708248
  MINF HERO11 Black Mini
  MUID 1677220512, -51860378, -1273302860, 904980600, 0, 0, 0, 0
  CMOD 12
  MTYP 0
  OREN U
  DZOM Y
  DZST 0
  SMTR N
  PRTN Y
  PTWB AUTO
  PTSH MED
  PTCL NATURAL
  EXPT AUTO
  PIMX 1600
  PIMN 100
  PTEV 0.0
  RATE .empty.
  SROT 13.0000
  EISE Y
  EISA HS EIS
  HCTL Off
  AUPT N
  APTO OFF
  AUDO AUTO
  BROD .empty.
  BRID 0
  PVUL F
  PRJT GPRO
  SOFF 0
  CLKS 2
  CDAT 0x0000000065CCCB49
  SCTM 0
  PRNA 10
  PRNU 0
  SCAP N
  CDTM 0
  DUST NO_LIMIT
  VRES 3840, 2160
  VFPS 60000, 1001
  HSGT OFF
  BITR STANDARD
  MMOD STEREO
  RAMP .empty.
  TZON 60
  CLKC 0
  DZMX 1.4000
  CTRL Pro
  PWPR PERFORMANCE
  ORDP Y
  CLDP Y
  PIMD MANUAL
DEVC 
  DVID FOVL
  DVNM Large FOV
  ABSC 0.0000
  ZFOV 95.5393
  VFOV L
  MXCF x1
  MAPX 1.0000
  MYCF y1
  MAPY 1.0000
  PYCF r0r1r2r3r4r5r6
  POLY 0.0000, 1.8151, 0.1035, -2.9413, 3.5951, -1.8582, 0.3529
  ZMPL 0.6061
  ARUW 1.7778
  ARWA 1.7778
DEVC 
  DVID HLMT
  DVNM Highlights

**Comment by dnewman-gpsw** [comment]
Please contract GoPro Support.  This is not a Labs FW issue, as you are running stock firmware. 

There is nothing unusual with the metadata.
