### ISSUE TITLE
Simple IMU triggers don't seem to repeat (i.e. !R) on GP12 (but do work in longer "compound" commands)

### ISSUE THREAD

**Issue by piersg** [gopro/labs#799]
I may have done something to cause this though, which I'll explain below, but first:

If I scan the default example QR code on [the documentation page](https://gopro.github.io/labs/control/imutrigger) (i.e. this command: `!SI6D1H5!R`) my new GP12 records once when moved, but after it stops recording, it doesn't return to the "IMU" display and does not record again if moved.

However, if I run this command: 

`mVr1080p25fW0te0cNsMv0dVoV0D4C0S1W0L02T240305171912oMBASE="EX_240305_BC1F_"!SI3D1H60!R`

it does repeatedly record (but, separate problem, it also sets the time again, which is undesirable).

I didn't try the more simple command until after I had run the above one quite a few times, so I don't know if that has somehow caused the non-repeats for the simple command. But I have tried power-cycling and removing the battery without effect.

**Comment by dnewman-gpsw** [comment]
I don't see the first error in a upcoming release (good news, the bug seems to be fixed already), but I there is a super simple workaround

```!SI6D1H5!1R```  (added the 1 to !1R)

It just need a small delay.  The reason the long command is work, it those extras commands are take a second or to to process.

**Comment by piersg** [comment]
Thanks that workaround seems to be working.

While we're talking ;-) is the `!timeRx` command documented in any more detail somewhere? Is 'x' just a char offset? From the end/from the beginning?

Ideally I'd like to run just the long command above but repeat only the IMU tigger (and not the clock set)

**Comment by dnewman-gpsw** [comment]
'x' is character offset from the beginning.

**Comment by dnewman-gpsw** [comment]
Closed with the new HERO12 Labs release.
