### ISSUE TITLE
Can a GoPro 8 Black read multiple QR code one after another ?

### ISSUE THREAD

**Issue by romall93** [gopro/labs#80]
Hi everyone,

My goal is to set up a GoPro 8 using QR control to record every hour (for a week) a time-lapse of 1 picture/2 sec for 15 minute 

So basically the camera would turn on automatically at for example 12:00 and record from 12:00 to 12:15. Then turn off.

Turn on at 13:00 and record from 13:00 to 13:15. Then turn off

And so on, until the battery is dead (the GoPro would be plug to an external battery and should last at least 7 days.)

Is that even possible ??

Thank you everyone for your precious help before I get lost for ever in the QR code universe !

Romain

**Comment by dnewman-gpsw** [comment]
Yes, all commands can be stacked.  A simple version of this command would be !S!900E!2700R    Start in the current default mode (which you would have previously set up, or add QR command,) record for 15 minute (i.e. !900E - End capture after 900 seconds), then repeat everything after 45 minutes.

**Comment by romall93** [comment]
Amazing thank you very much for your help ! it's super useful
