### ISSUE TITLE
Disable timestamp overlay on Hero 8 Black

### ISSUE THREAD

**Issue by jacobthaqvist** [gopro/labs#81]
Hi!

I have successfully added timestamp via labs/QR code procedure. Now I don't need it anymore and want to disable overlays all together. How do I do this? I can temporarily remove the timestamp by choosing the "Erase" QR code here https://gopro.github.io/labs/control/overlays/ 
But the overlay reappears when restarting the camera.

Any help appreciated!

**Comment by dnewman-gpsw** [comment]
To fully disable overlays use: 
![image](https://user-images.githubusercontent.com/10856084/189952406-5dd04352-9292-4a9a-96a2-1f15d7f96020.png)
