### ISSUE TITLE
GoPro Mod HDMI clean out by default on start up

### ISSUE THREAD

**Issue by marksteven** [gopro/labs#83]
Would be nice when using Media Mod with HDMI plugged in that the back screen remains working so you can see what you are pointing at.
Very hard to "click" across 2 screens to hit "eye" to get clean HDMI out.
Even better if you could setup HDMI out straight away on power up without splash screen.
Also great to remove "battery " monitor by default in HDMI output.
No GoPro/Lab QR codes seem to work to correct this issue for me.

**Comment by beyondcr** [comment]
I was also struggling with this problem and stumbled across a twitter post that lead me to https://gopro.github.io/labs/control/extensions/ essentially you want to create a qr code you can do this with the editor on the bottom of their page, you want Metadata Four CC to be HDMI then the metadata value to be 1 also check the box to make Premanent (gopro please fix spelling on your page), then scan the qr code with your gopro10 and now you should have clean hdmi. I believe the qr settings are stored on the sd card but this is all new to me, good luck!

**Comment by dnewman-gpsw** [comment]
Correct.  From https://gopro.github.io/labs/control/extensions/ 
![image](https://user-images.githubusercontent.com/10856084/189951953-29691eac-76fc-4cd1-a51a-ba4b4597bf04.png)
