### ISSUE TITLE
Hindsight over 15min and automatically end of videos not working together

### ISSUE THREAD

**Issue by simsche** [gopro/labs#836]
Hi there, 

I know I can change the timeout to about 1440min in total of the hindsight. 
but if I want to have 15secs bevor an trigger and let’s say 15s after (so n automatic stop of the video), that’s is only working within the first 15 mins fine.
After that it has several bugs like abortion after 2 secs after the trigger for example.

Is it known?

regards
Simon

**Comment by dnewman-gpsw** [comment]
What camera model?  What command to auto stop?   Please share complete step to reproduce this error.

**Comment by simsche** [comment]
Your right. I am sorry.

- GoPro Hero 12
- Labs v2.20.70, March 2024

To reproduce it: 
- Scan the QR Code for "HSTO" duration for example 60 or 1440 min (timeout of the hindsight)
- set the "duration capture time" to 15s
- set the hindsight time to 15s
- start the hindsight 
- do not touch the Gopro for 20 min
- press record

Now if you press record you will get a 30s Video (15s bevor the trigger and 15s after the trigger)
But somehow, it the Gopro will not be triggered over 15 mins and you press record for example after 30mins or so, you get very often 32s videos with 30 sec bevor the trigger. Or just a 15s Video or sometimes even nothing.

**Comment by dnewman-gpsw** [comment]
I have found it works fine.  I waited 30 minutes, shooting a clock, and got 15s before and 15s after each time.  I ran the test twice.
