### ISSUE TITLE
Base filename page appears to be broken, and hero 12 doesn't work with new filenames

### ISSUE THREAD

**Issue by mod6890325** [gopro/labs#839]
It seems that https://gopro.github.io/labs/control/basename/ doesn't format dates/times correctly.

For the provided example, "CamA-[yyyymmddHHMMSS]-" the preview shows:

> Your filenames will be in the format: CamA-[yyyymmddHHMMSS]-GH010206.MP4 and CamA-[yyyymmddHHMMSS]-GOPR0206.JPG

and when I applied this to my hero 12 anyway (latest firmware v2.20.70, March 2024), I couldn't download recorded video to phone via Quick app - the app didn't see it.

Seems like going with the Labs firmware is a really bad idea. Why even bother?

**Comment by dnewman-gpsw** [comment]
On the page you linked it says:

```
WARNING: On camera playback, USB transfer, the GoPro Quik app and GoPro cloud services will not support these renamed files. This is for direct SD card transfers only. In addition, the camera’s automatic file repair will not know to repair these files (see Manual File Recovery below), so only use this feature if you aren’t putting cameras in extreme danger (where power could be randomly disconnected.)
```

So it is working as designed and documented. This is feature is for users directly offloading MP4 to editing workstations, they don't use Quik.

> Seems like going with the Labs firmware is a really bad idea. Why even bother?

Labs is for advanced users experimenting and pushing the boundaries of what a GoPro can do.  Most features Labs are compatible with Quik, but is you not into experimenting, maybe you shouldn't be using Labs.

**Comment by mod6890325** [comment]
Yeah, what do I expect from a 12-th generation product.... a sensible file-naming convention out of the box? Who am I kidding :))))))))))

**Comment by dnewman-gpsw** [comment]
The standard file naming complies with the DCIM specifications.  Which is 8.3.  But I too would prefer the longer, fancier naming.  As this is not about Labs, I'll close the ticket
