### ISSUE TITLE
Bluetooth issues with HERO12 Black - v2.20.70

### ISSUE THREAD

**Issue by lsmith77** [gopro/labs#847]
I just upgraded to v2.20.70 and since then I had several issues using my Hero12 Black with Media and Max Mods installed using the latest Quik app version on my iPhone 13 Mini and iPad Pro 11” all on the most recent iOS/iPadOS versions.

1) Initially it would always have a red warning icon which I guess says that no battery is installed (despite running on battery)

After a 10s press on the mode button to restart the camera this was fixed

2) I then had issues connecting via bluetooth (which worked previously) on both my iPad and iPhone. It would just not be able to connect.

On the iPhone it was not able to connect at all and the iPad I got:
![IMG_0998](https://github.com/gopro/labs/assets/300279/2f969298-14f6-4e5a-ad9a-1f26b7084b84)

I have removed the bluetooth pairing on both devices and did another 10s restart. Now I managed to get it working on the iPad after several tries. On the iPhone I am getting:
![IMG_1872](https://github.com/gopro/labs/assets/300279/d90ff480-36a7-44e3-947e-bd1bb37afd37)

**Comment by dnewman-gpsw** [comment]
These are not Labs modified features, Labs doesn't alter BLE or WiFi in any way.  Try a Factory Reset, that you get you back to normal under 2.20.70.

**Comment by lsmith77** [comment]
but if labs doesn’t modify this, then what is the point in a factory reset?

**Comment by dnewman-gpsw** [comment]
All manual firmware updates can produce a need for a factory reset.  When camera behave weird, do a factory reset.

**Comment by lsmith77** [comment]
ah ok understood.

I have now restarted my iPhone and then I was able to connect and all is well.

Thank you for the fast responses though and I learned something for future issues.
