### ISSUE TITLE
Rolling Shutter Correction Issue GP 12

### ISSUE THREAD

**Issue by przfpv** [gopro/labs#864]
5.3k on 60fps footage has horrible rolling shutter correction beyond saving. All my other footage has been perfectly fine up until these couple video recordings. All my footage afterwards was perfect on different settings as well. Attached is a link with a sample clip. https://drive.google.com/file/d/1kw7_4ewYIgUAoecxXogC7_rsTzymLH5e/view?usp=drivesdk

**Comment by dnewman-gpsw** [comment]
Is this a GoPro Labs question?  What Labs setting caused the issue?

**Comment by przfpv** [comment]
Just seeing that this particular gopro is not in labs firmware (version 2.10).

**Comment by dnewman-gpsw** [comment]
Sorry not my area, try a factory reset, if that fails try GoPro Support as maybe your camera hardware has failed.
