### ISSUE TITLE
GoPro Hero 9 Not Showing USB Connection

### ISSUE THREAD

**Issue by JinmingM** [gopro/labs#870]
I am experiencing an issue with my GoPro Hero 9 where it does not show the USB connection on my computer, despite having updated to the latest firmware. I have confirmed that both the USB cable and computer USB port are functioning correctly by testing them with a colleague's GoPro Hero 9, which connected without any issues.

**Comment by dnewman-gpsw** [comment]
How is this a Labs issue?  Have you request MTP from the USB connections menu?  Menu->Connections->USB Connection->MTP

**Comment by dnewman-gpsw** [comment]
Not related to Labs.
