### ISSUE TITLE
Hero11 Firmware

### ISSUE THREAD

**Issue by beyondcr** [gopro/labs#88]
Where can I find the Labs firmware for the Hero11?

**Comment by dnewman-gpsw** [comment]
In future moving this type of question to https://github.com/gopro/labs/discussions

All Labs firmware is available within gopro.com/labs

**Comment by fxstein** [comment]
I have also added labs firmware support (HERO 8-11) to GoProX today:

https://github.com/fxstein/GoProX

With that, you can simply run

```goprox --firmware labs```

to install the latest firmware for your camera model onto the current sdcard. It auto detects the camera model from the card and will check against the latest available firmware.
