### ISSUE TITLE
Info labels for min and max shutter speed are reversed in the app

### ISSUE THREAD

**Issue by dutchct** [gopro/labs#893]
The labels in the app seem to do the opposite of what you'd expect.

**Comment by dnewman-gpsw** [comment]
They aren't reversed.  They are in 1/x time format.  

EXPX=  maXimum shutter time.
EXPN= miNimum shutter time.

e.g. 
EXPX=48
EXPN=192

They feel inverted as it seems like maximum shouldn't be less than the minimum.  But if you read the print, these are shutter times presented to 1/x format.  So the above sets 1/48 as maximum which is greater than 1/192 as the minimum.

**Comment by dutchct** [comment]
In your comment you’re using the word “time”. In the app, the word “speed” is used. 

If you feed example look up a camera’s max shutter speed it’ll be 1/8000. 

https://www.google.com/search?q=a6700+max+shutter+speed

**Comment by dnewman-gpsw** [comment]
shutter time and shutter speed are same thing.  These controls use 1/x formatting.

**Comment by dutchct** [comment]
https://www.cambridgeincolour.com/tutorials/camera-exposure.htm

“The shutter speed specifically refers to how long this light is permitted to enter the camera. "Shutter speed" and "exposure time" refer to the same concept, where a faster shutter speed means a shorter exposure time.”

https://en.wikipedia.org/wiki/Shutter_speed

“Short exposure times are sometimes called "fast", and long exposure times "slow".“

Please don’t think I’m trying to jerk you around. I personally found the wording in the app unintuitive. English is an odd language, but i think the majority of us think this way when using time and speed in relation to shutters in cameras.

**Comment by dnewman-gpsw** [comment]
Yes I understand, I just think this is pedantic. These control are presented 1/x.

**Comment by dutchct** [comment]
Maybe ask a ux/ui designer at gopro and see what they think?

Anyhow, thanks for your work on labs. Big reason I’m staying on gopro.

**Comment by dnewman-gpsw** [comment]
Labs doesn't have UX, and QRControl is not an official GoPro App.  If you want to improve the documentation within https://gopro.github.io/labs/control/extensions/, users submissions are welcome, and many do.

**Comment by dnewman-gpsw** [comment]
Closing as an really a Labs firmware issue.
