### ISSUE TITLE
Go Pro Hero 12 Time stamp overlay

### ISSUE THREAD

**Issue by cat3333333333** [gopro/labs#896]
Trying to add the timestamp overlay https://gopro.github.io/labs/control/overlays/ with the current video settings at 16:9 aspect Ratio, 4K, Frame rate 30, Lens superView, HyperSmooth off. We have also tried other framerates and different settings. 

Downloaded the Go pro labs firmware and loaded it onto the camera.
After scanning the QR code with the camera and accepts the QR code and does not display the code. What else needs to happen to display the overlay on the camera.

**Comment by dnewman-gpsw** [comment]
Try again with 4Kp30 8-bit.  It works fine with Superview 4K 30, so guessing you were in 8-bit.
![image](https://github.com/gopro/labs/assets/10856084/26b3a34d-0a5d-4bf6-9800-1a57dbefb00a)

**Comment by cat3333333333** [comment]
Tried this as well in 8-bit, should I be in 10-bit instead?

**Comment by dnewman-gpsw** [comment]
You have look at the full resolution media, it is not within the LRV or on in the Quik preview. Only within the MP4.

**Comment by cat3333333333** [comment]
Ok it shows up on the MP4 file. This should be clearly defined in the instructions.
