### ISSUE TITLE
Boost mode in Hypersmooth

### ISSUE THREAD

**Issue by jacekmusial** [gopro/labs#9]
Hi there!

Please consider adding a Boost option to Hypersmooth.
I am aware of the fact that Boost is not applicable to every mode thus I am happy to help in any way I can with the PR.

![image](https://user-images.githubusercontent.com/7474972/87863096-c0ab2200-c957-11ea-944d-a505bc78a5ca.png)

Thanks in advance :)

**Comment by jacekmusial** [comment]
@lbrownell-gpsw @dnewman-gpsw 🖥

**Comment by dnewman-gpsw** [comment]
It is not a web page UX issue, there are currently no QR commands to describe the different Hypersmooth states.   This is the result of the first hackathon QR Code controller was built before there was more Hypersmooth modes.  It will need to be fixed in camera.
