### ISSUE TITLE
Hero 8 black cutting off and back on

### ISSUE THREAD

**Issue by ConcreteHeroes** [gopro/labs#904]
So for some time now one of my hero 8 black cameras will cut off and back on randomly. I have swapped sd cards, tried different batteries, uninstalled labs, and factory reset the camera. Yet the problem persist. I've tried several of the methods I found on forums and on YT for correcting the issue, and none have worked. I can use any of the sd cards, batteries, etc. on my other labs enabled hero 8 black without issue. So what are my options for getting this fixed before the camera bricks itself, because that's what I belive will happen next.

**Comment by dnewman-gpsw** [comment]
Sounds like a hardware failure or damaged unit. Seems you will need to replace that camera.
