### ISSUE TITLE
Hero 12 labs firmware v2.20.70

### ISSUE THREAD

**Issue by BadSide84** [gopro/labs#914]
I get some issue on connecting the gopro to the quick app. After powering on the camera there is no connection to the app like other camera hero 11-10-9

Is that normal? Is that a knowed issue?

Thanks

**Comment by dnewman-gpsw** [comment]
Did you turn the WiFi on?  Many Labs commands will turn it off.

**Comment by BadSide84** [comment]
Of course is on

**Comment by dnewman-gpsw** [comment]
Not a known issue.  That firmware has been out a while. Plus I just retested, and all is working. Try a !FRESET to see if a factory reset clears things up.

**Comment by dnewman-gpsw** [comment]
Or just !WRESET

**Comment by BadSide84** [comment]
Ok when I can I try and I'll keep you updated

**Comment by BadSide84** [comment]
David

Tried to reset and doesn't work.

I noticed that when the GoPro doesn't get connection with the quick app the option of pairing is like this picture

![image](https://github.com/gopro/labs/assets/16736895/2e203302-6506-4a1e-91c0-e52477d35ae4)

When is working is like this

![image](https://github.com/gopro/labs/assets/16736895/ed8f3dc9-e554-41d7-a144-f8e79568d047)

Then when is connected is like this

![image](https://github.com/gopro/labs/assets/16736895/ed1171b0-0575-48df-86a5-ae45d7fc27af)

**Comment by BadSide84** [comment]
David

I found a trick to make the connection working

Normally when you power cycle the first time the GoPro doesn't work with the Bluetooth but if I try to power off and wait that the GoPro turn off, then I make new power cycle the second time the pairing with GoPro Quick app working fine
