### ISSUE TITLE
Labs Install Help on Hero 11

### ISSUE THREAD

**Issue by overossm** [gopro/labs#920]
### Discussed in https://github.com/gopro/labs/discussions/919

<div type='discussions-op-text'>

<sup>Originally posted by **overossm** May 18, 2024</sup>
Hello! I installed the GoPro labs firmware on the micro SD card and followed the instructions to insert it into the GoPro camera while it is turned off and then turn it on. 

The instructions said the camera would turn on and off multiple times, and a checkmark would appear. However, it did not turn on and off, and no check mark appeared. 

I verified that the firmware is installed on the SD card, but I haven't had any luck getting a check mark or any sort of verification that the camera is recognizing it. 

Any advice? 

I appreciate any help you can provide.</div>

**Comment by dnewman-gpsw** [comment]
Duplicate post

**Comment by dnewman-gpsw** [comment]
Same as discussions post
