### ISSUE TITLE
GoPro Hero 9 - USB Power Trigger - recording does not start

### ISSUE THREAD

**Issue by jensMF** [gopro/labs#93]
Hi,

I have a GoPro Hero 9 with labs firmware v1.72.70 | June 2022.
I would like to use USB Power Trigger to start recording when power is plugged in.
But with both of these commands `!uN!S!u10E!R`, `!uS!u10E!R` the cam turns on but never starts recording.

What am I doing wrong?

Thanks in advance for any help.

**Comment by dnewman-gpsw** [comment]
Future use https://github.com/gopro/labs/discussions for this no bug (with web pages) question.

I have no idea.  USB Power trigger is not great, a very early hack that hasn't been enhance over the years, but it might be the best available for HERO9 (using !MWAKE=2 is the newish version for later models.) But the fact that it wakes but doesn't record is weird.  Try !uNmV!1S!u10E!R

**Comment by jensMF** [comment]
> Future use https://github.com/gopro/labs/discussions for this no bug (with web pages) question.

Sorry, I thought this would be an issue.
Doesn't work with `!uNmV!1S!u10E!R` either. Maybe another labs feature I use blocks this? I have overlays activated, I have set the owner and when I power on the cam it says: Features activated: SYNC, ZONE, BRNO, BURN

**Comment by dnewman-gpsw** [comment]
They shouldn't.  There is nothing wrong with the command.  Post on discussions, maybe some other users have ideas for you.
