### ISSUE TITLE
Time code not working in 120Hz on Hero 7

### ISSUE THREAD

**Issue by TAOLiyong** [gopro/labs#939]
I want to attach a timecode feature to multiple GoPro Hero 7 cameras. It works at 60Hz but doesn't function at 120Hz. the version is HERO7 Black- v1.90.71, January 2021.

**Comment by dnewman-gpsw** [comment]
There will be no more updates HERO7 Labs, so you will need to work within Labs features that are there.

**Comment by TAOLiyong** [comment]
Understand. Thank you for replying to me quickly.
