### ISSUE TITLE
timelapse error

### ISSUE THREAD

**Issue by dronevisionbtm** [gopro/labs#940]
Have any of you experienced that the camera stops taking pictures and will start again after the next 24 hours?

Gopro 12 v2.20
githun v 2.20.70

Do I have to reset when the timelapse schedule changes?
![A518B1A3-D824-4D7E-8529-F29C4A0CCF1B](https://github.com/gopro/labs/assets/161919475/17a065ee-296e-485a-9063-d5fd87c5ca82)

**Comment by dnewman-gpsw** [comment]
Yes it can happen, but it is very rare.   Please share your command to see if it can be improved.

> Do I have to reset when the timelapse schedule changes?

I don't understand this question.

**Comment by dronevisionbtm** [comment]
> Yes it can happen, but it is very rare. Please share your command to see if it can be improved.
> 
> > Do I have to reset when the timelapse schedule changes?
> 
> I don't understand this question.

![F7FF9434-A66C-4E46-9380-94568DDE31A9](https://github.com/gopro/labs/assets/161919475/981a7b03-e154-4f4f-ac80-d7ca96e47e75)

i use this command, and for second question i mean

Do I need to reset my camera if I want to change the commands?

**Comment by dnewman-gpsw** [comment]
No need to reset the camera.  

I don't see any issues with the command.  If you still had the logs from May 25, that might help. Logs are in MISC/qrlog.txt and MISC/qrlog.bak  See it there are any dates from May 25 (I expect not.)
