### ISSUE TITLE
 2 GoPro 11 mini after the last labs update no work

### ISSUE THREAD

**Issue by Geotrippp** [gopro/labs#946]
1 gopro - keeps rebooting, 
2 GoPro  - gets hot when charging without turning it on

**Comment by dnewman-gpsw** [comment]
Hold done the power button for 10+ seconds for the full reboot. Reinstall FW.

**Comment by Geotrippp** [comment]
Reinstallation doesn't help

**Comment by Geotrippp** [comment]
10 sec too, the second GoPro doesn’t turn on at all, it just gets warm when charging

**Comment by dnewman-gpsw** [comment]
You will need to contact support for returns.  

As for Labs updates, this is the same process a regular firmware update, so this is not knowns to Labs. Is there anything you can tell about these two cameras that might have made them different?  Where they both running stock 2.50.00 before the update?

**Comment by Geotrippp** [comment]
the first camera worked before on the previous firmware, the second one is new out of the box

**Comment by Geotrippp** [comment]
If I am now in the country of Georgia, but there are no receipts and I bought them in other countries, where should I go for a replacement?

**Comment by dnewman-gpsw** [comment]
I don't know how support handles this situation, but I sure they have procedures. I'm also looking into any recovery operations that might work in the field. I never had to do this for a Mini, which why this is so puzzling that you had two failures.

**Comment by dnewman-gpsw** [comment]
Just in case you haven't tried: hold hold the shutter and power together for 3s for a factory reset.

**Comment by Geotrippp** [comment]
in question 651, was there a different story with the restart?

**Comment by dnewman-gpsw** [comment]
That is the recovery procedure I'm investigating.  It doesn't seem to work so far. Also that use bricked his camera with a bad command, you did do that, so this scenario is slightly different.
