### ISSUE TITLE
EXPS and HIST cause reboot loop on gopro 11 mini V2.50.71

### ISSUE THREAD

**Issue by mrdogeman1** [gopro/labs#954]
After accidentally updating to normal firmware I wanted to switch back to labs, so I got the latest version V2.50.71
When I tried to scan my usual QR (wich contain the HIST and EXPS commands) it froze, and then rebooted and froze after the labs message again and again. Exiting this loop was quite difficult, I tried holding the buttons for a long time, formatting the SD card among a few other things but none of that got stopped the loop from happening as soon as I powered on again.

To finally stop this reboot loop a had to do a sequence of a few actions: 

1. Hold the power button as soon as it powered on to turn it off manually before it crashed, so it powered down the "correct way"
2. Hold the power button to enter bluetooth pairing mode.
3. Quickly try to scan the reset QR code (!RESET)

After this I could use the gopro again, until I scanned a qr with HIST or EXPS. The loop would start again then.

I tried quite a few other metadata commands, but so far only these two caused the loop.
Now I've downgraded to V2.50.70 and now HIST and EXPS work fine again, so I'm pretty sure this is a bug in the latest version.

**Comment by dnewman-gpsw** [comment]
I have confirmed HIST and EXPS are broken, which is weird, as no code related changes. These are the only two related to the display, looking into that. However you can get out of the loop by ejecting the SD card (it is trying to re-run the script that it last used, which was crashing.)

**Comment by mrdogeman1** [comment]
> However you can get out of the loop by ejecting the SD card (it is trying to re-run the script that it last used, which was crashing.)

Oh that didn't work for me. The loop would continue even without an SD card.

**Comment by dnewman-gpsw** [comment]
Yes, if you had set them permanent, of course.

But I found the issue. Try the corrected build: https://www.dropbox.com/scl/fi/jjkajk5eg5vmg18ggrljk/HERO11MiniLabs025071b.zip?rlkey=r225gusrzd9985kp1xij27q4z&dl=1

**Comment by dnewman-gpsw** [comment]
Have you tried this?

**Comment by RikshaDriver** [comment]
I experienced this same issue today during a family outing.

Had to do a complete factory reset twice and get off GoPro Labs QR Codes to do any recording.

A preliminary test shows that this release seems to work with the QR codes now.
