### ISSUE TITLE
BITL 6 and above not working on gopro12

### ISSUE THREAD

**Issue by draugael** [gopro/labs#955]
Using 6000 kbit/s and higher causes immediately a stream crash and when I try to restart the setting are back to 5000 kbit/s.
Also the BITL setting is not always accepted.

My setup:

-     GoPro Hero 12 Black, Labs v2.20.70
-     Wifi6 router
-     monaserver 2 on the same network

**Comment by dnewman-gpsw** [comment]
It is working here, but with many limitations.

![image](https://github.com/gopro/labs/assets/10856084/da5816ae-03b3-4925-bbeb-8a16c574d23b)

I found it would crash with network error, or crash the camera, if I have QRDR enabled or overlays enabled, or any feature that requires more processing per frame (maybe motion detection.)  It seem Labs Livestream is still very fragile.

**Comment by draugael** [comment]
I'll retry tomorrow maybe I'll have better luck. Is there a way to get logs to help me (and maybe you) to solve this issue ?

**Comment by dnewman-gpsw** [comment]
The issue happening outside of Labs code, Labs logs will not tell us much.
