### ISSUE TITLE
Delayed action, camera not waking up.

### ISSUE THREAD

**Issue by aske2002** [gopro/labs#96]
We are doing a study of fish, using 15 hero 9's and 10 hero 7's. All with labs firmware.

For this we are using two QR-codes, one to set the framerate, time, etc, and one to start a delayed action loop. Eg.

Command: mVr4p60fW0oT220929011327 (set resolution, time and framerate)
Turn the camera on and off
Command: !1680N!S!120E!R

We deploy all the cameras, and check the cameras every day, to change batteries and sd-card, and then restart the delayed actions loop.

When the second QR-code is scanned, the camera says "Start time HH:MM:MS:MS (28 mins), press the button to cancel", and then turns off. This is expected behavior. The problem comes when the camera has to turn on again. Some of the cameras will turn on and run the loop perfectly fine, but about 50% won't even turn on the first time. This issue mostly seems to be camera specific, but also random at times. It mostly occurs for the Hero 9's, and sometimes for the Hero 7's. Sometimes the cameras will record a few videos, before just stopping. (Battery is still above 50%). We are submerging the cameras in the water, but the temperature is about 18 degrees Celsius, so that shouldn't be a problem with the batteries.

We've tried all kinds of different stuff to fix the issue, like reinstalling labs firmware, factory resets, doing things in a different order, filming a short video manually, formatting sd-cards, and more, but we can't seem to find any solution. Below is a part of the qrlog.txt from one of the faulty cameras, where it didn't record.

[2056-09-30 18:17:14] Read QR:mVr4p60fW0oT220929001934
[2022-09-29 00:19:38] Shutdown:inprogress
[2022-09-29 00:19:47] Labs:Main Start
[2022-09-29 00:19:47] Labs:Initialize
[2022-09-29 00:19:51] Read QR:!1680N!S!120E!R
[2022-09-29 00:19:57] Shutdown and Sleep:1560 seconds (28 minutes)
[2022-09-29 00:19:58] shutdown:rtc wake scheduled
[2022-09-29 01:10:13] Labs:Main Start
[2022-09-29 01:10:13] Labs:Initialize

As you can see it did not wake up, I ended up turning it on manually, it gave me a message saying it will turn on in 23.9 hours, which is the scheduled time + 24 hrs.

Any help is appreciated very much, as this issue is very hurtful for the study.

Thank you!

**Comment by dnewman-gpsw** [comment]
This is the discussing, is it not a bug report for the Labs web pages.
