### ISSUE TITLE
10-bit color for timewarp? 

### ISSUE THREAD

**Issue by dhicks** [gopro/labs#963]
I stumbled across GoPro Labs yesterday when I was trying to find a way to enable 10-bit color for timewarps.  I'm not totally certain I understand what I'm doing, but [this code](https://gopro.github.io/labs/control/set/?cmd=td1) does switch video into 10-bit mode.  However, it doesn't seem to have any effect on timewarps, i.e.: 

1. Switch to a timewarp preset
2. Show the same QR code to the GoPro; it displays the "QR code w/ checkmark" symbol
3. Take a short video
4. Open it in QuickTime on my Mac
5. Info panel indicates a bit depth of 8 rather than 10

Is there some way to configure timewarps to use 10-bit color?

**Comment by dnewman-gpsw** [comment]
There is currently no 10-bit support for Timewarp, or any of the timelapse modes.  The 10-bit control only applies to video captured within the video presets.
