### ISSUE TITLE
Feature Request: Standard Settings through a configfile

### ISSUE THREAD

**Issue by mohs8421** [gopro/labs#965]
My most common use-case for the cam is as a dash-cam for bike ride safety purposes.
For that I currently have to activate the overlay through a qr-code, and I would also like to use the IMU-Trigger feature in case of an accident, where I cannot immediately trigger the hindsight-recording.

So to avoid having to scan several codes every time I want to go, I would like to place one file on the sd-card to automatically have everything set up.

**Comment by dnewman-gpsw** [comment]
This is an existing feature, look up BOOT commands.

**Comment by mohs8421** [comment]
hm, ok, I tried it now, it does something, but the result is not what I had in mind.
The command I transmitted:
!BOOT="!Ldash"!SAVEdash="g1oMLFIN=0oMBRNO=20oMBURN="(0,30)[BRHH:MM:SSaa yyyy-mm-dd ]"!SI1H30!R!hS2"
I assume the nesting " is a problem here

**Comment by mohs8421** [comment]
ok, after that attempt, I took the sdcard into my laptop and manually edited the file that was generated.
There I removed the extra " around everything and tried it again. After that, the IMU-Trigger as well as the Burn was active, only thing missing was to start hindsight, but that's easy enough.
