### ISSUE TITLE
GoPro Hero 11 Motion Detection

### ISSUE THREAD

**Issue by JohnCash0018** [gopro/labs#97]
I have installed the GoPro Labs beta software on my Hero 11.  I have read the white papers and watched videos on how to setup Motion Detection with QRControl.  After several hours of troubleshooting I have concluded this feature does NOT work on the Hero 11.  Can you please advise as to how I can resolve this issue?

Thank you

**Comment by dnewman-gpsw** [comment]
in discussion forum
