### ISSUE TITLE
gopro 11 black mini Timestamp issue

### ISSUE THREAD

**Issue by jacobchoi77** [gopro/labs#976]
Hello. My name is Jacob and I live in Korea. 
I purchased a gopro 11 black mini. Timestamp function is used for black box purposes.
I tried to activate it through Gopro labs.
But it didn't work, so I contacted the Go Pro dealer in Korea, inquired about the function, and tried again. 
I tried it, but it didn't work out.
The seller contacted GoPro headquarters and was told that the Timestamp function is not supported for this model.
The seller told GoPro Labs that the availability of the Timestamp function for the model is limited.
They say returns are not possible. If it is not supported, shouldn't it be expressed as No?
It would be understandable if it was set to No, but since it is not, I am requesting a return from GoPro.

**Comment by dnewman-gpsw** [comment]
Labs features are not part of the camera, they not listed or offered in any official documentation.  GoPro Labs is for experimental extensions, that may not on work on each camera model, no guarantees, that is why it is free.  Labs features are not a basis for a camera return. They are just a fun addition for user experimentation. 

Maybe I can help you with the function you want to use.  What is a timestamp function?  Can you please share the QR code(s) you are attempting to use with the camera?  Are you talking about overlays or timecode?

**Comment by jacobchoi77** [comment]
Hi~ I'm Jacob.

=>  They are just a fun addition for user experimentation.

I think you're right. It was my fault for buying the wrong product and
trying to use it as a black box.
I feel aggrieved towards GoPro for no reason and look back at myself for
trying to get a refund.


=> Maybe I can help you with the function you want to use.

I don't know if it's possible, but I would appreciate it if you could try.
If it doesn't work, I'll have to sell it used.

The function I was trying to enable in GoPro Labs is the function below.
[image: image.png]

Current status of my Black Mini 11 is...
Overlay activated when gopro labs firmware update? The message error = 10
appears and passes.

When I scan the qrcode for the above function, a qr icon and a check icon
appear and the system stops.
Some thing like this
[image: ddddd.jpg]

above appears even if I do this,,
1. factory reset (in device)
2. sd clear (in device)
3. 11 mini firmware update (
https://gopro.com/en/us/support/hero11-black-mini-product-update/windows)
4. go pro labs firmware update (https://gopro.github.io/labs/)

Thanks. David Newman.

**Comment by dnewman-gpsw** [comment]
It works in the limited way documented.  This is from a HERO11 Mini with Labs firmware 2.50.71, shot a few minutes ago.
![image](https://github.com/gopro/labs/assets/10856084/9def99b7-d043-41d9-8dd2-bdac319ea1e1)

Try this code to test, it will switch the camera to 1080p50 (one of the limited modes that overlays work,  best is 16:9 4k/24/25/30), it will enable the overlays, then recorded a short 5-6 video.  
![image](https://github.com/gopro/labs/assets/10856084/7a98cbec-10a2-4acb-850f-2209d0b0af31)

**Comment by jacobchoi77** [comment]
If you look at the app without downloading it, the time/date does not
appear.
You can see it if you download it. When I tried it before, I didn't
download it and watch it.
So maybe I couldn't confirm it.
Anyway, the time/date comes out fine. Thanks to you, I think it went well.
Thank you, David.

**Comment by dnewman-gpsw** [comment]
Correct, it is not in the low resolution preview, only in the full resolution file.
