### ISSUE TITLE
gopro 12 daily longterm timelapse error

### ISSUE THREAD

**Issue by dronevisionbtm** [gopro/labs#977]
@dnewman-gpsw please solve my problem
Im using gopro 12 for my project, my gopro always turn off for 24 hour

this my setting  for gopro
![WhatsApp Image 2024-07-05 at 16 22 35](https://github.com/gopro/labs/assets/161919475/5ebdba85-cc8d-47e5-957a-0ea1b338b935)

and this my log
[qrlog.txt](https://github.com/user-attachments/files/16107848/qrlog.txt)
last taking photo on 3 july 24 on 11.55 

this my camera version
[version.txt](https://github.com/user-attachments/files/16107864/version.txt)

im using voltaic v50 and solar panel, im sure battry not empty when gopro stop

and i have 3 gopro 12 all same problem..
hope can find solution from you, and if you dont mind please send me new barcode for daily timelapse 24 hour with 5 minute interval

**Comment by dronevisionbtm** [comment]
and i hope can fnd solution from you @dnewman-gpsw

**Comment by dnewman-gpsw** [comment]
This doesn't seem to be much value in skipping 23:50 to 00:10.  Why not run a simpler script like
```!280NQmP!S!1R```

You are running old firmware, current release is 2.20.70.  (which is pretty reliable)

You are also welcome to try an experimental version (for fixing a rare start failure:)
 https://www.dropbox.com/scl/fi/z81rui7y2xeeytcyjqae2/LABS_HERO12_02_20_72b-sec.zip?rlkey=5h0h2dfnqj2exekuw0jfy9sij&dl=1

**Comment by dronevisionbtm** [comment]
hi david
hope you are well, i already test and use chat gpt for make codes for my
gopro but always fail

i hope you can help me to make this command “ camera take single photo with
5 minutes interval and only on Monday wednesday and Friday”

thanks before

best regards


Indra - Indonesia

**Comment by dnewman-gpsw** [comment]
@dronevisionbtm post what you tried in discussions, not in a closed issue thread.

**Comment by dronevisionbtm** [comment]
hi @dnewman-gpsw 
i have tried my gopro for take photo every 5 minutes and only on monday, wednesday and friday

this code i get from chatgpt, but not working (after scan camera start take photo with 1s interval)
>t:W0>t:W3>t:W5!300NQmP!S!1R

im using gopro 12 with latest firmware 02.32.70

hope can find solution from you

thanks
