### ISSUE TITLE
GoPro 11 Timelapse exposure flicker

### ISSUE THREAD

**Issue by Alxysh** [gopro/labs#993]
Hello!
I have an issue in Night Timelapse mode (I've saw it in both modes – jpg and video):
Some frames have more longer shutter speed than other. It looks like exposure flicker in final Timelapse.

Mode:  Night Timelapse JPG
Shutter: Auto
ISO: 100...400
Exposure: -1, center point measuring
Color: Wide Flat
Labs version: v2.30.70

I've also found mention about this issue [here](https://www.reddit.com/r/gopro/comments/xpgw0u/gopro_11_exposure_flicker_in_timelapse_mode/)

"Normal" shutter speed
<img width="1161" alt="Screenshot 2024-07-24 at 10 35 41" src="https://github.com/user-attachments/assets/493b1a02-6ca5-4647-bb88-b5617f605eb7">
"Longer" shutter speed
<img width="1161" alt="Screenshot 2024-07-24 at 10 35 45" src="https://github.com/user-attachments/assets/6b6c7591-1c0e-4bbe-9a39-711c4ce25c6f">
"Normal" shutter speed
<img width="1135" alt="Screenshot 2024-07-24 at 10 36 24" src="https://github.com/user-attachments/assets/1f218330-6c20-4a2b-9a17-a31604045cab">
"Longer" shutter speed
<img width="1135" alt="Screenshot 2024-07-24 at 10 36 39" src="https://github.com/user-attachments/assets/c06d5845-78ff-45b3-803e-803cd14775fd">

**Comment by dnewman-gpsw** [comment]
Think this might very rare (I've never experienced it), also this is not a Labs feature. So if the camera is doing this all the time, regular contact support. The Issue area here is for Labs features that are not working.
